/* ===============================================================
Copyright 2026, Infineon Technologies AG or an 
affiliate of Infineon Technologies AG.  All rights reserved.
 
This software, associated documentation and materials ("Software") is owned by
Infineon Technologies AG or one of its affiliates ("Infineon") and is 
protected by and subject to worldwide patent protection (United States and 
foreign), United States copyright laws and international treaty provisions. 
Therefore, you may use this Software only as provided in the license agreement
accompanying the software package from which you obtained this 
Software ("EULA"). If no EULA applies, then any reproduction, modification, 
translation, compilation, or representation of this Software is prohibited 
without the express written permission of Infineon.
 
Disclaimer: THIS SOFTWARE IS PROVIDED AS-IS, WITH NO WARRANTY OF 
ANY KIND, EXPRESS OR IMPLIED, INCLUDING, BUT NOT LIMITED TO, 
NONINFRINGEMENT, IMPLIED WARRANTIES OF  MERCHANTABILITY AND
FITNESS FOR A PARTICULAR PURPOSE.  Infineon reserves the right to make
changes to the Software without notice. Infineon does not assume any liability
arising out of the application or use of the Software or any product or 
circuit described in the Software. Infineon does not authorize its products 
for use in any products where a malfunction or failure of the Infineon product 
may reasonably be expected to result in significant property damage, injury or
death ("High Risk Product").  By including Infineon 's product in a High Risk 
Product, the manufacturer of such system or application assumes all risk of 
such use and in doing so agrees to indemnify Infineon against all liability.

 ===============================================================
*/ 
// File : InterruptController_ICcomponent_PRIO_RESOLUTION_Grouping_Priority_Circuit00.sv 
// Author : tahiraga 
// Date : 18:21:33    21/09/2026 
// Revision :  
// =============================================================== 
// Description : 
/*
---- Auto Generated by MetaRTL , a MetaGen application
---- Contact: ParitoshKumar.Sinha@infineon.com
---- Contact: Yash.Ranjan@infineon.com
===============================================================
*/


module InterruptController_ICcomponent_PRIO_RESOLUTION_Grouping_Priority_Circuit00 (
    input pend_int_1,
    input req_int_1,
    input active_int_1,
    output prio_0,
    input [2:0] sel_prio_int_1,
    input pend_int_4,
    input req_int_4,
    input active_int_4,
    output prio_1,
    input [2:0] sel_prio_int_4,
    input pend_int_7,
    input req_int_7,
    input active_int_7,
    output prio_2,
    input [2:0] sel_prio_int_7,
    input pend_int_11,
    input req_int_11,
    input active_int_11,
    output prio_3,
    input [2:0] sel_prio_int_11,
    input pend_int_15,
    input req_int_15,
    input active_int_15,
    output prio_4,
    input [2:0] sel_prio_int_15,
    input pend_int_19,
    input req_int_19,
    input active_int_19,
    output prio_5,
    input [2:0] sel_prio_int_19,
    input pend_int_21,
    input req_int_21,
    input active_int_21,
    output prio_6,
    input [2:0] sel_prio_int_21,
    input pend_int_28,
    input req_int_28,
    input active_int_28,
    output prio_7,
    input [2:0] sel_prio_int_28,
    input int_ended
);

logic   NOT01_Outp_s;
logic   [7:0] CONCAT07_Outp_s;
logic   [7:0] CONCAT06_Outp_s;
logic   [7:0] CONCAT05_Outp_s;
logic   [7:0] CONCAT04_Outp_s;
logic   [7:0] CONCAT03_Outp_s;
logic   [7:0] CONCAT02_Outp_s;
logic   [7:0] CONCAT01_Outp_s;
logic   mask_pend_int_28_Outp_s;
logic   mask_pend_int_21_Outp_s;
logic   mask_pend_int_19_Outp_s;
logic   mask_pend_int_15_Outp_s;
logic   mask_pend_int_11_Outp_s;
logic   mask_pend_int_7_Outp_s;
logic   mask_pend_int_4_Outp_s;
logic   mask_pend_int_1_Outp_s;
logic   [7:0] CONCAT00_Outp_s;

logic   prio_7_Outp_s;
logic   prio_6_Outp_s;
logic   prio_5_Outp_s;
logic   prio_4_Outp_s;
logic   prio_3_Outp_s;
logic   prio_2_Outp_s;
logic   prio_1_Outp_s;
logic   prio_0_Outp_s;

assign NOT01_Outp_s = ~((~(int_ended & (| {active_int_1,active_int_4,active_int_7,active_int_11,active_int_15,active_int_19,active_int_21,active_int_28}))) & (| {req_int_1,req_int_4,req_int_7,req_int_11,req_int_15,req_int_19,req_int_21,req_int_28}));

assign CONCAT07_Outp_s = {(sel_prio_int_28 == 3'b111 ? 1'b1 : 1'b0),(sel_prio_int_21 == 3'b111 ? 1'b1 : 1'b0),(sel_prio_int_19 == 3'b111 ? 1'b1 : 1'b0),(sel_prio_int_15 == 3'b111 ? 1'b1 : 1'b0),(sel_prio_int_11 == 3'b111 ? 1'b1 : 1'b0),(sel_prio_int_7 == 3'b111 ? 1'b1 : 1'b0),(sel_prio_int_4 == 3'b111 ? 1'b1 : 1'b0),(sel_prio_int_1 == 3'b111 ? 1'b1 : 1'b0)};

assign CONCAT06_Outp_s = {(sel_prio_int_28 == 3'b110 ? 1'b1 : 1'b0),(sel_prio_int_21 == 3'b110 ? 1'b1 : 1'b0),(sel_prio_int_19 == 3'b110 ? 1'b1 : 1'b0),(sel_prio_int_15 == 3'b110 ? 1'b1 : 1'b0),(sel_prio_int_11 == 3'b110 ? 1'b1 : 1'b0),(sel_prio_int_7 == 3'b110 ? 1'b1 : 1'b0),(sel_prio_int_4 == 3'b110 ? 1'b1 : 1'b0),(sel_prio_int_1 == 3'b110 ? 1'b1 : 1'b0)};

assign CONCAT05_Outp_s = {(sel_prio_int_28 == 3'b101 ? 1'b1 : 1'b0),(sel_prio_int_21 == 3'b101 ? 1'b1 : 1'b0),(sel_prio_int_19 == 3'b101 ? 1'b1 : 1'b0),(sel_prio_int_15 == 3'b101 ? 1'b1 : 1'b0),(sel_prio_int_11 == 3'b101 ? 1'b1 : 1'b0),(sel_prio_int_7 == 3'b101 ? 1'b1 : 1'b0),(sel_prio_int_4 == 3'b101 ? 1'b1 : 1'b0),(sel_prio_int_1 == 3'b101 ? 1'b1 : 1'b0)};

assign CONCAT04_Outp_s = {(sel_prio_int_28 == 3'b100 ? 1'b1 : 1'b0),(sel_prio_int_21 == 3'b100 ? 1'b1 : 1'b0),(sel_prio_int_19 == 3'b100 ? 1'b1 : 1'b0),(sel_prio_int_15 == 3'b100 ? 1'b1 : 1'b0),(sel_prio_int_11 == 3'b100 ? 1'b1 : 1'b0),(sel_prio_int_7 == 3'b100 ? 1'b1 : 1'b0),(sel_prio_int_4 == 3'b100 ? 1'b1 : 1'b0),(sel_prio_int_1 == 3'b100 ? 1'b1 : 1'b0)};

assign CONCAT03_Outp_s = {(sel_prio_int_28 == 3'b11 ? 1'b1 : 1'b0),(sel_prio_int_21 == 3'b11 ? 1'b1 : 1'b0),(sel_prio_int_19 == 3'b11 ? 1'b1 : 1'b0),(sel_prio_int_15 == 3'b11 ? 1'b1 : 1'b0),(sel_prio_int_11 == 3'b11 ? 1'b1 : 1'b0),(sel_prio_int_7 == 3'b11 ? 1'b1 : 1'b0),(sel_prio_int_4 == 3'b11 ? 1'b1 : 1'b0),(sel_prio_int_1 == 3'b11 ? 1'b1 : 1'b0)};

assign CONCAT02_Outp_s = {(sel_prio_int_28 == 3'b10 ? 1'b1 : 1'b0),(sel_prio_int_21 == 3'b10 ? 1'b1 : 1'b0),(sel_prio_int_19 == 3'b10 ? 1'b1 : 1'b0),(sel_prio_int_15 == 3'b10 ? 1'b1 : 1'b0),(sel_prio_int_11 == 3'b10 ? 1'b1 : 1'b0),(sel_prio_int_7 == 3'b10 ? 1'b1 : 1'b0),(sel_prio_int_4 == 3'b10 ? 1'b1 : 1'b0),(sel_prio_int_1 == 3'b10 ? 1'b1 : 1'b0)};

assign CONCAT01_Outp_s = {(sel_prio_int_28 == 3'b1 ? 1'b1 : 1'b0),(sel_prio_int_21 == 3'b1 ? 1'b1 : 1'b0),(sel_prio_int_19 == 3'b1 ? 1'b1 : 1'b0),(sel_prio_int_15 == 3'b1 ? 1'b1 : 1'b0),(sel_prio_int_11 == 3'b1 ? 1'b1 : 1'b0),(sel_prio_int_7 == 3'b1 ? 1'b1 : 1'b0),(sel_prio_int_4 == 3'b1 ? 1'b1 : 1'b0),(sel_prio_int_1 == 3'b1 ? 1'b1 : 1'b0)};

assign mask_pend_int_28_Outp_s = pend_int_28 & (NOT01_Outp_s | req_int_28);

assign mask_pend_int_21_Outp_s = pend_int_21 & (NOT01_Outp_s | req_int_21);

assign mask_pend_int_19_Outp_s = pend_int_19 & (NOT01_Outp_s | req_int_19);

assign mask_pend_int_15_Outp_s = pend_int_15 & (NOT01_Outp_s | req_int_15);

assign mask_pend_int_11_Outp_s = pend_int_11 & (NOT01_Outp_s | req_int_11);

assign mask_pend_int_7_Outp_s = pend_int_7 & (NOT01_Outp_s | req_int_7);

assign mask_pend_int_4_Outp_s = pend_int_4 & (NOT01_Outp_s | req_int_4);

assign mask_pend_int_1_Outp_s = pend_int_1 & (NOT01_Outp_s | req_int_1);

assign CONCAT00_Outp_s = {(sel_prio_int_28 == 3'b0 ? 1'b1 : 1'b0),(sel_prio_int_21 == 3'b0 ? 1'b1 : 1'b0),(sel_prio_int_19 == 3'b0 ? 1'b1 : 1'b0),(sel_prio_int_15 == 3'b0 ? 1'b1 : 1'b0),(sel_prio_int_11 == 3'b0 ? 1'b1 : 1'b0),(sel_prio_int_7 == 3'b0 ? 1'b1 : 1'b0),(sel_prio_int_4 == 3'b0 ? 1'b1 : 1'b0),(sel_prio_int_1 == 3'b0 ? 1'b1 : 1'b0)};

always_comb
begin
    case (CONCAT07_Outp_s)
        8'b1 : prio_7_Outp_s = mask_pend_int_1_Outp_s;
        8'b10 : prio_7_Outp_s = mask_pend_int_4_Outp_s;
        8'b100 : prio_7_Outp_s = mask_pend_int_7_Outp_s;
        8'b1000 : prio_7_Outp_s = mask_pend_int_11_Outp_s;
        8'b10000 : prio_7_Outp_s = mask_pend_int_15_Outp_s;
        8'b100000 : prio_7_Outp_s = mask_pend_int_19_Outp_s;
        8'b1000000 : prio_7_Outp_s = mask_pend_int_21_Outp_s;
        8'b10000000 : prio_7_Outp_s = mask_pend_int_28_Outp_s;
        default : prio_7_Outp_s = 1'b0;
    endcase
end

always_comb
begin
    case (CONCAT06_Outp_s)
        8'b1 : prio_6_Outp_s = mask_pend_int_1_Outp_s;
        8'b10 : prio_6_Outp_s = mask_pend_int_4_Outp_s;
        8'b100 : prio_6_Outp_s = mask_pend_int_7_Outp_s;
        8'b1000 : prio_6_Outp_s = mask_pend_int_11_Outp_s;
        8'b10000 : prio_6_Outp_s = mask_pend_int_15_Outp_s;
        8'b100000 : prio_6_Outp_s = mask_pend_int_19_Outp_s;
        8'b1000000 : prio_6_Outp_s = mask_pend_int_21_Outp_s;
        8'b10000000 : prio_6_Outp_s = mask_pend_int_28_Outp_s;
        default : prio_6_Outp_s = 1'b0;
    endcase
end

always_comb
begin
    case (CONCAT05_Outp_s)
        8'b1 : prio_5_Outp_s = mask_pend_int_1_Outp_s;
        8'b10 : prio_5_Outp_s = mask_pend_int_4_Outp_s;
        8'b100 : prio_5_Outp_s = mask_pend_int_7_Outp_s;
        8'b1000 : prio_5_Outp_s = mask_pend_int_11_Outp_s;
        8'b10000 : prio_5_Outp_s = mask_pend_int_15_Outp_s;
        8'b100000 : prio_5_Outp_s = mask_pend_int_19_Outp_s;
        8'b1000000 : prio_5_Outp_s = mask_pend_int_21_Outp_s;
        8'b10000000 : prio_5_Outp_s = mask_pend_int_28_Outp_s;
        default : prio_5_Outp_s = 1'b0;
    endcase
end

always_comb
begin
    case (CONCAT04_Outp_s)
        8'b1 : prio_4_Outp_s = mask_pend_int_1_Outp_s;
        8'b10 : prio_4_Outp_s = mask_pend_int_4_Outp_s;
        8'b100 : prio_4_Outp_s = mask_pend_int_7_Outp_s;
        8'b1000 : prio_4_Outp_s = mask_pend_int_11_Outp_s;
        8'b10000 : prio_4_Outp_s = mask_pend_int_15_Outp_s;
        8'b100000 : prio_4_Outp_s = mask_pend_int_19_Outp_s;
        8'b1000000 : prio_4_Outp_s = mask_pend_int_21_Outp_s;
        8'b10000000 : prio_4_Outp_s = mask_pend_int_28_Outp_s;
        default : prio_4_Outp_s = 1'b0;
    endcase
end

always_comb
begin
    case (CONCAT03_Outp_s)
        8'b1 : prio_3_Outp_s = mask_pend_int_1_Outp_s;
        8'b10 : prio_3_Outp_s = mask_pend_int_4_Outp_s;
        8'b100 : prio_3_Outp_s = mask_pend_int_7_Outp_s;
        8'b1000 : prio_3_Outp_s = mask_pend_int_11_Outp_s;
        8'b10000 : prio_3_Outp_s = mask_pend_int_15_Outp_s;
        8'b100000 : prio_3_Outp_s = mask_pend_int_19_Outp_s;
        8'b1000000 : prio_3_Outp_s = mask_pend_int_21_Outp_s;
        8'b10000000 : prio_3_Outp_s = mask_pend_int_28_Outp_s;
        default : prio_3_Outp_s = 1'b0;
    endcase
end

always_comb
begin
    case (CONCAT02_Outp_s)
        8'b1 : prio_2_Outp_s = mask_pend_int_1_Outp_s;
        8'b10 : prio_2_Outp_s = mask_pend_int_4_Outp_s;
        8'b100 : prio_2_Outp_s = mask_pend_int_7_Outp_s;
        8'b1000 : prio_2_Outp_s = mask_pend_int_11_Outp_s;
        8'b10000 : prio_2_Outp_s = mask_pend_int_15_Outp_s;
        8'b100000 : prio_2_Outp_s = mask_pend_int_19_Outp_s;
        8'b1000000 : prio_2_Outp_s = mask_pend_int_21_Outp_s;
        8'b10000000 : prio_2_Outp_s = mask_pend_int_28_Outp_s;
        default : prio_2_Outp_s = 1'b0;
    endcase
end

always_comb
begin
    case (CONCAT01_Outp_s)
        8'b1 : prio_1_Outp_s = mask_pend_int_1_Outp_s;
        8'b10 : prio_1_Outp_s = mask_pend_int_4_Outp_s;
        8'b100 : prio_1_Outp_s = mask_pend_int_7_Outp_s;
        8'b1000 : prio_1_Outp_s = mask_pend_int_11_Outp_s;
        8'b10000 : prio_1_Outp_s = mask_pend_int_15_Outp_s;
        8'b100000 : prio_1_Outp_s = mask_pend_int_19_Outp_s;
        8'b1000000 : prio_1_Outp_s = mask_pend_int_21_Outp_s;
        8'b10000000 : prio_1_Outp_s = mask_pend_int_28_Outp_s;
        default : prio_1_Outp_s = 1'b0;
    endcase
end

always_comb
begin
    case (CONCAT00_Outp_s)
        8'b1 : prio_0_Outp_s = mask_pend_int_1_Outp_s;
        8'b10 : prio_0_Outp_s = mask_pend_int_4_Outp_s;
        8'b100 : prio_0_Outp_s = mask_pend_int_7_Outp_s;
        8'b1000 : prio_0_Outp_s = mask_pend_int_11_Outp_s;
        8'b10000 : prio_0_Outp_s = mask_pend_int_15_Outp_s;
        8'b100000 : prio_0_Outp_s = mask_pend_int_19_Outp_s;
        8'b1000000 : prio_0_Outp_s = mask_pend_int_21_Outp_s;
        8'b10000000 : prio_0_Outp_s = mask_pend_int_28_Outp_s;
        default : prio_0_Outp_s = 1'b0;
    endcase
end

InterruptController_Priority_Circuit comp_Priority_Circuit(
    .pend_LEVEL_0 ( prio_0_Outp_s ),
    .pend_LEVEL_1 ( prio_1_Outp_s ),
    .pend_LEVEL_2 ( prio_2_Outp_s ),
    .pend_LEVEL_3 ( prio_3_Outp_s ),
    .pend_LEVEL_4 ( prio_4_Outp_s ),
    .pend_LEVEL_5 ( prio_5_Outp_s ),
    .pend_LEVEL_6 ( prio_6_Outp_s ),
    .pend_LEVEL_7 ( prio_7_Outp_s ),
    .prio_LEVEL_0 ( prio_0        ),
    .prio_LEVEL_1 ( prio_1        ),
    .prio_LEVEL_2 ( prio_2        ),
    .prio_LEVEL_3 ( prio_3        ),
    .prio_LEVEL_4 ( prio_4        ),
    .prio_LEVEL_5 ( prio_5        ),
    .prio_LEVEL_6 ( prio_6        ),
    .prio_LEVEL_7 ( prio_7        )
);


endmodule

