/* ===============================================================
Copyright 2026, Infineon Technologies AG or an 
affiliate of Infineon Technologies AG.  All rights reserved.
 
This software, associated documentation and materials ("Software") is owned by
Infineon Technologies AG or one of its affiliates ("Infineon") and is 
protected by and subject to worldwide patent protection (United States and 
foreign), United States copyright laws and international treaty provisions. 
Therefore, you may use this Software only as provided in the license agreement
accompanying the software package from which you obtained this 
Software ("EULA"). If no EULA applies, then any reproduction, modification, 
translation, compilation, or representation of this Software is prohibited 
without the express written permission of Infineon.
 
Disclaimer: THIS SOFTWARE IS PROVIDED AS-IS, WITH NO WARRANTY OF 
ANY KIND, EXPRESS OR IMPLIED, INCLUDING, BUT NOT LIMITED TO, 
NONINFRINGEMENT, IMPLIED WARRANTIES OF  MERCHANTABILITY AND
FITNESS FOR A PARTICULAR PURPOSE.  Infineon reserves the right to make
changes to the Software without notice. Infineon does not assume any liability
arising out of the application or use of the Software or any product or 
circuit described in the Software. Infineon does not authorize its products 
for use in any products where a malfunction or failure of the Infineon product 
may reasonably be expected to result in significant property damage, injury or
death ("High Risk Product").  By including Infineon 's product in a High Risk 
Product, the manufacturer of such system or application assumes all risk of 
such use and in doing so agrees to indemnify Infineon against all liability.

 ===============================================================
*/ 
// File : InterruptController_ICcomponent_PRIO_RESOLUTION_Regrouping_Priority_Circuit00.sv 
// Author : tahiraga 
// Date : 18:21:29    21/09/2026 
// Revision :  
// =============================================================== 
// Description : 
/*
---- Auto Generated by MetaRTL , a MetaGen application
---- Contact: ParitoshKumar.Sinha@infineon.com
---- Contact: Yash.Ranjan@infineon.com
===============================================================
*/


module InterruptController_ICcomponent_PRIO_RESOLUTION_Regrouping_Priority_Circuit00 (
    input pend_bit,
    input Grouping_Priority_Circuit00_prio_0_in,
    output logic  int_1_out,
    input Grouping_Priority_Circuit00_prio_1_in,
    output logic  int_4_out,
    input Grouping_Priority_Circuit00_prio_2_in,
    output logic  int_7_out,
    input Grouping_Priority_Circuit00_prio_3_in,
    output logic  int_11_out,
    input Grouping_Priority_Circuit00_prio_4_in,
    output logic  int_15_out,
    input Grouping_Priority_Circuit00_prio_5_in,
    output logic  int_19_out,
    input Grouping_Priority_Circuit00_prio_6_in,
    output logic  int_21_out,
    input Grouping_Priority_Circuit00_prio_7_in,
    output logic  int_28_out,
    input [2:0] int_1_prio,
    input [2:0] int_4_prio,
    input [2:0] int_7_prio,
    input [2:0] int_11_prio,
    input [2:0] int_15_prio,
    input [2:0] int_19_prio,
    input [2:0] int_21_prio,
    input [2:0] int_28_prio
);

logic   prio_7_pending_Outp_s;
logic   prio_6_pending_Outp_s;
logic   prio_5_pending_Outp_s;
logic   prio_4_pending_Outp_s;
logic   prio_3_pending_Outp_s;
logic   prio_2_pending_Outp_s;
logic   prio_1_pending_Outp_s;
logic   prio_0_pending_Outp_s;


always_comb
begin
    case (int_28_prio)
        3'b0 : int_28_out = prio_0_pending_Outp_s;
        3'b1 : int_28_out = prio_1_pending_Outp_s;
        3'b10 : int_28_out = prio_2_pending_Outp_s;
        3'b11 : int_28_out = prio_3_pending_Outp_s;
        3'b100 : int_28_out = prio_4_pending_Outp_s;
        3'b101 : int_28_out = prio_5_pending_Outp_s;
        3'b110 : int_28_out = prio_6_pending_Outp_s;
        3'b111 : int_28_out = prio_7_pending_Outp_s;
        default : int_28_out = 1'b0;
    endcase
end

always_comb
begin
    case (int_21_prio)
        3'b0 : int_21_out = prio_0_pending_Outp_s;
        3'b1 : int_21_out = prio_1_pending_Outp_s;
        3'b10 : int_21_out = prio_2_pending_Outp_s;
        3'b11 : int_21_out = prio_3_pending_Outp_s;
        3'b100 : int_21_out = prio_4_pending_Outp_s;
        3'b101 : int_21_out = prio_5_pending_Outp_s;
        3'b110 : int_21_out = prio_6_pending_Outp_s;
        3'b111 : int_21_out = prio_7_pending_Outp_s;
        default : int_21_out = 1'b0;
    endcase
end

always_comb
begin
    case (int_19_prio)
        3'b0 : int_19_out = prio_0_pending_Outp_s;
        3'b1 : int_19_out = prio_1_pending_Outp_s;
        3'b10 : int_19_out = prio_2_pending_Outp_s;
        3'b11 : int_19_out = prio_3_pending_Outp_s;
        3'b100 : int_19_out = prio_4_pending_Outp_s;
        3'b101 : int_19_out = prio_5_pending_Outp_s;
        3'b110 : int_19_out = prio_6_pending_Outp_s;
        3'b111 : int_19_out = prio_7_pending_Outp_s;
        default : int_19_out = 1'b0;
    endcase
end

always_comb
begin
    case (int_15_prio)
        3'b0 : int_15_out = prio_0_pending_Outp_s;
        3'b1 : int_15_out = prio_1_pending_Outp_s;
        3'b10 : int_15_out = prio_2_pending_Outp_s;
        3'b11 : int_15_out = prio_3_pending_Outp_s;
        3'b100 : int_15_out = prio_4_pending_Outp_s;
        3'b101 : int_15_out = prio_5_pending_Outp_s;
        3'b110 : int_15_out = prio_6_pending_Outp_s;
        3'b111 : int_15_out = prio_7_pending_Outp_s;
        default : int_15_out = 1'b0;
    endcase
end

always_comb
begin
    case (int_11_prio)
        3'b0 : int_11_out = prio_0_pending_Outp_s;
        3'b1 : int_11_out = prio_1_pending_Outp_s;
        3'b10 : int_11_out = prio_2_pending_Outp_s;
        3'b11 : int_11_out = prio_3_pending_Outp_s;
        3'b100 : int_11_out = prio_4_pending_Outp_s;
        3'b101 : int_11_out = prio_5_pending_Outp_s;
        3'b110 : int_11_out = prio_6_pending_Outp_s;
        3'b111 : int_11_out = prio_7_pending_Outp_s;
        default : int_11_out = 1'b0;
    endcase
end

always_comb
begin
    case (int_7_prio)
        3'b0 : int_7_out = prio_0_pending_Outp_s;
        3'b1 : int_7_out = prio_1_pending_Outp_s;
        3'b10 : int_7_out = prio_2_pending_Outp_s;
        3'b11 : int_7_out = prio_3_pending_Outp_s;
        3'b100 : int_7_out = prio_4_pending_Outp_s;
        3'b101 : int_7_out = prio_5_pending_Outp_s;
        3'b110 : int_7_out = prio_6_pending_Outp_s;
        3'b111 : int_7_out = prio_7_pending_Outp_s;
        default : int_7_out = 1'b0;
    endcase
end

always_comb
begin
    case (int_4_prio)
        3'b0 : int_4_out = prio_0_pending_Outp_s;
        3'b1 : int_4_out = prio_1_pending_Outp_s;
        3'b10 : int_4_out = prio_2_pending_Outp_s;
        3'b11 : int_4_out = prio_3_pending_Outp_s;
        3'b100 : int_4_out = prio_4_pending_Outp_s;
        3'b101 : int_4_out = prio_5_pending_Outp_s;
        3'b110 : int_4_out = prio_6_pending_Outp_s;
        3'b111 : int_4_out = prio_7_pending_Outp_s;
        default : int_4_out = 1'b0;
    endcase
end

assign prio_7_pending_Outp_s = pend_bit & Grouping_Priority_Circuit00_prio_7_in;

assign prio_6_pending_Outp_s = pend_bit & Grouping_Priority_Circuit00_prio_6_in;

assign prio_5_pending_Outp_s = pend_bit & Grouping_Priority_Circuit00_prio_5_in;

assign prio_4_pending_Outp_s = pend_bit & Grouping_Priority_Circuit00_prio_4_in;

assign prio_3_pending_Outp_s = pend_bit & Grouping_Priority_Circuit00_prio_3_in;

assign prio_2_pending_Outp_s = pend_bit & Grouping_Priority_Circuit00_prio_2_in;

assign prio_1_pending_Outp_s = pend_bit & Grouping_Priority_Circuit00_prio_1_in;

assign prio_0_pending_Outp_s = pend_bit & Grouping_Priority_Circuit00_prio_0_in;

always_comb
begin
    case (int_1_prio)
        3'b0 : int_1_out = prio_0_pending_Outp_s;
        3'b1 : int_1_out = prio_1_pending_Outp_s;
        3'b10 : int_1_out = prio_2_pending_Outp_s;
        3'b11 : int_1_out = prio_3_pending_Outp_s;
        3'b100 : int_1_out = prio_4_pending_Outp_s;
        3'b101 : int_1_out = prio_5_pending_Outp_s;
        3'b110 : int_1_out = prio_6_pending_Outp_s;
        3'b111 : int_1_out = prio_7_pending_Outp_s;
        default : int_1_out = 1'b0;
    endcase
end


endmodule

