/* ===============================================================
Copyright 2026, Infineon Technologies AG or an 
affiliate of Infineon Technologies AG.  All rights reserved.
 
This software, associated documentation and materials ("Software") is owned by
Infineon Technologies AG or one of its affiliates ("Infineon") and is 
protected by and subject to worldwide patent protection (United States and 
foreign), United States copyright laws and international treaty provisions. 
Therefore, you may use this Software only as provided in the license agreement
accompanying the software package from which you obtained this 
Software ("EULA"). If no EULA applies, then any reproduction, modification, 
translation, compilation, or representation of this Software is prohibited 
without the express written permission of Infineon.
 
Disclaimer: THIS SOFTWARE IS PROVIDED AS-IS, WITH NO WARRANTY OF 
ANY KIND, EXPRESS OR IMPLIED, INCLUDING, BUT NOT LIMITED TO, 
NONINFRINGEMENT, IMPLIED WARRANTIES OF  MERCHANTABILITY AND
FITNESS FOR A PARTICULAR PURPOSE.  Infineon reserves the right to make
changes to the Software without notice. Infineon does not assume any liability
arising out of the application or use of the Software or any product or 
circuit described in the Software. Infineon does not authorize its products 
for use in any products where a malfunction or failure of the Infineon product 
may reasonably be expected to result in significant property damage, injury or
death ("High Risk Product").  By including Infineon 's product in a High Risk 
Product, the manufacturer of such system or application assumes all risk of 
such use and in doing so agrees to indemnify Infineon against all liability.

 ===============================================================
*/ 
// File : InterruptController_Reg_IF_AHB_RAI_Bridge.sv 
// Author : tahiraga 
// Date : 18:22:02    21/09/2026 
// Revision :  
// =============================================================== 
// Description : 
/*
---- Auto Generated by MetaRTL , a MetaGen application
---- Contact: ParitoshKumar.Sinha@infineon.com
---- Contact: Yash.Ranjan@infineon.com
===============================================================
*/


module InterruptController_Reg_IF_AHB_RAI_Bridge (
    input [31:0] HADDR_i,
    input [31:0] HWDATA_i,
    input [2:0] HBURST_i,
    input HMASTLOCK_i,
    input [2:0] HSIZE_i,
    input [1:0] HTRANS_i,
    input HWRITE_i,
    input HSEL_i,
    input HREADY_i,
    output [31:0] HRDATA_o,
    output HREADYOUT_o,
    output HRESP_o,
    input [3:0] HPROT_i,
    input [31:0] rai_per_rdata_i,
    output rai_per_acc_en_o,
    input rai_per_ack_i,
    output rai_per_wr_en_o,
    output [1:0] csc_access_size_o,
    output [31:0] rai_per_wdata_o,
    input rai_per_err_i,
    output [31:0] bridge_fsm_haddr_reg_Outp_out_out,
    input HCLK_i,
    input HRESET_n_i
);

logic   [2:0] bridge_fsm_hsize_o_s;
logic   bridge_fsm_hwrite_o_s;
logic   bridge_fsm_access_en_s;
logic   [31:0] bridge_fsm_haddr_o_s;
logic   [31:0] bridge_fsm_hwdata_o_s;
logic   bridge_sync_access_done_o_s;

InterruptController_Reg_IF_AHB_RAI_Bridge_bridge_fsm comp_bridge_fsm(
    .haddr_i            ( HADDR_i                           ),
    .hwdata_i           ( HWDATA_i                          ),
    .hsize_i            ( HSIZE_i                           ),
    .htrans_i           ( HTRANS_i                          ),
    .hwrite_i           ( HWRITE_i                          ),
    .hsel_i             ( HSEL_i                            ),
    .hready_i           ( HREADY_i                          ),
    .rai_per_err_i      ( rai_per_err_i                     ),
    .access_done_i      ( bridge_sync_access_done_o_s       ),
    .HCLK_i             ( HCLK_i                            ),
    .HRESET_n_i         ( HRESET_n_i                        ),
    .hreadyout_o        ( HREADYOUT_o                       ),
    .hresp_o            ( HRESP_o                           ),
    .hsize_o            ( bridge_fsm_hsize_o_s              ),
    .hwrite_o           ( bridge_fsm_hwrite_o_s             ),
    .access_en          ( bridge_fsm_access_en_s            ),
    .haddr_o            ( bridge_fsm_haddr_o_s              ),
    .hwdata_o           ( bridge_fsm_hwdata_o_s             ),
    .haddr_reg_Outp_out ( bridge_fsm_haddr_reg_Outp_out_out )
);

InterruptController_Reg_IF_AHB_RAI_Bridge_bridge_sync comp_bridge_sync(
    .hsel_i            ( bridge_fsm_access_en_s      ),
    .hsize_i           ( bridge_fsm_hsize_o_s        ),
    .hwrite_i          ( bridge_fsm_hwrite_o_s       ),
    .haddr_i           ( bridge_fsm_haddr_o_s        ),
    .hwdata_i          ( bridge_fsm_hwdata_o_s       ),
    .rai_per_ack_i     ( rai_per_ack_i               ),
    .rai_per_rdata_i   ( rai_per_rdata_i             ),
    .hrdata_o          ( HRDATA_o                    ),
    .access_done_o     ( bridge_sync_access_done_o_s ),
    .rai_per_acc_en_o  ( rai_per_acc_en_o            ),
    .rai_per_wr_en_o   ( rai_per_wr_en_o             ),
    .csc_access_size_o ( csc_access_size_o           ),
    .rai_per_wdata_o   ( rai_per_wdata_o             )
);


endmodule

