/* ===============================================================
Copyright 2026, Infineon Technologies AG or an 
affiliate of Infineon Technologies AG.  All rights reserved.
 
This software, associated documentation and materials ("Software") is owned by
Infineon Technologies AG or one of its affiliates ("Infineon") and is 
protected by and subject to worldwide patent protection (United States and 
foreign), United States copyright laws and international treaty provisions. 
Therefore, you may use this Software only as provided in the license agreement
accompanying the software package from which you obtained this 
Software ("EULA"). If no EULA applies, then any reproduction, modification, 
translation, compilation, or representation of this Software is prohibited 
without the express written permission of Infineon.
 
Disclaimer: THIS SOFTWARE IS PROVIDED AS-IS, WITH NO WARRANTY OF 
ANY KIND, EXPRESS OR IMPLIED, INCLUDING, BUT NOT LIMITED TO, 
NONINFRINGEMENT, IMPLIED WARRANTIES OF  MERCHANTABILITY AND
FITNESS FOR A PARTICULAR PURPOSE.  Infineon reserves the right to make
changes to the Software without notice. Infineon does not assume any liability
arising out of the application or use of the Software or any product or 
circuit described in the Software. Infineon does not authorize its products 
for use in any products where a malfunction or failure of the Infineon product 
may reasonably be expected to result in significant property damage, injury or
death ("High Risk Product").  By including Infineon 's product in a High Risk 
Product, the manufacturer of such system or application assumes all risk of 
such use and in doing so agrees to indemnify Infineon against all liability.

 ===============================================================
*/ 
// File : InterruptController_Reg_IF_Top_CSC_Top_CSC_DefaultInterface_Top_CSC_DefaultInterface_ReadCircuit.sv 
// Author : tahiraga 
// Date : 18:20:29    21/09/2026 
// Revision :  
// =============================================================== 
// Description : 
/*
---- Auto Generated by MetaRTL , a MetaGen application
---- Contact: ParitoshKumar.Sinha@infineon.com
---- Contact: Yash.Ranjan@infineon.com
===============================================================
*/


module InterruptController_Reg_IF_Top_CSC_Top_CSC_DefaultInterface_Top_CSC_DefaultInterface_ReadCircuit (
    output [31:0] DefaultInterface_RC_data_out,
    input DefaultInterface_RC_rd_en,
    input [4:0] DefaultInterface_RC_Shifting_Value_Mux_out,
    input [31:0] DefaultInterface_RC_Masking_Mux_out,
    input Port_of_Reg_enable_int_31,
    output DefaultInterface_RC_enable_int_31_out,
    input Port_of_Reg_enable_int_30,
    output DefaultInterface_RC_enable_int_30_out,
    input Port_of_Reg_enable_int_29,
    output DefaultInterface_RC_enable_int_29_out,
    input Port_of_Reg_enable_int_28,
    output DefaultInterface_RC_enable_int_28_out,
    input Port_of_Reg_enable_int_27,
    output DefaultInterface_RC_enable_int_27_out,
    input Port_of_Reg_enable_int_26,
    output DefaultInterface_RC_enable_int_26_out,
    input Port_of_Reg_enable_int_25,
    output DefaultInterface_RC_enable_int_25_out,
    input Port_of_Reg_enable_int_24,
    output DefaultInterface_RC_enable_int_24_out,
    input Port_of_Reg_enable_int_23,
    output DefaultInterface_RC_enable_int_23_out,
    input Port_of_Reg_enable_int_22,
    output DefaultInterface_RC_enable_int_22_out,
    input Port_of_Reg_enable_int_21,
    output DefaultInterface_RC_enable_int_21_out,
    input Port_of_Reg_enable_int_20,
    output DefaultInterface_RC_enable_int_20_out,
    input Port_of_Reg_enable_int_19,
    output DefaultInterface_RC_enable_int_19_out,
    input Port_of_Reg_enable_int_18,
    output DefaultInterface_RC_enable_int_18_out,
    input Port_of_Reg_enable_int_17,
    output DefaultInterface_RC_enable_int_17_out,
    input Port_of_Reg_enable_int_16,
    output DefaultInterface_RC_enable_int_16_out,
    input Port_of_Reg_enable_int_15,
    output DefaultInterface_RC_enable_int_15_out,
    input Port_of_Reg_enable_int_14,
    output DefaultInterface_RC_enable_int_14_out,
    input Port_of_Reg_enable_int_13,
    output DefaultInterface_RC_enable_int_13_out,
    input Port_of_Reg_enable_int_12,
    output DefaultInterface_RC_enable_int_12_out,
    input Port_of_Reg_enable_int_11,
    output DefaultInterface_RC_enable_int_11_out,
    input Port_of_Reg_enable_int_10,
    output DefaultInterface_RC_enable_int_10_out,
    input Port_of_Reg_enable_int_9,
    output DefaultInterface_RC_enable_int_9_out,
    input Port_of_Reg_enable_int_8,
    output DefaultInterface_RC_enable_int_8_out,
    input Port_of_Reg_enable_int_7,
    output DefaultInterface_RC_enable_int_7_out,
    input Port_of_Reg_enable_int_6,
    output DefaultInterface_RC_enable_int_6_out,
    input Port_of_Reg_enable_int_5,
    output DefaultInterface_RC_enable_int_5_out,
    input Port_of_Reg_enable_int_4,
    output DefaultInterface_RC_enable_int_4_out,
    input Port_of_Reg_enable_int_3,
    output DefaultInterface_RC_enable_int_3_out,
    input Port_of_Reg_enable_int_2,
    output DefaultInterface_RC_enable_int_2_out,
    input Port_of_Reg_enable_int_1,
    output DefaultInterface_RC_enable_int_1_out,
    input Port_of_Reg_enable_int_0,
    output DefaultInterface_RC_enable_int_0_out,
    input Address_EQ_Port_enable,
    input Port_of_Reg_unmask_int_31,
    output DefaultInterface_RC_unmask_int_31_out,
    input Port_of_Reg_unmask_int_30,
    output DefaultInterface_RC_unmask_int_30_out,
    input Port_of_Reg_unmask_int_29,
    output DefaultInterface_RC_unmask_int_29_out,
    input Port_of_Reg_unmask_int_28,
    output DefaultInterface_RC_unmask_int_28_out,
    input Port_of_Reg_unmask_int_27,
    output DefaultInterface_RC_unmask_int_27_out,
    input Port_of_Reg_unmask_int_26,
    output DefaultInterface_RC_unmask_int_26_out,
    input Port_of_Reg_unmask_int_25,
    output DefaultInterface_RC_unmask_int_25_out,
    input Port_of_Reg_unmask_int_24,
    output DefaultInterface_RC_unmask_int_24_out,
    input Port_of_Reg_unmask_int_23,
    output DefaultInterface_RC_unmask_int_23_out,
    input Port_of_Reg_unmask_int_22,
    output DefaultInterface_RC_unmask_int_22_out,
    input Port_of_Reg_unmask_int_21,
    output DefaultInterface_RC_unmask_int_21_out,
    input Port_of_Reg_unmask_int_20,
    output DefaultInterface_RC_unmask_int_20_out,
    input Port_of_Reg_unmask_int_19,
    output DefaultInterface_RC_unmask_int_19_out,
    input Port_of_Reg_unmask_int_18,
    output DefaultInterface_RC_unmask_int_18_out,
    input Port_of_Reg_unmask_int_17,
    output DefaultInterface_RC_unmask_int_17_out,
    input Port_of_Reg_unmask_int_16,
    output DefaultInterface_RC_unmask_int_16_out,
    input Port_of_Reg_unmask_int_15,
    output DefaultInterface_RC_unmask_int_15_out,
    input Port_of_Reg_unmask_int_14,
    output DefaultInterface_RC_unmask_int_14_out,
    input Port_of_Reg_unmask_int_13,
    output DefaultInterface_RC_unmask_int_13_out,
    input Port_of_Reg_unmask_int_12,
    output DefaultInterface_RC_unmask_int_12_out,
    input Port_of_Reg_unmask_int_11,
    output DefaultInterface_RC_unmask_int_11_out,
    input Port_of_Reg_unmask_int_10,
    output DefaultInterface_RC_unmask_int_10_out,
    input Port_of_Reg_unmask_int_9,
    output DefaultInterface_RC_unmask_int_9_out,
    input Port_of_Reg_unmask_int_8,
    output DefaultInterface_RC_unmask_int_8_out,
    input Port_of_Reg_unmask_int_7,
    output DefaultInterface_RC_unmask_int_7_out,
    input Port_of_Reg_unmask_int_6,
    output DefaultInterface_RC_unmask_int_6_out,
    input Port_of_Reg_unmask_int_5,
    output DefaultInterface_RC_unmask_int_5_out,
    input Port_of_Reg_unmask_int_4,
    output DefaultInterface_RC_unmask_int_4_out,
    input Port_of_Reg_unmask_int_3,
    output DefaultInterface_RC_unmask_int_3_out,
    input Port_of_Reg_unmask_int_2,
    output DefaultInterface_RC_unmask_int_2_out,
    input Port_of_Reg_unmask_int_1,
    output DefaultInterface_RC_unmask_int_1_out,
    input Port_of_Reg_unmask_int_0,
    output DefaultInterface_RC_unmask_int_0_out,
    input Address_EQ_Port_unmask,
    input Port_of_Reg_pending_int_31,
    output DefaultInterface_RC_pending_int_31_out,
    input Port_of_Reg_pending_int_30,
    output DefaultInterface_RC_pending_int_30_out,
    input Port_of_Reg_pending_int_29,
    output DefaultInterface_RC_pending_int_29_out,
    input Port_of_Reg_pending_int_28,
    output DefaultInterface_RC_pending_int_28_out,
    input Port_of_Reg_pending_int_27,
    output DefaultInterface_RC_pending_int_27_out,
    input Port_of_Reg_pending_int_26,
    output DefaultInterface_RC_pending_int_26_out,
    input Port_of_Reg_pending_int_25,
    output DefaultInterface_RC_pending_int_25_out,
    input Port_of_Reg_pending_int_24,
    output DefaultInterface_RC_pending_int_24_out,
    input Port_of_Reg_pending_int_23,
    output DefaultInterface_RC_pending_int_23_out,
    input Port_of_Reg_pending_int_22,
    output DefaultInterface_RC_pending_int_22_out,
    input Port_of_Reg_pending_int_21,
    output DefaultInterface_RC_pending_int_21_out,
    input Port_of_Reg_pending_int_20,
    output DefaultInterface_RC_pending_int_20_out,
    input Port_of_Reg_pending_int_19,
    output DefaultInterface_RC_pending_int_19_out,
    input Port_of_Reg_pending_int_18,
    output DefaultInterface_RC_pending_int_18_out,
    input Port_of_Reg_pending_int_17,
    output DefaultInterface_RC_pending_int_17_out,
    input Port_of_Reg_pending_int_16,
    output DefaultInterface_RC_pending_int_16_out,
    input Port_of_Reg_pending_int_15,
    output DefaultInterface_RC_pending_int_15_out,
    input Port_of_Reg_pending_int_14,
    output DefaultInterface_RC_pending_int_14_out,
    input Port_of_Reg_pending_int_13,
    output DefaultInterface_RC_pending_int_13_out,
    input Port_of_Reg_pending_int_12,
    output DefaultInterface_RC_pending_int_12_out,
    input Port_of_Reg_pending_int_11,
    output DefaultInterface_RC_pending_int_11_out,
    input Port_of_Reg_pending_int_10,
    output DefaultInterface_RC_pending_int_10_out,
    input Port_of_Reg_pending_int_9,
    output DefaultInterface_RC_pending_int_9_out,
    input Port_of_Reg_pending_int_8,
    output DefaultInterface_RC_pending_int_8_out,
    input Port_of_Reg_pending_int_7,
    output DefaultInterface_RC_pending_int_7_out,
    input Port_of_Reg_pending_int_6,
    output DefaultInterface_RC_pending_int_6_out,
    input Port_of_Reg_pending_int_5,
    output DefaultInterface_RC_pending_int_5_out,
    input Port_of_Reg_pending_int_4,
    output DefaultInterface_RC_pending_int_4_out,
    input Port_of_Reg_pending_int_3,
    output DefaultInterface_RC_pending_int_3_out,
    input Port_of_Reg_pending_int_2,
    output DefaultInterface_RC_pending_int_2_out,
    input Port_of_Reg_pending_int_1,
    output DefaultInterface_RC_pending_int_1_out,
    input Port_of_Reg_pending_int_0,
    output DefaultInterface_RC_pending_int_0_out,
    input Address_EQ_Port_pending,
    input Port_of_Reg_pending_NMI,
    output DefaultInterface_RC_pending_NMI_out,
    input Address_EQ_Port_pending_1,
    input Port_of_Reg_active_int_31,
    output DefaultInterface_RC_active_int_31_out,
    input Port_of_Reg_active_int_30,
    output DefaultInterface_RC_active_int_30_out,
    input Port_of_Reg_active_int_29,
    output DefaultInterface_RC_active_int_29_out,
    input Port_of_Reg_active_int_28,
    output DefaultInterface_RC_active_int_28_out,
    input Port_of_Reg_active_int_27,
    output DefaultInterface_RC_active_int_27_out,
    input Port_of_Reg_active_int_26,
    output DefaultInterface_RC_active_int_26_out,
    input Port_of_Reg_active_int_25,
    output DefaultInterface_RC_active_int_25_out,
    input Port_of_Reg_active_int_24,
    output DefaultInterface_RC_active_int_24_out,
    input Port_of_Reg_active_int_23,
    output DefaultInterface_RC_active_int_23_out,
    input Port_of_Reg_active_int_22,
    output DefaultInterface_RC_active_int_22_out,
    input Port_of_Reg_active_int_21,
    output DefaultInterface_RC_active_int_21_out,
    input Port_of_Reg_active_int_20,
    output DefaultInterface_RC_active_int_20_out,
    input Port_of_Reg_active_int_19,
    output DefaultInterface_RC_active_int_19_out,
    input Port_of_Reg_active_int_18,
    output DefaultInterface_RC_active_int_18_out,
    input Port_of_Reg_active_int_17,
    output DefaultInterface_RC_active_int_17_out,
    input Port_of_Reg_active_int_16,
    output DefaultInterface_RC_active_int_16_out,
    input Port_of_Reg_active_int_15,
    output DefaultInterface_RC_active_int_15_out,
    input Port_of_Reg_active_int_14,
    output DefaultInterface_RC_active_int_14_out,
    input Port_of_Reg_active_int_13,
    output DefaultInterface_RC_active_int_13_out,
    input Port_of_Reg_active_int_12,
    output DefaultInterface_RC_active_int_12_out,
    input Port_of_Reg_active_int_11,
    output DefaultInterface_RC_active_int_11_out,
    input Port_of_Reg_active_int_10,
    output DefaultInterface_RC_active_int_10_out,
    input Port_of_Reg_active_int_9,
    output DefaultInterface_RC_active_int_9_out,
    input Port_of_Reg_active_int_8,
    output DefaultInterface_RC_active_int_8_out,
    input Port_of_Reg_active_int_7,
    output DefaultInterface_RC_active_int_7_out,
    input Port_of_Reg_active_int_6,
    output DefaultInterface_RC_active_int_6_out,
    input Port_of_Reg_active_int_5,
    output DefaultInterface_RC_active_int_5_out,
    input Port_of_Reg_active_int_4,
    output DefaultInterface_RC_active_int_4_out,
    input Port_of_Reg_active_int_3,
    output DefaultInterface_RC_active_int_3_out,
    input Port_of_Reg_active_int_2,
    output DefaultInterface_RC_active_int_2_out,
    input Port_of_Reg_active_int_1,
    output DefaultInterface_RC_active_int_1_out,
    input Port_of_Reg_active_int_0,
    output DefaultInterface_RC_active_int_0_out,
    input Address_EQ_Port_active,
    input Port_of_Reg_active_NMI,
    output DefaultInterface_RC_active_NMI_out,
    input Address_EQ_Port_active_1,
    input [2:0] Port_of_Reg_priority_int_9,
    output [2:0] DefaultInterface_RC_priority_int_9_out,
    input [2:0] Port_of_Reg_priority_int_8,
    output [2:0] DefaultInterface_RC_priority_int_8_out,
    input [2:0] Port_of_Reg_priority_int_7,
    output [2:0] DefaultInterface_RC_priority_int_7_out,
    input [2:0] Port_of_Reg_priority_int_6,
    output [2:0] DefaultInterface_RC_priority_int_6_out,
    input [2:0] Port_of_Reg_priority_int_5,
    output [2:0] DefaultInterface_RC_priority_int_5_out,
    input [2:0] Port_of_Reg_priority_int_4,
    output [2:0] DefaultInterface_RC_priority_int_4_out,
    input [2:0] Port_of_Reg_priority_int_3,
    output [2:0] DefaultInterface_RC_priority_int_3_out,
    input [2:0] Port_of_Reg_priority_int_2,
    output [2:0] DefaultInterface_RC_priority_int_2_out,
    input [2:0] Port_of_Reg_priority_int_1,
    output [2:0] DefaultInterface_RC_priority_int_1_out,
    input [2:0] Port_of_Reg_priority_int_0,
    output [2:0] DefaultInterface_RC_priority_int_0_out,
    input Address_EQ_Port_priority,
    input [2:0] Port_of_Reg_priority_int_19,
    output [2:0] DefaultInterface_RC_priority_int_19_out,
    input [2:0] Port_of_Reg_priority_int_18,
    output [2:0] DefaultInterface_RC_priority_int_18_out,
    input [2:0] Port_of_Reg_priority_int_17,
    output [2:0] DefaultInterface_RC_priority_int_17_out,
    input [2:0] Port_of_Reg_priority_int_16,
    output [2:0] DefaultInterface_RC_priority_int_16_out,
    input [2:0] Port_of_Reg_priority_int_15,
    output [2:0] DefaultInterface_RC_priority_int_15_out,
    input [2:0] Port_of_Reg_priority_int_14,
    output [2:0] DefaultInterface_RC_priority_int_14_out,
    input [2:0] Port_of_Reg_priority_int_13,
    output [2:0] DefaultInterface_RC_priority_int_13_out,
    input [2:0] Port_of_Reg_priority_int_12,
    output [2:0] DefaultInterface_RC_priority_int_12_out,
    input [2:0] Port_of_Reg_priority_int_11,
    output [2:0] DefaultInterface_RC_priority_int_11_out,
    input [2:0] Port_of_Reg_priority_int_10,
    output [2:0] DefaultInterface_RC_priority_int_10_out,
    input Address_EQ_Port_priority_1,
    input [2:0] Port_of_Reg_priority_int_29,
    output [2:0] DefaultInterface_RC_priority_int_29_out,
    input [2:0] Port_of_Reg_priority_int_28,
    output [2:0] DefaultInterface_RC_priority_int_28_out,
    input [2:0] Port_of_Reg_priority_int_27,
    output [2:0] DefaultInterface_RC_priority_int_27_out,
    input [2:0] Port_of_Reg_priority_int_26,
    output [2:0] DefaultInterface_RC_priority_int_26_out,
    input [2:0] Port_of_Reg_priority_int_25,
    output [2:0] DefaultInterface_RC_priority_int_25_out,
    input [2:0] Port_of_Reg_priority_int_24,
    output [2:0] DefaultInterface_RC_priority_int_24_out,
    input [2:0] Port_of_Reg_priority_int_23,
    output [2:0] DefaultInterface_RC_priority_int_23_out,
    input [2:0] Port_of_Reg_priority_int_22,
    output [2:0] DefaultInterface_RC_priority_int_22_out,
    input [2:0] Port_of_Reg_priority_int_21,
    output [2:0] DefaultInterface_RC_priority_int_21_out,
    input [2:0] Port_of_Reg_priority_int_20,
    output [2:0] DefaultInterface_RC_priority_int_20_out,
    input Address_EQ_Port_priority_2,
    input [2:0] Port_of_Reg_priority_int_31,
    output [2:0] DefaultInterface_RC_priority_int_31_out,
    input [2:0] Port_of_Reg_priority_int_30,
    output [2:0] DefaultInterface_RC_priority_int_30_out,
    input Address_EQ_Port_priority_3,
    input Port_of_Reg_requested_int_31,
    output DefaultInterface_RC_requested_int_31_out,
    input Port_of_Reg_requested_int_30,
    output DefaultInterface_RC_requested_int_30_out,
    input Port_of_Reg_requested_int_29,
    output DefaultInterface_RC_requested_int_29_out,
    input Port_of_Reg_requested_int_28,
    output DefaultInterface_RC_requested_int_28_out,
    input Port_of_Reg_requested_int_27,
    output DefaultInterface_RC_requested_int_27_out,
    input Port_of_Reg_requested_int_26,
    output DefaultInterface_RC_requested_int_26_out,
    input Port_of_Reg_requested_int_25,
    output DefaultInterface_RC_requested_int_25_out,
    input Port_of_Reg_requested_int_24,
    output DefaultInterface_RC_requested_int_24_out,
    input Port_of_Reg_requested_int_23,
    output DefaultInterface_RC_requested_int_23_out,
    input Port_of_Reg_requested_int_22,
    output DefaultInterface_RC_requested_int_22_out,
    input Port_of_Reg_requested_int_21,
    output DefaultInterface_RC_requested_int_21_out,
    input Port_of_Reg_requested_int_20,
    output DefaultInterface_RC_requested_int_20_out,
    input Port_of_Reg_requested_int_19,
    output DefaultInterface_RC_requested_int_19_out,
    input Port_of_Reg_requested_int_18,
    output DefaultInterface_RC_requested_int_18_out,
    input Port_of_Reg_requested_int_17,
    output DefaultInterface_RC_requested_int_17_out,
    input Port_of_Reg_requested_int_16,
    output DefaultInterface_RC_requested_int_16_out,
    input Port_of_Reg_requested_int_15,
    output DefaultInterface_RC_requested_int_15_out,
    input Port_of_Reg_requested_int_14,
    output DefaultInterface_RC_requested_int_14_out,
    input Port_of_Reg_requested_int_13,
    output DefaultInterface_RC_requested_int_13_out,
    input Port_of_Reg_requested_int_12,
    output DefaultInterface_RC_requested_int_12_out,
    input Port_of_Reg_requested_int_11,
    output DefaultInterface_RC_requested_int_11_out,
    input Port_of_Reg_requested_int_10,
    output DefaultInterface_RC_requested_int_10_out,
    input Port_of_Reg_requested_int_9,
    output DefaultInterface_RC_requested_int_9_out,
    input Port_of_Reg_requested_int_8,
    output DefaultInterface_RC_requested_int_8_out,
    input Port_of_Reg_requested_int_7,
    output DefaultInterface_RC_requested_int_7_out,
    input Port_of_Reg_requested_int_6,
    output DefaultInterface_RC_requested_int_6_out,
    input Port_of_Reg_requested_int_5,
    output DefaultInterface_RC_requested_int_5_out,
    input Port_of_Reg_requested_int_4,
    output DefaultInterface_RC_requested_int_4_out,
    input Port_of_Reg_requested_int_3,
    output DefaultInterface_RC_requested_int_3_out,
    input Port_of_Reg_requested_int_2,
    output DefaultInterface_RC_requested_int_2_out,
    input Port_of_Reg_requested_int_1,
    output DefaultInterface_RC_requested_int_1_out,
    input Port_of_Reg_requested_int_0,
    output DefaultInterface_RC_requested_int_0_out,
    input Address_EQ_Port_requested,
    input Port_of_Reg_requested_NMI,
    output DefaultInterface_RC_requested_NMI_out,
    input Address_EQ_Port_requested_1,
    input Port_of_Reg_paused_int_31,
    output DefaultInterface_RC_paused_int_31_out,
    input Port_of_Reg_paused_int_30,
    output DefaultInterface_RC_paused_int_30_out,
    input Port_of_Reg_paused_int_29,
    output DefaultInterface_RC_paused_int_29_out,
    input Port_of_Reg_paused_int_28,
    output DefaultInterface_RC_paused_int_28_out,
    input Port_of_Reg_paused_int_27,
    output DefaultInterface_RC_paused_int_27_out,
    input Port_of_Reg_paused_int_26,
    output DefaultInterface_RC_paused_int_26_out,
    input Port_of_Reg_paused_int_25,
    output DefaultInterface_RC_paused_int_25_out,
    input Port_of_Reg_paused_int_24,
    output DefaultInterface_RC_paused_int_24_out,
    input Port_of_Reg_paused_int_23,
    output DefaultInterface_RC_paused_int_23_out,
    input Port_of_Reg_paused_int_22,
    output DefaultInterface_RC_paused_int_22_out,
    input Port_of_Reg_paused_int_21,
    output DefaultInterface_RC_paused_int_21_out,
    input Port_of_Reg_paused_int_20,
    output DefaultInterface_RC_paused_int_20_out,
    input Port_of_Reg_paused_int_19,
    output DefaultInterface_RC_paused_int_19_out,
    input Port_of_Reg_paused_int_18,
    output DefaultInterface_RC_paused_int_18_out,
    input Port_of_Reg_paused_int_17,
    output DefaultInterface_RC_paused_int_17_out,
    input Port_of_Reg_paused_int_16,
    output DefaultInterface_RC_paused_int_16_out,
    input Port_of_Reg_paused_int_15,
    output DefaultInterface_RC_paused_int_15_out,
    input Port_of_Reg_paused_int_14,
    output DefaultInterface_RC_paused_int_14_out,
    input Port_of_Reg_paused_int_13,
    output DefaultInterface_RC_paused_int_13_out,
    input Port_of_Reg_paused_int_12,
    output DefaultInterface_RC_paused_int_12_out,
    input Port_of_Reg_paused_int_11,
    output DefaultInterface_RC_paused_int_11_out,
    input Port_of_Reg_paused_int_10,
    output DefaultInterface_RC_paused_int_10_out,
    input Port_of_Reg_paused_int_9,
    output DefaultInterface_RC_paused_int_9_out,
    input Port_of_Reg_paused_int_8,
    output DefaultInterface_RC_paused_int_8_out,
    input Port_of_Reg_paused_int_7,
    output DefaultInterface_RC_paused_int_7_out,
    input Port_of_Reg_paused_int_6,
    output DefaultInterface_RC_paused_int_6_out,
    input Port_of_Reg_paused_int_5,
    output DefaultInterface_RC_paused_int_5_out,
    input Port_of_Reg_paused_int_4,
    output DefaultInterface_RC_paused_int_4_out,
    input Port_of_Reg_paused_int_3,
    output DefaultInterface_RC_paused_int_3_out,
    input Port_of_Reg_paused_int_2,
    output DefaultInterface_RC_paused_int_2_out,
    input Port_of_Reg_paused_int_1,
    output DefaultInterface_RC_paused_int_1_out,
    input Port_of_Reg_paused_int_0,
    output DefaultInterface_RC_paused_int_0_out,
    input Address_EQ_Port_paused,
    input Port_of_Reg_paused_NMI,
    output DefaultInterface_RC_paused_NMI_out,
    input Address_EQ_Port_paused_1,
    input [1:0] Port_of_Reg_group_priority_Group4,
    output [1:0] DefaultInterface_RC_group_priority_Group4_out,
    input [1:0] Port_of_Reg_group_priority_Group3,
    output [1:0] DefaultInterface_RC_group_priority_Group3_out,
    input [1:0] Port_of_Reg_group_priority_Group2,
    output [1:0] DefaultInterface_RC_group_priority_Group2_out,
    input [1:0] Port_of_Reg_group_priority_Group1,
    output [1:0] DefaultInterface_RC_group_priority_Group1_out,
    input Address_EQ_Port_group_priority,
    input [31:0] Port_of_Reg_addr_int_0,
    output [31:0] DefaultInterface_RC_addr_int_0_out,
    input Address_EQ_Port_int_0_addr,
    input [31:0] Port_of_Reg_addr_int_1,
    output [31:0] DefaultInterface_RC_addr_int_1_out,
    input Address_EQ_Port_int_1_addr,
    input [31:0] Port_of_Reg_addr_int_2,
    output [31:0] DefaultInterface_RC_addr_int_2_out,
    input Address_EQ_Port_int_2_addr,
    input [31:0] Port_of_Reg_addr_int_3,
    output [31:0] DefaultInterface_RC_addr_int_3_out,
    input Address_EQ_Port_int_3_addr,
    input [31:0] Port_of_Reg_addr_int_4,
    output [31:0] DefaultInterface_RC_addr_int_4_out,
    input Address_EQ_Port_int_4_addr,
    input [31:0] Port_of_Reg_addr_int_5,
    output [31:0] DefaultInterface_RC_addr_int_5_out,
    input Address_EQ_Port_int_5_addr,
    input [31:0] Port_of_Reg_addr_int_6,
    output [31:0] DefaultInterface_RC_addr_int_6_out,
    input Address_EQ_Port_int_6_addr,
    input [31:0] Port_of_Reg_addr_int_7,
    output [31:0] DefaultInterface_RC_addr_int_7_out,
    input Address_EQ_Port_int_7_addr,
    input [31:0] Port_of_Reg_addr_int_8,
    output [31:0] DefaultInterface_RC_addr_int_8_out,
    input Address_EQ_Port_int_8_addr,
    input [31:0] Port_of_Reg_addr_int_9,
    output [31:0] DefaultInterface_RC_addr_int_9_out,
    input Address_EQ_Port_int_9_addr,
    input [31:0] Port_of_Reg_addr_int_10,
    output [31:0] DefaultInterface_RC_addr_int_10_out,
    input Address_EQ_Port_int_10_addr,
    input [31:0] Port_of_Reg_addr_int_11,
    output [31:0] DefaultInterface_RC_addr_int_11_out,
    input Address_EQ_Port_int_11_addr,
    input [31:0] Port_of_Reg_addr_int_12,
    output [31:0] DefaultInterface_RC_addr_int_12_out,
    input Address_EQ_Port_int_12_addr,
    input [31:0] Port_of_Reg_addr_int_13,
    output [31:0] DefaultInterface_RC_addr_int_13_out,
    input Address_EQ_Port_int_13_addr,
    input [31:0] Port_of_Reg_addr_int_14,
    output [31:0] DefaultInterface_RC_addr_int_14_out,
    input Address_EQ_Port_int_14_addr,
    input [31:0] Port_of_Reg_addr_int_15,
    output [31:0] DefaultInterface_RC_addr_int_15_out,
    input Address_EQ_Port_int_15_addr,
    input [31:0] Port_of_Reg_addr_int_16,
    output [31:0] DefaultInterface_RC_addr_int_16_out,
    input Address_EQ_Port_int_16_addr,
    input [31:0] Port_of_Reg_addr_int_17,
    output [31:0] DefaultInterface_RC_addr_int_17_out,
    input Address_EQ_Port_int_17_addr,
    input [31:0] Port_of_Reg_addr_int_18,
    output [31:0] DefaultInterface_RC_addr_int_18_out,
    input Address_EQ_Port_int_18_addr,
    input [31:0] Port_of_Reg_addr_int_19,
    output [31:0] DefaultInterface_RC_addr_int_19_out,
    input Address_EQ_Port_int_19_addr,
    input [31:0] Port_of_Reg_addr_int_20,
    output [31:0] DefaultInterface_RC_addr_int_20_out,
    input Address_EQ_Port_int_20_addr,
    input [31:0] Port_of_Reg_addr_int_21,
    output [31:0] DefaultInterface_RC_addr_int_21_out,
    input Address_EQ_Port_int_21_addr,
    input [31:0] Port_of_Reg_addr_int_22,
    output [31:0] DefaultInterface_RC_addr_int_22_out,
    input Address_EQ_Port_int_22_addr,
    input [31:0] Port_of_Reg_addr_int_23,
    output [31:0] DefaultInterface_RC_addr_int_23_out,
    input Address_EQ_Port_int_23_addr,
    input [31:0] Port_of_Reg_addr_int_24,
    output [31:0] DefaultInterface_RC_addr_int_24_out,
    input Address_EQ_Port_int_24_addr,
    input [31:0] Port_of_Reg_addr_int_25,
    output [31:0] DefaultInterface_RC_addr_int_25_out,
    input Address_EQ_Port_int_25_addr,
    input [31:0] Port_of_Reg_addr_int_26,
    output [31:0] DefaultInterface_RC_addr_int_26_out,
    input Address_EQ_Port_int_26_addr,
    input [31:0] Port_of_Reg_addr_int_27,
    output [31:0] DefaultInterface_RC_addr_int_27_out,
    input Address_EQ_Port_int_27_addr,
    input [31:0] Port_of_Reg_addr_int_28,
    output [31:0] DefaultInterface_RC_addr_int_28_out,
    input Address_EQ_Port_int_28_addr,
    input [31:0] Port_of_Reg_addr_int_29,
    output [31:0] DefaultInterface_RC_addr_int_29_out,
    input Address_EQ_Port_int_29_addr,
    input [31:0] Port_of_Reg_addr_int_30,
    output [31:0] DefaultInterface_RC_addr_int_30_out,
    input Address_EQ_Port_int_30_addr,
    input [31:0] Port_of_Reg_addr_int_31,
    output [31:0] DefaultInterface_RC_addr_int_31_out,
    input Address_EQ_Port_int_31_addr,
    input [31:0] Port_of_Reg_addr_NMI,
    output [31:0] DefaultInterface_RC_addr_NMI_out,
    input Address_EQ_Port_NMI_addr
);

logic   [31:0] NMI_addr_Outp_s;
logic   [31:0] int_31_addr_Outp_s;
logic   [31:0] int_30_addr_Outp_s;
logic   [31:0] int_29_addr_Outp_s;
logic   [31:0] int_28_addr_Outp_s;
logic   [31:0] int_27_addr_Outp_s;
logic   [31:0] int_26_addr_Outp_s;
logic   [31:0] int_25_addr_Outp_s;
logic   [31:0] int_24_addr_Outp_s;
logic   [31:0] int_23_addr_Outp_s;
logic   [31:0] int_22_addr_Outp_s;
logic   [31:0] int_21_addr_Outp_s;
logic   [31:0] int_20_addr_Outp_s;
logic   [31:0] int_19_addr_Outp_s;
logic   [31:0] int_18_addr_Outp_s;
logic   [31:0] int_17_addr_Outp_s;
logic   [31:0] int_16_addr_Outp_s;
logic   [31:0] int_15_addr_Outp_s;
logic   [31:0] int_14_addr_Outp_s;
logic   [31:0] int_13_addr_Outp_s;
logic   [31:0] int_12_addr_Outp_s;
logic   [31:0] int_11_addr_Outp_s;
logic   [31:0] int_10_addr_Outp_s;
logic   [31:0] int_9_addr_Outp_s;
logic   [31:0] int_8_addr_Outp_s;
logic   [31:0] int_7_addr_Outp_s;
logic   [31:0] int_6_addr_Outp_s;
logic   [31:0] int_5_addr_Outp_s;
logic   [31:0] int_4_addr_Outp_s;
logic   [31:0] int_3_addr_Outp_s;
logic   [31:0] int_2_addr_Outp_s;
logic   [31:0] int_1_addr_Outp_s;
logic   [31:0] int_0_addr_Outp_s;
logic   [31:0] group_priority_Outp_s;
logic   [31:0] paused_1_Outp_s;
logic   [31:0] paused_Outp_s;
logic   [31:0] requested_1_Outp_s;
logic   [31:0] requested_Outp_s;
logic   [31:0] priority_3_Outp_s;
logic   [31:0] priority_2_Outp_s;
logic   [31:0] priority_1_Outp_s;
logic   [31:0] priority_Outp_s;
logic   [31:0] active_1_Outp_s;
logic   [31:0] active_Outp_s;
logic   [31:0] pending_1_Outp_s;
logic   [31:0] pending_Outp_s;
logic   [31:0] unmask_Outp_s;
logic   [31:0] enable_Outp_s;
logic   [31:0] BOR_Outp_s;
logic  signed  [31:0] DefaultInterface_Shifting_Outp_s;

logic   [31:0] Mux47_Outp_s;
logic   [31:0] Mux46_Outp_s;
logic   [31:0] Mux45_Outp_s;
logic   [31:0] Mux44_Outp_s;
logic   [31:0] Mux43_Outp_s;
logic   [31:0] Mux42_Outp_s;
logic   [31:0] Mux41_Outp_s;
logic   [31:0] Mux40_Outp_s;
logic   [31:0] Mux39_Outp_s;
logic   [31:0] Mux38_Outp_s;
logic   [31:0] Mux37_Outp_s;
logic   [31:0] Mux36_Outp_s;
logic   [31:0] Mux35_Outp_s;
logic   [31:0] Mux34_Outp_s;
logic   [31:0] Mux33_Outp_s;
logic   [31:0] Mux32_Outp_s;
logic   [31:0] Mux31_Outp_s;
logic   [31:0] Mux30_Outp_s;
logic   [31:0] Mux29_Outp_s;
logic   [31:0] Mux28_Outp_s;
logic   [31:0] Mux27_Outp_s;
logic   [31:0] Mux26_Outp_s;
logic   [31:0] Mux25_Outp_s;
logic   [31:0] Mux24_Outp_s;
logic   [31:0] Mux23_Outp_s;
logic   [31:0] Mux22_Outp_s;
logic   [31:0] Mux21_Outp_s;
logic   [31:0] Mux20_Outp_s;
logic   [31:0] Mux19_Outp_s;
logic   [31:0] Mux18_Outp_s;
logic   [31:0] Mux17_Outp_s;
logic   [31:0] Mux16_Outp_s;
logic   [31:0] Mux15_Outp_s;
logic   [31:0] Mux14_Outp_s;
logic   [31:0] Mux13_Outp_s;
logic   [31:0] Mux12_Outp_s;
logic   [31:0] Mux11_Outp_s;
logic   [31:0] Mux10_Outp_s;
logic   [31:0] Mux09_Outp_s;
logic   [31:0] Mux08_Outp_s;
logic   [31:0] Mux07_Outp_s;
logic   [31:0] Mux06_Outp_s;
logic   [31:0] Mux05_Outp_s;
logic   [31:0] Mux04_Outp_s;
logic   [31:0] Mux03_Outp_s;
logic   [31:0] Mux02_Outp_s;
logic   [31:0] Mux01_Outp_s;
logic   [31:0] Mux00_Outp_s;
logic   [31:0] DefaultInterface_Reading_MUX_Outp_s;

assign NMI_addr_Outp_s = {Port_of_Reg_addr_NMI};

assign int_31_addr_Outp_s = {Port_of_Reg_addr_int_31};

assign int_30_addr_Outp_s = {Port_of_Reg_addr_int_30};

assign int_29_addr_Outp_s = {Port_of_Reg_addr_int_29};

assign int_28_addr_Outp_s = {Port_of_Reg_addr_int_28};

assign int_27_addr_Outp_s = {Port_of_Reg_addr_int_27};

assign int_26_addr_Outp_s = {Port_of_Reg_addr_int_26};

assign int_25_addr_Outp_s = {Port_of_Reg_addr_int_25};

assign int_24_addr_Outp_s = {Port_of_Reg_addr_int_24};

assign int_23_addr_Outp_s = {Port_of_Reg_addr_int_23};

assign int_22_addr_Outp_s = {Port_of_Reg_addr_int_22};

assign int_21_addr_Outp_s = {Port_of_Reg_addr_int_21};

assign int_20_addr_Outp_s = {Port_of_Reg_addr_int_20};

assign int_19_addr_Outp_s = {Port_of_Reg_addr_int_19};

assign int_18_addr_Outp_s = {Port_of_Reg_addr_int_18};

assign int_17_addr_Outp_s = {Port_of_Reg_addr_int_17};

assign int_16_addr_Outp_s = {Port_of_Reg_addr_int_16};

assign int_15_addr_Outp_s = {Port_of_Reg_addr_int_15};

assign int_14_addr_Outp_s = {Port_of_Reg_addr_int_14};

assign int_13_addr_Outp_s = {Port_of_Reg_addr_int_13};

assign int_12_addr_Outp_s = {Port_of_Reg_addr_int_12};

assign int_11_addr_Outp_s = {Port_of_Reg_addr_int_11};

assign int_10_addr_Outp_s = {Port_of_Reg_addr_int_10};

assign int_9_addr_Outp_s = {Port_of_Reg_addr_int_9};

assign int_8_addr_Outp_s = {Port_of_Reg_addr_int_8};

assign int_7_addr_Outp_s = {Port_of_Reg_addr_int_7};

assign int_6_addr_Outp_s = {Port_of_Reg_addr_int_6};

assign int_5_addr_Outp_s = {Port_of_Reg_addr_int_5};

assign int_4_addr_Outp_s = {Port_of_Reg_addr_int_4};

assign int_3_addr_Outp_s = {Port_of_Reg_addr_int_3};

assign int_2_addr_Outp_s = {Port_of_Reg_addr_int_2};

assign int_1_addr_Outp_s = {Port_of_Reg_addr_int_1};

assign int_0_addr_Outp_s = {Port_of_Reg_addr_int_0};

assign group_priority_Outp_s = {24'b0,Port_of_Reg_group_priority_Group4,Port_of_Reg_group_priority_Group3,Port_of_Reg_group_priority_Group2,Port_of_Reg_group_priority_Group1};

assign paused_1_Outp_s = {31'b0,Port_of_Reg_paused_NMI};

assign paused_Outp_s = {Port_of_Reg_paused_int_31,Port_of_Reg_paused_int_30,Port_of_Reg_paused_int_29,Port_of_Reg_paused_int_28,Port_of_Reg_paused_int_27,Port_of_Reg_paused_int_26,Port_of_Reg_paused_int_25,Port_of_Reg_paused_int_24,Port_of_Reg_paused_int_23,Port_of_Reg_paused_int_22,Port_of_Reg_paused_int_21,Port_of_Reg_paused_int_20,Port_of_Reg_paused_int_19,Port_of_Reg_paused_int_18,Port_of_Reg_paused_int_17,Port_of_Reg_paused_int_16,Port_of_Reg_paused_int_15,Port_of_Reg_paused_int_14,Port_of_Reg_paused_int_13,Port_of_Reg_paused_int_12,Port_of_Reg_paused_int_11,Port_of_Reg_paused_int_10,Port_of_Reg_paused_int_9,Port_of_Reg_paused_int_8,Port_of_Reg_paused_int_7,Port_of_Reg_paused_int_6,Port_of_Reg_paused_int_5,Port_of_Reg_paused_int_4,Port_of_Reg_paused_int_3,Port_of_Reg_paused_int_2,Port_of_Reg_paused_int_1,Port_of_Reg_paused_int_0};

assign requested_1_Outp_s = {31'b0,Port_of_Reg_requested_NMI};

assign requested_Outp_s = {Port_of_Reg_requested_int_31,Port_of_Reg_requested_int_30,Port_of_Reg_requested_int_29,Port_of_Reg_requested_int_28,Port_of_Reg_requested_int_27,Port_of_Reg_requested_int_26,Port_of_Reg_requested_int_25,Port_of_Reg_requested_int_24,Port_of_Reg_requested_int_23,Port_of_Reg_requested_int_22,Port_of_Reg_requested_int_21,Port_of_Reg_requested_int_20,Port_of_Reg_requested_int_19,Port_of_Reg_requested_int_18,Port_of_Reg_requested_int_17,Port_of_Reg_requested_int_16,Port_of_Reg_requested_int_15,Port_of_Reg_requested_int_14,Port_of_Reg_requested_int_13,Port_of_Reg_requested_int_12,Port_of_Reg_requested_int_11,Port_of_Reg_requested_int_10,Port_of_Reg_requested_int_9,Port_of_Reg_requested_int_8,Port_of_Reg_requested_int_7,Port_of_Reg_requested_int_6,Port_of_Reg_requested_int_5,Port_of_Reg_requested_int_4,Port_of_Reg_requested_int_3,Port_of_Reg_requested_int_2,Port_of_Reg_requested_int_1,Port_of_Reg_requested_int_0};

assign priority_3_Outp_s = {26'b0,Port_of_Reg_priority_int_31,Port_of_Reg_priority_int_30};

assign priority_2_Outp_s = {2'b0,Port_of_Reg_priority_int_29,Port_of_Reg_priority_int_28,Port_of_Reg_priority_int_27,Port_of_Reg_priority_int_26,Port_of_Reg_priority_int_25,Port_of_Reg_priority_int_24,Port_of_Reg_priority_int_23,Port_of_Reg_priority_int_22,Port_of_Reg_priority_int_21,Port_of_Reg_priority_int_20};

assign priority_1_Outp_s = {2'b0,Port_of_Reg_priority_int_19,Port_of_Reg_priority_int_18,Port_of_Reg_priority_int_17,Port_of_Reg_priority_int_16,Port_of_Reg_priority_int_15,Port_of_Reg_priority_int_14,Port_of_Reg_priority_int_13,Port_of_Reg_priority_int_12,Port_of_Reg_priority_int_11,Port_of_Reg_priority_int_10};

assign priority_Outp_s = {2'b0,Port_of_Reg_priority_int_9,Port_of_Reg_priority_int_8,Port_of_Reg_priority_int_7,Port_of_Reg_priority_int_6,Port_of_Reg_priority_int_5,Port_of_Reg_priority_int_4,Port_of_Reg_priority_int_3,Port_of_Reg_priority_int_2,Port_of_Reg_priority_int_1,Port_of_Reg_priority_int_0};

assign active_1_Outp_s = {31'b0,Port_of_Reg_active_NMI};

assign active_Outp_s = {Port_of_Reg_active_int_31,Port_of_Reg_active_int_30,Port_of_Reg_active_int_29,Port_of_Reg_active_int_28,Port_of_Reg_active_int_27,Port_of_Reg_active_int_26,Port_of_Reg_active_int_25,Port_of_Reg_active_int_24,Port_of_Reg_active_int_23,Port_of_Reg_active_int_22,Port_of_Reg_active_int_21,Port_of_Reg_active_int_20,Port_of_Reg_active_int_19,Port_of_Reg_active_int_18,Port_of_Reg_active_int_17,Port_of_Reg_active_int_16,Port_of_Reg_active_int_15,Port_of_Reg_active_int_14,Port_of_Reg_active_int_13,Port_of_Reg_active_int_12,Port_of_Reg_active_int_11,Port_of_Reg_active_int_10,Port_of_Reg_active_int_9,Port_of_Reg_active_int_8,Port_of_Reg_active_int_7,Port_of_Reg_active_int_6,Port_of_Reg_active_int_5,Port_of_Reg_active_int_4,Port_of_Reg_active_int_3,Port_of_Reg_active_int_2,Port_of_Reg_active_int_1,Port_of_Reg_active_int_0};

assign pending_1_Outp_s = {31'b0,Port_of_Reg_pending_NMI};

assign pending_Outp_s = {Port_of_Reg_pending_int_31,Port_of_Reg_pending_int_30,Port_of_Reg_pending_int_29,Port_of_Reg_pending_int_28,Port_of_Reg_pending_int_27,Port_of_Reg_pending_int_26,Port_of_Reg_pending_int_25,Port_of_Reg_pending_int_24,Port_of_Reg_pending_int_23,Port_of_Reg_pending_int_22,Port_of_Reg_pending_int_21,Port_of_Reg_pending_int_20,Port_of_Reg_pending_int_19,Port_of_Reg_pending_int_18,Port_of_Reg_pending_int_17,Port_of_Reg_pending_int_16,Port_of_Reg_pending_int_15,Port_of_Reg_pending_int_14,Port_of_Reg_pending_int_13,Port_of_Reg_pending_int_12,Port_of_Reg_pending_int_11,Port_of_Reg_pending_int_10,Port_of_Reg_pending_int_9,Port_of_Reg_pending_int_8,Port_of_Reg_pending_int_7,Port_of_Reg_pending_int_6,Port_of_Reg_pending_int_5,Port_of_Reg_pending_int_4,Port_of_Reg_pending_int_3,Port_of_Reg_pending_int_2,Port_of_Reg_pending_int_1,Port_of_Reg_pending_int_0};

assign unmask_Outp_s = {Port_of_Reg_unmask_int_31,Port_of_Reg_unmask_int_30,Port_of_Reg_unmask_int_29,Port_of_Reg_unmask_int_28,Port_of_Reg_unmask_int_27,Port_of_Reg_unmask_int_26,Port_of_Reg_unmask_int_25,Port_of_Reg_unmask_int_24,Port_of_Reg_unmask_int_23,Port_of_Reg_unmask_int_22,Port_of_Reg_unmask_int_21,Port_of_Reg_unmask_int_20,Port_of_Reg_unmask_int_19,Port_of_Reg_unmask_int_18,Port_of_Reg_unmask_int_17,Port_of_Reg_unmask_int_16,Port_of_Reg_unmask_int_15,Port_of_Reg_unmask_int_14,Port_of_Reg_unmask_int_13,Port_of_Reg_unmask_int_12,Port_of_Reg_unmask_int_11,Port_of_Reg_unmask_int_10,Port_of_Reg_unmask_int_9,Port_of_Reg_unmask_int_8,Port_of_Reg_unmask_int_7,Port_of_Reg_unmask_int_6,Port_of_Reg_unmask_int_5,Port_of_Reg_unmask_int_4,Port_of_Reg_unmask_int_3,Port_of_Reg_unmask_int_2,Port_of_Reg_unmask_int_1,Port_of_Reg_unmask_int_0};

assign enable_Outp_s = {Port_of_Reg_enable_int_31,Port_of_Reg_enable_int_30,Port_of_Reg_enable_int_29,Port_of_Reg_enable_int_28,Port_of_Reg_enable_int_27,Port_of_Reg_enable_int_26,Port_of_Reg_enable_int_25,Port_of_Reg_enable_int_24,Port_of_Reg_enable_int_23,Port_of_Reg_enable_int_22,Port_of_Reg_enable_int_21,Port_of_Reg_enable_int_20,Port_of_Reg_enable_int_19,Port_of_Reg_enable_int_18,Port_of_Reg_enable_int_17,Port_of_Reg_enable_int_16,Port_of_Reg_enable_int_15,Port_of_Reg_enable_int_14,Port_of_Reg_enable_int_13,Port_of_Reg_enable_int_12,Port_of_Reg_enable_int_11,Port_of_Reg_enable_int_10,Port_of_Reg_enable_int_9,Port_of_Reg_enable_int_8,Port_of_Reg_enable_int_7,Port_of_Reg_enable_int_6,Port_of_Reg_enable_int_5,Port_of_Reg_enable_int_4,Port_of_Reg_enable_int_3,Port_of_Reg_enable_int_2,Port_of_Reg_enable_int_1,Port_of_Reg_enable_int_0};

always_comb
begin
    case (Address_EQ_Port_NMI_addr)
        1'b1 : Mux47_Outp_s = NMI_addr_Outp_s;
        default : Mux47_Outp_s = 32'b0;
    endcase
end

always_comb
begin
    case (Address_EQ_Port_int_31_addr)
        1'b1 : Mux46_Outp_s = int_31_addr_Outp_s;
        default : Mux46_Outp_s = 32'b0;
    endcase
end

always_comb
begin
    case (Address_EQ_Port_int_30_addr)
        1'b1 : Mux45_Outp_s = int_30_addr_Outp_s;
        default : Mux45_Outp_s = 32'b0;
    endcase
end

always_comb
begin
    case (Address_EQ_Port_int_29_addr)
        1'b1 : Mux44_Outp_s = int_29_addr_Outp_s;
        default : Mux44_Outp_s = 32'b0;
    endcase
end

always_comb
begin
    case (Address_EQ_Port_int_28_addr)
        1'b1 : Mux43_Outp_s = int_28_addr_Outp_s;
        default : Mux43_Outp_s = 32'b0;
    endcase
end

always_comb
begin
    case (Address_EQ_Port_int_27_addr)
        1'b1 : Mux42_Outp_s = int_27_addr_Outp_s;
        default : Mux42_Outp_s = 32'b0;
    endcase
end

always_comb
begin
    case (Address_EQ_Port_int_26_addr)
        1'b1 : Mux41_Outp_s = int_26_addr_Outp_s;
        default : Mux41_Outp_s = 32'b0;
    endcase
end

always_comb
begin
    case (Address_EQ_Port_int_25_addr)
        1'b1 : Mux40_Outp_s = int_25_addr_Outp_s;
        default : Mux40_Outp_s = 32'b0;
    endcase
end

always_comb
begin
    case (Address_EQ_Port_int_24_addr)
        1'b1 : Mux39_Outp_s = int_24_addr_Outp_s;
        default : Mux39_Outp_s = 32'b0;
    endcase
end

always_comb
begin
    case (Address_EQ_Port_int_23_addr)
        1'b1 : Mux38_Outp_s = int_23_addr_Outp_s;
        default : Mux38_Outp_s = 32'b0;
    endcase
end

always_comb
begin
    case (Address_EQ_Port_int_22_addr)
        1'b1 : Mux37_Outp_s = int_22_addr_Outp_s;
        default : Mux37_Outp_s = 32'b0;
    endcase
end

always_comb
begin
    case (Address_EQ_Port_int_21_addr)
        1'b1 : Mux36_Outp_s = int_21_addr_Outp_s;
        default : Mux36_Outp_s = 32'b0;
    endcase
end

always_comb
begin
    case (Address_EQ_Port_int_20_addr)
        1'b1 : Mux35_Outp_s = int_20_addr_Outp_s;
        default : Mux35_Outp_s = 32'b0;
    endcase
end

always_comb
begin
    case (Address_EQ_Port_int_19_addr)
        1'b1 : Mux34_Outp_s = int_19_addr_Outp_s;
        default : Mux34_Outp_s = 32'b0;
    endcase
end

always_comb
begin
    case (Address_EQ_Port_int_18_addr)
        1'b1 : Mux33_Outp_s = int_18_addr_Outp_s;
        default : Mux33_Outp_s = 32'b0;
    endcase
end

always_comb
begin
    case (Address_EQ_Port_int_17_addr)
        1'b1 : Mux32_Outp_s = int_17_addr_Outp_s;
        default : Mux32_Outp_s = 32'b0;
    endcase
end

always_comb
begin
    case (Address_EQ_Port_int_16_addr)
        1'b1 : Mux31_Outp_s = int_16_addr_Outp_s;
        default : Mux31_Outp_s = 32'b0;
    endcase
end

always_comb
begin
    case (Address_EQ_Port_int_15_addr)
        1'b1 : Mux30_Outp_s = int_15_addr_Outp_s;
        default : Mux30_Outp_s = 32'b0;
    endcase
end

always_comb
begin
    case (Address_EQ_Port_int_14_addr)
        1'b1 : Mux29_Outp_s = int_14_addr_Outp_s;
        default : Mux29_Outp_s = 32'b0;
    endcase
end

always_comb
begin
    case (Address_EQ_Port_int_13_addr)
        1'b1 : Mux28_Outp_s = int_13_addr_Outp_s;
        default : Mux28_Outp_s = 32'b0;
    endcase
end

always_comb
begin
    case (Address_EQ_Port_int_12_addr)
        1'b1 : Mux27_Outp_s = int_12_addr_Outp_s;
        default : Mux27_Outp_s = 32'b0;
    endcase
end

always_comb
begin
    case (Address_EQ_Port_int_11_addr)
        1'b1 : Mux26_Outp_s = int_11_addr_Outp_s;
        default : Mux26_Outp_s = 32'b0;
    endcase
end

always_comb
begin
    case (Address_EQ_Port_int_10_addr)
        1'b1 : Mux25_Outp_s = int_10_addr_Outp_s;
        default : Mux25_Outp_s = 32'b0;
    endcase
end

always_comb
begin
    case (Address_EQ_Port_int_9_addr)
        1'b1 : Mux24_Outp_s = int_9_addr_Outp_s;
        default : Mux24_Outp_s = 32'b0;
    endcase
end

always_comb
begin
    case (Address_EQ_Port_int_8_addr)
        1'b1 : Mux23_Outp_s = int_8_addr_Outp_s;
        default : Mux23_Outp_s = 32'b0;
    endcase
end

always_comb
begin
    case (Address_EQ_Port_int_7_addr)
        1'b1 : Mux22_Outp_s = int_7_addr_Outp_s;
        default : Mux22_Outp_s = 32'b0;
    endcase
end

always_comb
begin
    case (Address_EQ_Port_int_6_addr)
        1'b1 : Mux21_Outp_s = int_6_addr_Outp_s;
        default : Mux21_Outp_s = 32'b0;
    endcase
end

always_comb
begin
    case (Address_EQ_Port_int_5_addr)
        1'b1 : Mux20_Outp_s = int_5_addr_Outp_s;
        default : Mux20_Outp_s = 32'b0;
    endcase
end

always_comb
begin
    case (Address_EQ_Port_int_4_addr)
        1'b1 : Mux19_Outp_s = int_4_addr_Outp_s;
        default : Mux19_Outp_s = 32'b0;
    endcase
end

always_comb
begin
    case (Address_EQ_Port_int_3_addr)
        1'b1 : Mux18_Outp_s = int_3_addr_Outp_s;
        default : Mux18_Outp_s = 32'b0;
    endcase
end

always_comb
begin
    case (Address_EQ_Port_int_2_addr)
        1'b1 : Mux17_Outp_s = int_2_addr_Outp_s;
        default : Mux17_Outp_s = 32'b0;
    endcase
end

always_comb
begin
    case (Address_EQ_Port_int_1_addr)
        1'b1 : Mux16_Outp_s = int_1_addr_Outp_s;
        default : Mux16_Outp_s = 32'b0;
    endcase
end

always_comb
begin
    case (Address_EQ_Port_int_0_addr)
        1'b1 : Mux15_Outp_s = int_0_addr_Outp_s;
        default : Mux15_Outp_s = 32'b0;
    endcase
end

always_comb
begin
    case (Address_EQ_Port_group_priority)
        1'b1 : Mux14_Outp_s = group_priority_Outp_s;
        default : Mux14_Outp_s = 32'b0;
    endcase
end

always_comb
begin
    case (Address_EQ_Port_paused_1)
        1'b1 : Mux13_Outp_s = paused_1_Outp_s;
        default : Mux13_Outp_s = 32'b0;
    endcase
end

always_comb
begin
    case (Address_EQ_Port_paused)
        1'b1 : Mux12_Outp_s = paused_Outp_s;
        default : Mux12_Outp_s = 32'b0;
    endcase
end

always_comb
begin
    case (Address_EQ_Port_requested_1)
        1'b1 : Mux11_Outp_s = requested_1_Outp_s;
        default : Mux11_Outp_s = 32'b0;
    endcase
end

always_comb
begin
    case (Address_EQ_Port_requested)
        1'b1 : Mux10_Outp_s = requested_Outp_s;
        default : Mux10_Outp_s = 32'b0;
    endcase
end

always_comb
begin
    case (Address_EQ_Port_priority_3)
        1'b1 : Mux09_Outp_s = priority_3_Outp_s;
        default : Mux09_Outp_s = 32'b0;
    endcase
end

always_comb
begin
    case (Address_EQ_Port_priority_2)
        1'b1 : Mux08_Outp_s = priority_2_Outp_s;
        default : Mux08_Outp_s = 32'b0;
    endcase
end

always_comb
begin
    case (Address_EQ_Port_priority_1)
        1'b1 : Mux07_Outp_s = priority_1_Outp_s;
        default : Mux07_Outp_s = 32'b0;
    endcase
end

always_comb
begin
    case (Address_EQ_Port_priority)
        1'b1 : Mux06_Outp_s = priority_Outp_s;
        default : Mux06_Outp_s = 32'b0;
    endcase
end

always_comb
begin
    case (Address_EQ_Port_active_1)
        1'b1 : Mux05_Outp_s = active_1_Outp_s;
        default : Mux05_Outp_s = 32'b0;
    endcase
end

always_comb
begin
    case (Address_EQ_Port_active)
        1'b1 : Mux04_Outp_s = active_Outp_s;
        default : Mux04_Outp_s = 32'b0;
    endcase
end

always_comb
begin
    case (Address_EQ_Port_pending_1)
        1'b1 : Mux03_Outp_s = pending_1_Outp_s;
        default : Mux03_Outp_s = 32'b0;
    endcase
end

always_comb
begin
    case (Address_EQ_Port_pending)
        1'b1 : Mux02_Outp_s = pending_Outp_s;
        default : Mux02_Outp_s = 32'b0;
    endcase
end

always_comb
begin
    case (Address_EQ_Port_unmask)
        1'b1 : Mux01_Outp_s = unmask_Outp_s;
        default : Mux01_Outp_s = 32'b0;
    endcase
end

always_comb
begin
    case (Address_EQ_Port_enable)
        1'b1 : Mux00_Outp_s = enable_Outp_s;
        default : Mux00_Outp_s = 32'b0;
    endcase
end

assign BOR_Outp_s = Mux00_Outp_s | Mux01_Outp_s | Mux02_Outp_s | Mux03_Outp_s | Mux04_Outp_s | Mux05_Outp_s | Mux06_Outp_s | Mux07_Outp_s | Mux08_Outp_s | Mux09_Outp_s | Mux10_Outp_s | Mux11_Outp_s | Mux12_Outp_s | Mux13_Outp_s | Mux14_Outp_s | Mux15_Outp_s | Mux16_Outp_s | Mux17_Outp_s | Mux18_Outp_s | Mux19_Outp_s | Mux20_Outp_s | Mux21_Outp_s | Mux22_Outp_s | Mux23_Outp_s | Mux24_Outp_s | Mux25_Outp_s | Mux26_Outp_s | Mux27_Outp_s | Mux28_Outp_s | Mux29_Outp_s | Mux30_Outp_s | Mux31_Outp_s | Mux32_Outp_s | Mux33_Outp_s | Mux34_Outp_s | Mux35_Outp_s | Mux36_Outp_s | Mux37_Outp_s | Mux38_Outp_s | Mux39_Outp_s | Mux40_Outp_s | Mux41_Outp_s | Mux42_Outp_s | Mux43_Outp_s | Mux44_Outp_s | Mux45_Outp_s | Mux46_Outp_s | Mux47_Outp_s;

always_comb
begin
    case (DefaultInterface_RC_rd_en)
        1'b1 : DefaultInterface_Reading_MUX_Outp_s = BOR_Outp_s;
        default : DefaultInterface_Reading_MUX_Outp_s = 32'b0;
    endcase
end

assign DefaultInterface_Shifting_Outp_s = $signed(DefaultInterface_Reading_MUX_Outp_s) >>> DefaultInterface_RC_Shifting_Value_Mux_out;

assign DefaultInterface_RC_data_out = DefaultInterface_Shifting_Outp_s & DefaultInterface_RC_Masking_Mux_out;

assign DefaultInterface_RC_enable_int_31_out = Port_of_Reg_enable_int_31;
assign DefaultInterface_RC_enable_int_30_out = Port_of_Reg_enable_int_30;
assign DefaultInterface_RC_enable_int_29_out = Port_of_Reg_enable_int_29;
assign DefaultInterface_RC_enable_int_28_out = Port_of_Reg_enable_int_28;
assign DefaultInterface_RC_enable_int_27_out = Port_of_Reg_enable_int_27;
assign DefaultInterface_RC_enable_int_26_out = Port_of_Reg_enable_int_26;
assign DefaultInterface_RC_enable_int_25_out = Port_of_Reg_enable_int_25;
assign DefaultInterface_RC_enable_int_24_out = Port_of_Reg_enable_int_24;
assign DefaultInterface_RC_enable_int_23_out = Port_of_Reg_enable_int_23;
assign DefaultInterface_RC_enable_int_22_out = Port_of_Reg_enable_int_22;
assign DefaultInterface_RC_enable_int_21_out = Port_of_Reg_enable_int_21;
assign DefaultInterface_RC_enable_int_20_out = Port_of_Reg_enable_int_20;
assign DefaultInterface_RC_enable_int_19_out = Port_of_Reg_enable_int_19;
assign DefaultInterface_RC_enable_int_18_out = Port_of_Reg_enable_int_18;
assign DefaultInterface_RC_enable_int_17_out = Port_of_Reg_enable_int_17;
assign DefaultInterface_RC_enable_int_16_out = Port_of_Reg_enable_int_16;
assign DefaultInterface_RC_enable_int_15_out = Port_of_Reg_enable_int_15;
assign DefaultInterface_RC_enable_int_14_out = Port_of_Reg_enable_int_14;
assign DefaultInterface_RC_enable_int_13_out = Port_of_Reg_enable_int_13;
assign DefaultInterface_RC_enable_int_12_out = Port_of_Reg_enable_int_12;
assign DefaultInterface_RC_enable_int_11_out = Port_of_Reg_enable_int_11;
assign DefaultInterface_RC_enable_int_10_out = Port_of_Reg_enable_int_10;
assign DefaultInterface_RC_enable_int_9_out = Port_of_Reg_enable_int_9;
assign DefaultInterface_RC_enable_int_8_out = Port_of_Reg_enable_int_8;
assign DefaultInterface_RC_enable_int_7_out = Port_of_Reg_enable_int_7;
assign DefaultInterface_RC_enable_int_6_out = Port_of_Reg_enable_int_6;
assign DefaultInterface_RC_enable_int_5_out = Port_of_Reg_enable_int_5;
assign DefaultInterface_RC_enable_int_4_out = Port_of_Reg_enable_int_4;
assign DefaultInterface_RC_enable_int_3_out = Port_of_Reg_enable_int_3;
assign DefaultInterface_RC_enable_int_2_out = Port_of_Reg_enable_int_2;
assign DefaultInterface_RC_enable_int_1_out = Port_of_Reg_enable_int_1;
assign DefaultInterface_RC_enable_int_0_out = Port_of_Reg_enable_int_0;
assign DefaultInterface_RC_unmask_int_31_out = Port_of_Reg_unmask_int_31;
assign DefaultInterface_RC_unmask_int_30_out = Port_of_Reg_unmask_int_30;
assign DefaultInterface_RC_unmask_int_29_out = Port_of_Reg_unmask_int_29;
assign DefaultInterface_RC_unmask_int_28_out = Port_of_Reg_unmask_int_28;
assign DefaultInterface_RC_unmask_int_27_out = Port_of_Reg_unmask_int_27;
assign DefaultInterface_RC_unmask_int_26_out = Port_of_Reg_unmask_int_26;
assign DefaultInterface_RC_unmask_int_25_out = Port_of_Reg_unmask_int_25;
assign DefaultInterface_RC_unmask_int_24_out = Port_of_Reg_unmask_int_24;
assign DefaultInterface_RC_unmask_int_23_out = Port_of_Reg_unmask_int_23;
assign DefaultInterface_RC_unmask_int_22_out = Port_of_Reg_unmask_int_22;
assign DefaultInterface_RC_unmask_int_21_out = Port_of_Reg_unmask_int_21;
assign DefaultInterface_RC_unmask_int_20_out = Port_of_Reg_unmask_int_20;
assign DefaultInterface_RC_unmask_int_19_out = Port_of_Reg_unmask_int_19;
assign DefaultInterface_RC_unmask_int_18_out = Port_of_Reg_unmask_int_18;
assign DefaultInterface_RC_unmask_int_17_out = Port_of_Reg_unmask_int_17;
assign DefaultInterface_RC_unmask_int_16_out = Port_of_Reg_unmask_int_16;
assign DefaultInterface_RC_unmask_int_15_out = Port_of_Reg_unmask_int_15;
assign DefaultInterface_RC_unmask_int_14_out = Port_of_Reg_unmask_int_14;
assign DefaultInterface_RC_unmask_int_13_out = Port_of_Reg_unmask_int_13;
assign DefaultInterface_RC_unmask_int_12_out = Port_of_Reg_unmask_int_12;
assign DefaultInterface_RC_unmask_int_11_out = Port_of_Reg_unmask_int_11;
assign DefaultInterface_RC_unmask_int_10_out = Port_of_Reg_unmask_int_10;
assign DefaultInterface_RC_unmask_int_9_out = Port_of_Reg_unmask_int_9;
assign DefaultInterface_RC_unmask_int_8_out = Port_of_Reg_unmask_int_8;
assign DefaultInterface_RC_unmask_int_7_out = Port_of_Reg_unmask_int_7;
assign DefaultInterface_RC_unmask_int_6_out = Port_of_Reg_unmask_int_6;
assign DefaultInterface_RC_unmask_int_5_out = Port_of_Reg_unmask_int_5;
assign DefaultInterface_RC_unmask_int_4_out = Port_of_Reg_unmask_int_4;
assign DefaultInterface_RC_unmask_int_3_out = Port_of_Reg_unmask_int_3;
assign DefaultInterface_RC_unmask_int_2_out = Port_of_Reg_unmask_int_2;
assign DefaultInterface_RC_unmask_int_1_out = Port_of_Reg_unmask_int_1;
assign DefaultInterface_RC_unmask_int_0_out = Port_of_Reg_unmask_int_0;
assign DefaultInterface_RC_pending_int_31_out = Port_of_Reg_pending_int_31;
assign DefaultInterface_RC_pending_int_30_out = Port_of_Reg_pending_int_30;
assign DefaultInterface_RC_pending_int_29_out = Port_of_Reg_pending_int_29;
assign DefaultInterface_RC_pending_int_28_out = Port_of_Reg_pending_int_28;
assign DefaultInterface_RC_pending_int_27_out = Port_of_Reg_pending_int_27;
assign DefaultInterface_RC_pending_int_26_out = Port_of_Reg_pending_int_26;
assign DefaultInterface_RC_pending_int_25_out = Port_of_Reg_pending_int_25;
assign DefaultInterface_RC_pending_int_24_out = Port_of_Reg_pending_int_24;
assign DefaultInterface_RC_pending_int_23_out = Port_of_Reg_pending_int_23;
assign DefaultInterface_RC_pending_int_22_out = Port_of_Reg_pending_int_22;
assign DefaultInterface_RC_pending_int_21_out = Port_of_Reg_pending_int_21;
assign DefaultInterface_RC_pending_int_20_out = Port_of_Reg_pending_int_20;
assign DefaultInterface_RC_pending_int_19_out = Port_of_Reg_pending_int_19;
assign DefaultInterface_RC_pending_int_18_out = Port_of_Reg_pending_int_18;
assign DefaultInterface_RC_pending_int_17_out = Port_of_Reg_pending_int_17;
assign DefaultInterface_RC_pending_int_16_out = Port_of_Reg_pending_int_16;
assign DefaultInterface_RC_pending_int_15_out = Port_of_Reg_pending_int_15;
assign DefaultInterface_RC_pending_int_14_out = Port_of_Reg_pending_int_14;
assign DefaultInterface_RC_pending_int_13_out = Port_of_Reg_pending_int_13;
assign DefaultInterface_RC_pending_int_12_out = Port_of_Reg_pending_int_12;
assign DefaultInterface_RC_pending_int_11_out = Port_of_Reg_pending_int_11;
assign DefaultInterface_RC_pending_int_10_out = Port_of_Reg_pending_int_10;
assign DefaultInterface_RC_pending_int_9_out = Port_of_Reg_pending_int_9;
assign DefaultInterface_RC_pending_int_8_out = Port_of_Reg_pending_int_8;
assign DefaultInterface_RC_pending_int_7_out = Port_of_Reg_pending_int_7;
assign DefaultInterface_RC_pending_int_6_out = Port_of_Reg_pending_int_6;
assign DefaultInterface_RC_pending_int_5_out = Port_of_Reg_pending_int_5;
assign DefaultInterface_RC_pending_int_4_out = Port_of_Reg_pending_int_4;
assign DefaultInterface_RC_pending_int_3_out = Port_of_Reg_pending_int_3;
assign DefaultInterface_RC_pending_int_2_out = Port_of_Reg_pending_int_2;
assign DefaultInterface_RC_pending_int_1_out = Port_of_Reg_pending_int_1;
assign DefaultInterface_RC_pending_int_0_out = Port_of_Reg_pending_int_0;
assign DefaultInterface_RC_pending_NMI_out = Port_of_Reg_pending_NMI;
assign DefaultInterface_RC_active_int_31_out = Port_of_Reg_active_int_31;
assign DefaultInterface_RC_active_int_30_out = Port_of_Reg_active_int_30;
assign DefaultInterface_RC_active_int_29_out = Port_of_Reg_active_int_29;
assign DefaultInterface_RC_active_int_28_out = Port_of_Reg_active_int_28;
assign DefaultInterface_RC_active_int_27_out = Port_of_Reg_active_int_27;
assign DefaultInterface_RC_active_int_26_out = Port_of_Reg_active_int_26;
assign DefaultInterface_RC_active_int_25_out = Port_of_Reg_active_int_25;
assign DefaultInterface_RC_active_int_24_out = Port_of_Reg_active_int_24;
assign DefaultInterface_RC_active_int_23_out = Port_of_Reg_active_int_23;
assign DefaultInterface_RC_active_int_22_out = Port_of_Reg_active_int_22;
assign DefaultInterface_RC_active_int_21_out = Port_of_Reg_active_int_21;
assign DefaultInterface_RC_active_int_20_out = Port_of_Reg_active_int_20;
assign DefaultInterface_RC_active_int_19_out = Port_of_Reg_active_int_19;
assign DefaultInterface_RC_active_int_18_out = Port_of_Reg_active_int_18;
assign DefaultInterface_RC_active_int_17_out = Port_of_Reg_active_int_17;
assign DefaultInterface_RC_active_int_16_out = Port_of_Reg_active_int_16;
assign DefaultInterface_RC_active_int_15_out = Port_of_Reg_active_int_15;
assign DefaultInterface_RC_active_int_14_out = Port_of_Reg_active_int_14;
assign DefaultInterface_RC_active_int_13_out = Port_of_Reg_active_int_13;
assign DefaultInterface_RC_active_int_12_out = Port_of_Reg_active_int_12;
assign DefaultInterface_RC_active_int_11_out = Port_of_Reg_active_int_11;
assign DefaultInterface_RC_active_int_10_out = Port_of_Reg_active_int_10;
assign DefaultInterface_RC_active_int_9_out = Port_of_Reg_active_int_9;
assign DefaultInterface_RC_active_int_8_out = Port_of_Reg_active_int_8;
assign DefaultInterface_RC_active_int_7_out = Port_of_Reg_active_int_7;
assign DefaultInterface_RC_active_int_6_out = Port_of_Reg_active_int_6;
assign DefaultInterface_RC_active_int_5_out = Port_of_Reg_active_int_5;
assign DefaultInterface_RC_active_int_4_out = Port_of_Reg_active_int_4;
assign DefaultInterface_RC_active_int_3_out = Port_of_Reg_active_int_3;
assign DefaultInterface_RC_active_int_2_out = Port_of_Reg_active_int_2;
assign DefaultInterface_RC_active_int_1_out = Port_of_Reg_active_int_1;
assign DefaultInterface_RC_active_int_0_out = Port_of_Reg_active_int_0;
assign DefaultInterface_RC_active_NMI_out = Port_of_Reg_active_NMI;
assign DefaultInterface_RC_priority_int_9_out = Port_of_Reg_priority_int_9;
assign DefaultInterface_RC_priority_int_8_out = Port_of_Reg_priority_int_8;
assign DefaultInterface_RC_priority_int_7_out = Port_of_Reg_priority_int_7;
assign DefaultInterface_RC_priority_int_6_out = Port_of_Reg_priority_int_6;
assign DefaultInterface_RC_priority_int_5_out = Port_of_Reg_priority_int_5;
assign DefaultInterface_RC_priority_int_4_out = Port_of_Reg_priority_int_4;
assign DefaultInterface_RC_priority_int_3_out = Port_of_Reg_priority_int_3;
assign DefaultInterface_RC_priority_int_2_out = Port_of_Reg_priority_int_2;
assign DefaultInterface_RC_priority_int_1_out = Port_of_Reg_priority_int_1;
assign DefaultInterface_RC_priority_int_0_out = Port_of_Reg_priority_int_0;
assign DefaultInterface_RC_priority_int_19_out = Port_of_Reg_priority_int_19;
assign DefaultInterface_RC_priority_int_18_out = Port_of_Reg_priority_int_18;
assign DefaultInterface_RC_priority_int_17_out = Port_of_Reg_priority_int_17;
assign DefaultInterface_RC_priority_int_16_out = Port_of_Reg_priority_int_16;
assign DefaultInterface_RC_priority_int_15_out = Port_of_Reg_priority_int_15;
assign DefaultInterface_RC_priority_int_14_out = Port_of_Reg_priority_int_14;
assign DefaultInterface_RC_priority_int_13_out = Port_of_Reg_priority_int_13;
assign DefaultInterface_RC_priority_int_12_out = Port_of_Reg_priority_int_12;
assign DefaultInterface_RC_priority_int_11_out = Port_of_Reg_priority_int_11;
assign DefaultInterface_RC_priority_int_10_out = Port_of_Reg_priority_int_10;
assign DefaultInterface_RC_priority_int_29_out = Port_of_Reg_priority_int_29;
assign DefaultInterface_RC_priority_int_28_out = Port_of_Reg_priority_int_28;
assign DefaultInterface_RC_priority_int_27_out = Port_of_Reg_priority_int_27;
assign DefaultInterface_RC_priority_int_26_out = Port_of_Reg_priority_int_26;
assign DefaultInterface_RC_priority_int_25_out = Port_of_Reg_priority_int_25;
assign DefaultInterface_RC_priority_int_24_out = Port_of_Reg_priority_int_24;
assign DefaultInterface_RC_priority_int_23_out = Port_of_Reg_priority_int_23;
assign DefaultInterface_RC_priority_int_22_out = Port_of_Reg_priority_int_22;
assign DefaultInterface_RC_priority_int_21_out = Port_of_Reg_priority_int_21;
assign DefaultInterface_RC_priority_int_20_out = Port_of_Reg_priority_int_20;
assign DefaultInterface_RC_priority_int_31_out = Port_of_Reg_priority_int_31;
assign DefaultInterface_RC_priority_int_30_out = Port_of_Reg_priority_int_30;
assign DefaultInterface_RC_requested_int_31_out = Port_of_Reg_requested_int_31;
assign DefaultInterface_RC_requested_int_30_out = Port_of_Reg_requested_int_30;
assign DefaultInterface_RC_requested_int_29_out = Port_of_Reg_requested_int_29;
assign DefaultInterface_RC_requested_int_28_out = Port_of_Reg_requested_int_28;
assign DefaultInterface_RC_requested_int_27_out = Port_of_Reg_requested_int_27;
assign DefaultInterface_RC_requested_int_26_out = Port_of_Reg_requested_int_26;
assign DefaultInterface_RC_requested_int_25_out = Port_of_Reg_requested_int_25;
assign DefaultInterface_RC_requested_int_24_out = Port_of_Reg_requested_int_24;
assign DefaultInterface_RC_requested_int_23_out = Port_of_Reg_requested_int_23;
assign DefaultInterface_RC_requested_int_22_out = Port_of_Reg_requested_int_22;
assign DefaultInterface_RC_requested_int_21_out = Port_of_Reg_requested_int_21;
assign DefaultInterface_RC_requested_int_20_out = Port_of_Reg_requested_int_20;
assign DefaultInterface_RC_requested_int_19_out = Port_of_Reg_requested_int_19;
assign DefaultInterface_RC_requested_int_18_out = Port_of_Reg_requested_int_18;
assign DefaultInterface_RC_requested_int_17_out = Port_of_Reg_requested_int_17;
assign DefaultInterface_RC_requested_int_16_out = Port_of_Reg_requested_int_16;
assign DefaultInterface_RC_requested_int_15_out = Port_of_Reg_requested_int_15;
assign DefaultInterface_RC_requested_int_14_out = Port_of_Reg_requested_int_14;
assign DefaultInterface_RC_requested_int_13_out = Port_of_Reg_requested_int_13;
assign DefaultInterface_RC_requested_int_12_out = Port_of_Reg_requested_int_12;
assign DefaultInterface_RC_requested_int_11_out = Port_of_Reg_requested_int_11;
assign DefaultInterface_RC_requested_int_10_out = Port_of_Reg_requested_int_10;
assign DefaultInterface_RC_requested_int_9_out = Port_of_Reg_requested_int_9;
assign DefaultInterface_RC_requested_int_8_out = Port_of_Reg_requested_int_8;
assign DefaultInterface_RC_requested_int_7_out = Port_of_Reg_requested_int_7;
assign DefaultInterface_RC_requested_int_6_out = Port_of_Reg_requested_int_6;
assign DefaultInterface_RC_requested_int_5_out = Port_of_Reg_requested_int_5;
assign DefaultInterface_RC_requested_int_4_out = Port_of_Reg_requested_int_4;
assign DefaultInterface_RC_requested_int_3_out = Port_of_Reg_requested_int_3;
assign DefaultInterface_RC_requested_int_2_out = Port_of_Reg_requested_int_2;
assign DefaultInterface_RC_requested_int_1_out = Port_of_Reg_requested_int_1;
assign DefaultInterface_RC_requested_int_0_out = Port_of_Reg_requested_int_0;
assign DefaultInterface_RC_requested_NMI_out = Port_of_Reg_requested_NMI;
assign DefaultInterface_RC_paused_int_31_out = Port_of_Reg_paused_int_31;
assign DefaultInterface_RC_paused_int_30_out = Port_of_Reg_paused_int_30;
assign DefaultInterface_RC_paused_int_29_out = Port_of_Reg_paused_int_29;
assign DefaultInterface_RC_paused_int_28_out = Port_of_Reg_paused_int_28;
assign DefaultInterface_RC_paused_int_27_out = Port_of_Reg_paused_int_27;
assign DefaultInterface_RC_paused_int_26_out = Port_of_Reg_paused_int_26;
assign DefaultInterface_RC_paused_int_25_out = Port_of_Reg_paused_int_25;
assign DefaultInterface_RC_paused_int_24_out = Port_of_Reg_paused_int_24;
assign DefaultInterface_RC_paused_int_23_out = Port_of_Reg_paused_int_23;
assign DefaultInterface_RC_paused_int_22_out = Port_of_Reg_paused_int_22;
assign DefaultInterface_RC_paused_int_21_out = Port_of_Reg_paused_int_21;
assign DefaultInterface_RC_paused_int_20_out = Port_of_Reg_paused_int_20;
assign DefaultInterface_RC_paused_int_19_out = Port_of_Reg_paused_int_19;
assign DefaultInterface_RC_paused_int_18_out = Port_of_Reg_paused_int_18;
assign DefaultInterface_RC_paused_int_17_out = Port_of_Reg_paused_int_17;
assign DefaultInterface_RC_paused_int_16_out = Port_of_Reg_paused_int_16;
assign DefaultInterface_RC_paused_int_15_out = Port_of_Reg_paused_int_15;
assign DefaultInterface_RC_paused_int_14_out = Port_of_Reg_paused_int_14;
assign DefaultInterface_RC_paused_int_13_out = Port_of_Reg_paused_int_13;
assign DefaultInterface_RC_paused_int_12_out = Port_of_Reg_paused_int_12;
assign DefaultInterface_RC_paused_int_11_out = Port_of_Reg_paused_int_11;
assign DefaultInterface_RC_paused_int_10_out = Port_of_Reg_paused_int_10;
assign DefaultInterface_RC_paused_int_9_out = Port_of_Reg_paused_int_9;
assign DefaultInterface_RC_paused_int_8_out = Port_of_Reg_paused_int_8;
assign DefaultInterface_RC_paused_int_7_out = Port_of_Reg_paused_int_7;
assign DefaultInterface_RC_paused_int_6_out = Port_of_Reg_paused_int_6;
assign DefaultInterface_RC_paused_int_5_out = Port_of_Reg_paused_int_5;
assign DefaultInterface_RC_paused_int_4_out = Port_of_Reg_paused_int_4;
assign DefaultInterface_RC_paused_int_3_out = Port_of_Reg_paused_int_3;
assign DefaultInterface_RC_paused_int_2_out = Port_of_Reg_paused_int_2;
assign DefaultInterface_RC_paused_int_1_out = Port_of_Reg_paused_int_1;
assign DefaultInterface_RC_paused_int_0_out = Port_of_Reg_paused_int_0;
assign DefaultInterface_RC_paused_NMI_out = Port_of_Reg_paused_NMI;
assign DefaultInterface_RC_group_priority_Group4_out = Port_of_Reg_group_priority_Group4;
assign DefaultInterface_RC_group_priority_Group3_out = Port_of_Reg_group_priority_Group3;
assign DefaultInterface_RC_group_priority_Group2_out = Port_of_Reg_group_priority_Group2;
assign DefaultInterface_RC_group_priority_Group1_out = Port_of_Reg_group_priority_Group1;
assign DefaultInterface_RC_addr_int_0_out = Port_of_Reg_addr_int_0;
assign DefaultInterface_RC_addr_int_1_out = Port_of_Reg_addr_int_1;
assign DefaultInterface_RC_addr_int_2_out = Port_of_Reg_addr_int_2;
assign DefaultInterface_RC_addr_int_3_out = Port_of_Reg_addr_int_3;
assign DefaultInterface_RC_addr_int_4_out = Port_of_Reg_addr_int_4;
assign DefaultInterface_RC_addr_int_5_out = Port_of_Reg_addr_int_5;
assign DefaultInterface_RC_addr_int_6_out = Port_of_Reg_addr_int_6;
assign DefaultInterface_RC_addr_int_7_out = Port_of_Reg_addr_int_7;
assign DefaultInterface_RC_addr_int_8_out = Port_of_Reg_addr_int_8;
assign DefaultInterface_RC_addr_int_9_out = Port_of_Reg_addr_int_9;
assign DefaultInterface_RC_addr_int_10_out = Port_of_Reg_addr_int_10;
assign DefaultInterface_RC_addr_int_11_out = Port_of_Reg_addr_int_11;
assign DefaultInterface_RC_addr_int_12_out = Port_of_Reg_addr_int_12;
assign DefaultInterface_RC_addr_int_13_out = Port_of_Reg_addr_int_13;
assign DefaultInterface_RC_addr_int_14_out = Port_of_Reg_addr_int_14;
assign DefaultInterface_RC_addr_int_15_out = Port_of_Reg_addr_int_15;
assign DefaultInterface_RC_addr_int_16_out = Port_of_Reg_addr_int_16;
assign DefaultInterface_RC_addr_int_17_out = Port_of_Reg_addr_int_17;
assign DefaultInterface_RC_addr_int_18_out = Port_of_Reg_addr_int_18;
assign DefaultInterface_RC_addr_int_19_out = Port_of_Reg_addr_int_19;
assign DefaultInterface_RC_addr_int_20_out = Port_of_Reg_addr_int_20;
assign DefaultInterface_RC_addr_int_21_out = Port_of_Reg_addr_int_21;
assign DefaultInterface_RC_addr_int_22_out = Port_of_Reg_addr_int_22;
assign DefaultInterface_RC_addr_int_23_out = Port_of_Reg_addr_int_23;
assign DefaultInterface_RC_addr_int_24_out = Port_of_Reg_addr_int_24;
assign DefaultInterface_RC_addr_int_25_out = Port_of_Reg_addr_int_25;
assign DefaultInterface_RC_addr_int_26_out = Port_of_Reg_addr_int_26;
assign DefaultInterface_RC_addr_int_27_out = Port_of_Reg_addr_int_27;
assign DefaultInterface_RC_addr_int_28_out = Port_of_Reg_addr_int_28;
assign DefaultInterface_RC_addr_int_29_out = Port_of_Reg_addr_int_29;
assign DefaultInterface_RC_addr_int_30_out = Port_of_Reg_addr_int_30;
assign DefaultInterface_RC_addr_int_31_out = Port_of_Reg_addr_int_31;
assign DefaultInterface_RC_addr_NMI_out = Port_of_Reg_addr_NMI;

endmodule

