/* ===============================================================
Copyright 2026, Infineon Technologies AG or an 
affiliate of Infineon Technologies AG.  All rights reserved.
 
This software, associated documentation and materials ("Software") is owned by
Infineon Technologies AG or one of its affiliates ("Infineon") and is 
protected by and subject to worldwide patent protection (United States and 
foreign), United States copyright laws and international treaty provisions. 
Therefore, you may use this Software only as provided in the license agreement
accompanying the software package from which you obtained this 
Software ("EULA"). If no EULA applies, then any reproduction, modification, 
translation, compilation, or representation of this Software is prohibited 
without the express written permission of Infineon.
 
Disclaimer: THIS SOFTWARE IS PROVIDED AS-IS, WITH NO WARRANTY OF 
ANY KIND, EXPRESS OR IMPLIED, INCLUDING, BUT NOT LIMITED TO, 
NONINFRINGEMENT, IMPLIED WARRANTIES OF  MERCHANTABILITY AND
FITNESS FOR A PARTICULAR PURPOSE.  Infineon reserves the right to make
changes to the Software without notice. Infineon does not assume any liability
arising out of the application or use of the Software or any product or 
circuit described in the Software. Infineon does not authorize its products 
for use in any products where a malfunction or failure of the Infineon product 
may reasonably be expected to result in significant property damage, injury or
death ("High Risk Product").  By including Infineon 's product in a High Risk 
Product, the manufacturer of such system or application assumes all risk of 
such use and in doing so agrees to indemnify Infineon against all liability.

 ===============================================================
*/ 
// File : InterruptController_Reg_IF_AHB_RAI_Bridge_bridge_fsm.sv 
// Author : tahiraga 
// Date : 18:21:28    21/09/2026 
// Revision :  
// =============================================================== 
// Description : 
/*
---- Auto Generated by MetaRTL , a MetaGen application
---- Contact: ParitoshKumar.Sinha@infineon.com
---- Contact: Yash.Ranjan@infineon.com
===============================================================
*/


module InterruptController_Reg_IF_AHB_RAI_Bridge_bridge_fsm (
    input [31:0] haddr_i,
    input [31:0] hwdata_i,
    input [2:0] hsize_i,
    input [1:0] htrans_i,
    input hwrite_i,
    input hsel_i,
    input hready_i,
    input rai_per_err_i,
    input access_done_i,
    output hreadyout_o,
    output hresp_o,
    output logic  [2:0] hsize_o,
    output logic  hwrite_o,
    output access_en,
    output [31:0] haddr_o,
    output logic  [31:0] hwdata_o,
    output [31:0] haddr_reg_Outp_out,
    input HCLK_i,
    input HRESET_n_i
);

localparam rsp_okay_c = 1'b0;
localparam rsp_error_c = 1'b1;

logic   BAND00_Outp_s;
logic   LAND01_Outp_s;
logic   LAND00_Outp_s;
logic   FSM_Core_hreadyout_o_s;
logic   FSM_Core_hresp_o_s;
logic   FSM_Core_fsm_check_flag_s;

logic   [31:0] haddr_reg_Outp_s;
logic   delayed_error_reg_Outp_s;
logic   burst_err_reg_Outp_s;
logic   hsel_reg_Outp_s;

always_comb
begin
    case (hsel_reg_Outp_s)
        1'b0 : hwdata_o = 32'b0;
        1'b1 : hwdata_o = hwdata_i;
        default : hwdata_o = 32'b0;
    endcase
end

always_ff @(negedge HRESET_n_i, posedge HCLK_i)
begin
    if (HRESET_n_i == 1'b0) begin
        haddr_reg_Outp_s <= 32'b0;
    end else begin
        if (BAND00_Outp_s == 1'b1) begin
            haddr_reg_Outp_s <= haddr_i;
        end
    end
end
assign haddr_o = haddr_reg_Outp_s;
assign haddr_reg_Outp_out = haddr_reg_Outp_s;

assign access_en = hsel_reg_Outp_s & (~FSM_Core_hresp_o_s);

always_ff @(negedge HRESET_n_i, posedge HCLK_i)
begin
    if (HRESET_n_i == 1'b0) begin
        hwrite_o <= 1'b0;
    end else begin
        if (BAND00_Outp_s == 1'b1) begin
            hwrite_o <= hwrite_i;
        end
    end
end

always_ff @(negedge HRESET_n_i, posedge HCLK_i)
begin
    if (HRESET_n_i == 1'b0) begin
        hsize_o <= 3'b0;
    end else begin
        if (BAND00_Outp_s == 1'b1) begin
            hsize_o <= hsize_i;
        end
    end
end

always_ff @(negedge HRESET_n_i, posedge HCLK_i)
begin
    if (HRESET_n_i == 1'b0) begin
        delayed_error_reg_Outp_s <= 1'b0;
    end else begin
        if (1'b1 == 1'b1) begin
            delayed_error_reg_Outp_s <= rai_per_err_i;
        end
    end
end

assign hresp_o = FSM_Core_hresp_o_s | rai_per_err_i | delayed_error_reg_Outp_s;

assign BAND00_Outp_s = LAND00_Outp_s & FSM_Core_fsm_check_flag_s;

assign LAND01_Outp_s = LAND00_Outp_s & (~(htrans_i == 2'b10 ? 1'b1 : 1'b0));

assign LAND00_Outp_s = hready_i & hsel_i & (~(htrans_i == 2'b0 ? 1'b1 : 1'b0));

always_ff @(negedge HRESET_n_i, posedge HCLK_i)
begin
    if (HRESET_n_i == 1'b0) begin
        burst_err_reg_Outp_s <= 1'b0;
    end else begin
        if (BAND00_Outp_s == 1'b1) begin
            burst_err_reg_Outp_s <= LAND01_Outp_s;
        end
    end
end

always_ff @(negedge HRESET_n_i, posedge HCLK_i)
begin
    if (HRESET_n_i == 1'b0) begin
        hsel_reg_Outp_s <= 1'b0;
    end else begin
        if (FSM_Core_fsm_check_flag_s == 1'b1) begin
            hsel_reg_Outp_s <= LAND00_Outp_s;
        end
    end
end

InterruptController_Reg_IF_AHB_RAI_Bridge_bridge_fsm_FSM_Core comp_FSM_Core(
    .hsel_i         ( hsel_reg_Outp_s           ),
    .rai_per_err_i  ( burst_err_reg_Outp_s      ),
    .access_done_i  ( access_done_i             ),
    .Clk            ( HCLK_i                    ),
    .AsyncRst       ( HRESET_n_i                ),
    .hreadyout_o    ( FSM_Core_hreadyout_o_s    ),
    .hresp_o        ( FSM_Core_hresp_o_s        ),
    .fsm_check_flag ( FSM_Core_fsm_check_flag_s )
);

assign hreadyout_o = FSM_Core_hreadyout_o_s & (~rai_per_err_i);


endmodule

