/* ===============================================================
Copyright 2026, Infineon Technologies AG or an 
affiliate of Infineon Technologies AG.  All rights reserved.
 
This software, associated documentation and materials ("Software") is owned by
Infineon Technologies AG or one of its affiliates ("Infineon") and is 
protected by and subject to worldwide patent protection (United States and 
foreign), United States copyright laws and international treaty provisions. 
Therefore, you may use this Software only as provided in the license agreement
accompanying the software package from which you obtained this 
Software ("EULA"). If no EULA applies, then any reproduction, modification, 
translation, compilation, or representation of this Software is prohibited 
without the express written permission of Infineon.
 
Disclaimer: THIS SOFTWARE IS PROVIDED AS-IS, WITH NO WARRANTY OF 
ANY KIND, EXPRESS OR IMPLIED, INCLUDING, BUT NOT LIMITED TO, 
NONINFRINGEMENT, IMPLIED WARRANTIES OF  MERCHANTABILITY AND
FITNESS FOR A PARTICULAR PURPOSE.  Infineon reserves the right to make
changes to the Software without notice. Infineon does not assume any liability
arising out of the application or use of the Software or any product or 
circuit described in the Software. Infineon does not authorize its products 
for use in any products where a malfunction or failure of the Infineon product 
may reasonably be expected to result in significant property damage, injury or
death ("High Risk Product").  By including Infineon 's product in a High Risk 
Product, the manufacturer of such system or application assumes all risk of 
such use and in doing so agrees to indemnify Infineon against all liability.

 ===============================================================
*/ 
// File : InterruptController_Reg_IF_AHB_RAI_Bridge_bridge_fsm_FSM_Core.sv 
// Author : tahiraga 
// Date : 18:20:55    21/09/2026 
// Revision :  
// =============================================================== 
// Description : 
/*
---- Auto Generated by MetaRTL , a MetaGen application
---- Contact: ParitoshKumar.Sinha@infineon.com
---- Contact: Yash.Ranjan@infineon.com
===============================================================
*/


module InterruptController_Reg_IF_AHB_RAI_Bridge_bridge_fsm_FSM_Core (
    input hsel_i,
    input rai_per_err_i,
    input access_done_i,
    output logic  hreadyout_o,
    output logic  hresp_o,
    output logic  fsm_check_flag,
    input Clk,
    input AsyncRst
);

localparam FSM_RESP_CHECK = 2'b0;
localparam FSM_RESP_WAIT = 2'b1;
localparam FSM_RESP_ERROR = 2'b10;

logic   [1:0] state;
logic   [1:0] next_state;

always_ff @(posedge Clk, negedge AsyncRst)
begin
    if (AsyncRst == 1'b0) begin
        state <= FSM_RESP_CHECK;
    end else begin
        state <= next_state;
    end
end
always_comb
begin
    next_state = state;
    case (state)
        FSM_RESP_CHECK : begin
            if ((hsel_i == 1'b1) & (rai_per_err_i == 1'b0) & (access_done_i == 1'b1)) begin
                next_state = FSM_RESP_CHECK;
            end
            else if (hsel_i == 1'b0) begin
                next_state = FSM_RESP_CHECK;
            end
            else if ((1'b1 == hsel_i) & (rai_per_err_i == 1'b1)) begin
                next_state = FSM_RESP_ERROR;
            end
            else if ((1'b1 == hsel_i) & (rai_per_err_i == 1'b0) & (access_done_i == 1'b0)) begin
                next_state = FSM_RESP_WAIT;
            end
        end
        FSM_RESP_WAIT : begin
            if ((access_done_i == 1'b1) & (rai_per_err_i == 1'b0)) begin
                next_state = FSM_RESP_CHECK;
            end
            else if ((access_done_i == 1'b1) & (rai_per_err_i == 1'b1)) begin
                next_state = FSM_RESP_ERROR;
            end
            else if (access_done_i == 1'b0) begin
                next_state = FSM_RESP_WAIT;
            end
        end
        FSM_RESP_ERROR : begin
            if (1'b0 == 1'b0) begin
                next_state = FSM_RESP_CHECK;
            end
        end
        default : next_state = state;
    endcase
end

always_comb
begin
    hreadyout_o = 1'b0;
    hresp_o = 1'b0;
    fsm_check_flag = 1'b0;
    case (state)
        FSM_RESP_CHECK : begin
            if ((hsel_i == 1'b1) & (rai_per_err_i == 1'b0) & (access_done_i == 1'b1)) begin
                hreadyout_o = 1'b1;
                hresp_o = 1'b0;
                fsm_check_flag = 1'b1;
            end
            else if (hsel_i == 1'b0) begin
                hreadyout_o = 1'b1;
                hresp_o = 1'b0;
                fsm_check_flag = 1'b1;
            end
            else if ((1'b1 == hsel_i) & (rai_per_err_i == 1'b1)) begin
                hreadyout_o = 1'b0;
                hresp_o = 1'b1;
                fsm_check_flag = 1'b0;
            end
            else if ((1'b1 == hsel_i) & (rai_per_err_i == 1'b0) & (access_done_i == 1'b0)) begin
                hreadyout_o = 1'b0;
                hresp_o = 1'b0;
                fsm_check_flag = 1'b0;
            end
        end
        FSM_RESP_WAIT : begin
            if ((access_done_i == 1'b1) & (rai_per_err_i == 1'b0)) begin
                hreadyout_o = 1'b1;
                hresp_o = 1'b0;
                fsm_check_flag = 1'b1;
            end
            else if ((access_done_i == 1'b1) & (rai_per_err_i == 1'b1)) begin
                hreadyout_o = 1'b0;
                hresp_o = 1'b1;
                fsm_check_flag = 1'b0;
            end
            else if (access_done_i == 1'b0) begin
                hreadyout_o = 1'b0;
                hresp_o = 1'b0;
                fsm_check_flag = 1'b0;
            end
        end
        FSM_RESP_ERROR : begin
            if (1'b0 == 1'b0) begin
                hreadyout_o = 1'b1;
                hresp_o = 1'b1;
                fsm_check_flag = 1'b1;
            end
        end
        default : begin
            hreadyout_o = 1'b1;
            hresp_o = 1'b0;
            fsm_check_flag = 1'b1;
        end
    endcase
end

endmodule

