/* ===============================================================
Copyright 2026, Infineon Technologies AG or an 
affiliate of Infineon Technologies AG.  All rights reserved.
 
This software, associated documentation and materials ("Software") is owned by
Infineon Technologies AG or one of its affiliates ("Infineon") and is 
protected by and subject to worldwide patent protection (United States and 
foreign), United States copyright laws and international treaty provisions. 
Therefore, you may use this Software only as provided in the license agreement
accompanying the software package from which you obtained this 
Software ("EULA"). If no EULA applies, then any reproduction, modification, 
translation, compilation, or representation of this Software is prohibited 
without the express written permission of Infineon.
 
Disclaimer: THIS SOFTWARE IS PROVIDED AS-IS, WITH NO WARRANTY OF 
ANY KIND, EXPRESS OR IMPLIED, INCLUDING, BUT NOT LIMITED TO, 
NONINFRINGEMENT, IMPLIED WARRANTIES OF  MERCHANTABILITY AND
FITNESS FOR A PARTICULAR PURPOSE.  Infineon reserves the right to make
changes to the Software without notice. Infineon does not assume any liability
arising out of the application or use of the Software or any product or 
circuit described in the Software. Infineon does not authorize its products 
for use in any products where a malfunction or failure of the Infineon product 
may reasonably be expected to result in significant property damage, injury or
death ("High Risk Product").  By including Infineon 's product in a High Risk 
Product, the manufacturer of such system or application assumes all risk of 
such use and in doing so agrees to indemnify Infineon against all liability.

 ===============================================================
*/ 
// File : InterruptController_ICcomponent_IRQ_receiver32.sv 
// Author : tahiraga 
// Date : 18:22:21    21/09/2026 
// Revision :  
// =============================================================== 
// Description : 
/*
---- Auto Generated by MetaRTL , a MetaGen application
---- Contact: ParitoshKumar.Sinha@infineon.com
---- Contact: Yash.Ranjan@infineon.com
===============================================================
*/


module InterruptController_IRQ_receiver (
    input int_req,
    input eoi,
    input level_sens,
    input status_pending,
    output set_pending,
    output clr_pending,
    output int_ignrd,
    input HCLK_i,
    input HRESET_n_i
);

logic   BAND00_Outp_s;
logic   EDGE_SENS_LAND_Outp_s;

logic   EDGE_SENS_Register_Outp_s;

assign int_ignrd = status_pending & EDGE_SENS_LAND_Outp_s;

assign clr_pending = status_pending & eoi;

always_ff @(negedge HRESET_n_i, posedge HCLK_i)
begin
    if (HRESET_n_i == 1'b0) begin
        EDGE_SENS_Register_Outp_s <= 1'b0;
    end else begin
        EDGE_SENS_Register_Outp_s <= BAND00_Outp_s;
    end
end

assign BAND00_Outp_s = ((~level_sens) | (~status_pending)) & int_req;

assign EDGE_SENS_LAND_Outp_s = (BAND00_Outp_s ^ EDGE_SENS_Register_Outp_s) & BAND00_Outp_s;

assign set_pending = (~status_pending) & EDGE_SENS_LAND_Outp_s;


endmodule

