/* ===============================================================
Copyright 2026, Infineon Technologies AG or an 
affiliate of Infineon Technologies AG.  All rights reserved.
 
This software, associated documentation and materials ("Software") is owned by
Infineon Technologies AG or one of its affiliates ("Infineon") and is 
protected by and subject to worldwide patent protection (United States and 
foreign), United States copyright laws and international treaty provisions. 
Therefore, you may use this Software only as provided in the license agreement
accompanying the software package from which you obtained this 
Software ("EULA"). If no EULA applies, then any reproduction, modification, 
translation, compilation, or representation of this Software is prohibited 
without the express written permission of Infineon.
 
Disclaimer: THIS SOFTWARE IS PROVIDED AS-IS, WITH NO WARRANTY OF 
ANY KIND, EXPRESS OR IMPLIED, INCLUDING, BUT NOT LIMITED TO, 
NONINFRINGEMENT, IMPLIED WARRANTIES OF  MERCHANTABILITY AND
FITNESS FOR A PARTICULAR PURPOSE.  Infineon reserves the right to make
changes to the Software without notice. Infineon does not assume any liability
arising out of the application or use of the Software or any product or 
circuit described in the Software. Infineon does not authorize its products 
for use in any products where a malfunction or failure of the Infineon product 
may reasonably be expected to result in significant property damage, injury or
death ("High Risk Product").  By including Infineon 's product in a High Risk 
Product, the manufacturer of such system or application assumes all risk of 
such use and in doing so agrees to indemnify Infineon against all liability.

 ===============================================================
*/ 
// File : InterruptController_ICcomponent_EU_IF.sv 
// Author : tahiraga 
// Date : 18:22:20    21/09/2026 
// Revision :  
// =============================================================== 
// Description : 
/*
---- Auto Generated by MetaRTL , a MetaGen application
---- Contact: ParitoshKumar.Sinha@infineon.com
---- Contact: Yash.Ranjan@infineon.com
===============================================================
*/


module InterruptController_ICcomponent_EU_IF (
    input int_ended,
    input intr_ACK,
    output intr_REQ,
    input nmi_ended,
    input nmi_intr_ACK,
    output nmi_intr_REQ,
    input NMI_active_status,
    input NMI_requested_status,
    input NMI_paused_status,
    input NMI_highest_prio,
    output NMI_active_clr,
    output NMI_requested_clr,
    output NMI_paused_clr,
    output NMI_active_set,
    output NMI_requested_set,
    output NMI_paused_set,
    input int_1_active_status,
    input int_1_requested_status,
    input int_1_paused_status,
    input int_1_highest_prio,
    output int_1_active_clr,
    output int_1_requested_clr,
    output int_1_paused_clr,
    output int_1_active_set,
    output int_1_requested_set,
    output int_1_paused_set,
    input int_4_active_status,
    input int_4_requested_status,
    input int_4_paused_status,
    input int_4_highest_prio,
    output int_4_active_clr,
    output int_4_requested_clr,
    output int_4_paused_clr,
    output int_4_active_set,
    output int_4_requested_set,
    output int_4_paused_set,
    input int_7_active_status,
    input int_7_requested_status,
    input int_7_paused_status,
    input int_7_highest_prio,
    output int_7_active_clr,
    output int_7_requested_clr,
    output int_7_paused_clr,
    output int_7_active_set,
    output int_7_requested_set,
    output int_7_paused_set,
    input int_11_active_status,
    input int_11_requested_status,
    input int_11_paused_status,
    input int_11_highest_prio,
    output int_11_active_clr,
    output int_11_requested_clr,
    output int_11_paused_clr,
    output int_11_active_set,
    output int_11_requested_set,
    output int_11_paused_set,
    input int_15_active_status,
    input int_15_requested_status,
    input int_15_paused_status,
    input int_15_highest_prio,
    output int_15_active_clr,
    output int_15_requested_clr,
    output int_15_paused_clr,
    output int_15_active_set,
    output int_15_requested_set,
    output int_15_paused_set,
    input int_19_active_status,
    input int_19_requested_status,
    input int_19_paused_status,
    input int_19_highest_prio,
    output int_19_active_clr,
    output int_19_requested_clr,
    output int_19_paused_clr,
    output int_19_active_set,
    output int_19_requested_set,
    output int_19_paused_set,
    input int_21_active_status,
    input int_21_requested_status,
    input int_21_paused_status,
    input int_21_highest_prio,
    output int_21_active_clr,
    output int_21_requested_clr,
    output int_21_paused_clr,
    output int_21_active_set,
    output int_21_requested_set,
    output int_21_paused_set,
    input int_28_active_status,
    input int_28_requested_status,
    input int_28_paused_status,
    input int_28_highest_prio,
    output int_28_active_clr,
    output int_28_requested_clr,
    output int_28_paused_clr,
    output int_28_active_set,
    output int_28_requested_set,
    output int_28_paused_set,
    input int_5_active_status,
    input int_5_requested_status,
    input int_5_paused_status,
    input int_5_highest_prio,
    output int_5_active_clr,
    output int_5_requested_clr,
    output int_5_paused_clr,
    output int_5_active_set,
    output int_5_requested_set,
    output int_5_paused_set,
    input int_8_active_status,
    input int_8_requested_status,
    input int_8_paused_status,
    input int_8_highest_prio,
    output int_8_active_clr,
    output int_8_requested_clr,
    output int_8_paused_clr,
    output int_8_active_set,
    output int_8_requested_set,
    output int_8_paused_set,
    input int_12_active_status,
    input int_12_requested_status,
    input int_12_paused_status,
    input int_12_highest_prio,
    output int_12_active_clr,
    output int_12_requested_clr,
    output int_12_paused_clr,
    output int_12_active_set,
    output int_12_requested_set,
    output int_12_paused_set,
    input int_16_active_status,
    input int_16_requested_status,
    input int_16_paused_status,
    input int_16_highest_prio,
    output int_16_active_clr,
    output int_16_requested_clr,
    output int_16_paused_clr,
    output int_16_active_set,
    output int_16_requested_set,
    output int_16_paused_set,
    input int_22_active_status,
    input int_22_requested_status,
    input int_22_paused_status,
    input int_22_highest_prio,
    output int_22_active_clr,
    output int_22_requested_clr,
    output int_22_paused_clr,
    output int_22_active_set,
    output int_22_requested_set,
    output int_22_paused_set,
    input int_25_active_status,
    input int_25_requested_status,
    input int_25_paused_status,
    input int_25_highest_prio,
    output int_25_active_clr,
    output int_25_requested_clr,
    output int_25_paused_clr,
    output int_25_active_set,
    output int_25_requested_set,
    output int_25_paused_set,
    input int_29_active_status,
    input int_29_requested_status,
    input int_29_paused_status,
    input int_29_highest_prio,
    output int_29_active_clr,
    output int_29_requested_clr,
    output int_29_paused_clr,
    output int_29_active_set,
    output int_29_requested_set,
    output int_29_paused_set,
    input int_30_active_status,
    input int_30_requested_status,
    input int_30_paused_status,
    input int_30_highest_prio,
    output int_30_active_clr,
    output int_30_requested_clr,
    output int_30_paused_clr,
    output int_30_active_set,
    output int_30_requested_set,
    output int_30_paused_set,
    input int_2_active_status,
    input int_2_requested_status,
    input int_2_paused_status,
    input int_2_highest_prio,
    output int_2_active_clr,
    output int_2_requested_clr,
    output int_2_paused_clr,
    output int_2_active_set,
    output int_2_requested_set,
    output int_2_paused_set,
    input int_9_active_status,
    input int_9_requested_status,
    input int_9_paused_status,
    input int_9_highest_prio,
    output int_9_active_clr,
    output int_9_requested_clr,
    output int_9_paused_clr,
    output int_9_active_set,
    output int_9_requested_set,
    output int_9_paused_set,
    input int_13_active_status,
    input int_13_requested_status,
    input int_13_paused_status,
    input int_13_highest_prio,
    output int_13_active_clr,
    output int_13_requested_clr,
    output int_13_paused_clr,
    output int_13_active_set,
    output int_13_requested_set,
    output int_13_paused_set,
    input int_17_active_status,
    input int_17_requested_status,
    input int_17_paused_status,
    input int_17_highest_prio,
    output int_17_active_clr,
    output int_17_requested_clr,
    output int_17_paused_clr,
    output int_17_active_set,
    output int_17_requested_set,
    output int_17_paused_set,
    input int_20_active_status,
    input int_20_requested_status,
    input int_20_paused_status,
    input int_20_highest_prio,
    output int_20_active_clr,
    output int_20_requested_clr,
    output int_20_paused_clr,
    output int_20_active_set,
    output int_20_requested_set,
    output int_20_paused_set,
    input int_23_active_status,
    input int_23_requested_status,
    input int_23_paused_status,
    input int_23_highest_prio,
    output int_23_active_clr,
    output int_23_requested_clr,
    output int_23_paused_clr,
    output int_23_active_set,
    output int_23_requested_set,
    output int_23_paused_set,
    input int_26_active_status,
    input int_26_requested_status,
    input int_26_paused_status,
    input int_26_highest_prio,
    output int_26_active_clr,
    output int_26_requested_clr,
    output int_26_paused_clr,
    output int_26_active_set,
    output int_26_requested_set,
    output int_26_paused_set,
    input int_31_active_status,
    input int_31_requested_status,
    input int_31_paused_status,
    input int_31_highest_prio,
    output int_31_active_clr,
    output int_31_requested_clr,
    output int_31_paused_clr,
    output int_31_active_set,
    output int_31_requested_set,
    output int_31_paused_set,
    input int_0_active_status,
    input int_0_requested_status,
    input int_0_paused_status,
    input int_0_highest_prio,
    output int_0_active_clr,
    output int_0_requested_clr,
    output int_0_paused_clr,
    output int_0_active_set,
    output int_0_requested_set,
    output int_0_paused_set,
    input int_3_active_status,
    input int_3_requested_status,
    input int_3_paused_status,
    input int_3_highest_prio,
    output int_3_active_clr,
    output int_3_requested_clr,
    output int_3_paused_clr,
    output int_3_active_set,
    output int_3_requested_set,
    output int_3_paused_set,
    input int_6_active_status,
    input int_6_requested_status,
    input int_6_paused_status,
    input int_6_highest_prio,
    output int_6_active_clr,
    output int_6_requested_clr,
    output int_6_paused_clr,
    output int_6_active_set,
    output int_6_requested_set,
    output int_6_paused_set,
    input int_10_active_status,
    input int_10_requested_status,
    input int_10_paused_status,
    input int_10_highest_prio,
    output int_10_active_clr,
    output int_10_requested_clr,
    output int_10_paused_clr,
    output int_10_active_set,
    output int_10_requested_set,
    output int_10_paused_set,
    input int_14_active_status,
    input int_14_requested_status,
    input int_14_paused_status,
    input int_14_highest_prio,
    output int_14_active_clr,
    output int_14_requested_clr,
    output int_14_paused_clr,
    output int_14_active_set,
    output int_14_requested_set,
    output int_14_paused_set,
    input int_18_active_status,
    input int_18_requested_status,
    input int_18_paused_status,
    input int_18_highest_prio,
    output int_18_active_clr,
    output int_18_requested_clr,
    output int_18_paused_clr,
    output int_18_active_set,
    output int_18_requested_set,
    output int_18_paused_set,
    input int_24_active_status,
    input int_24_requested_status,
    input int_24_paused_status,
    input int_24_highest_prio,
    output int_24_active_clr,
    output int_24_requested_clr,
    output int_24_paused_clr,
    output int_24_active_set,
    output int_24_requested_set,
    output int_24_paused_set,
    input int_27_active_status,
    input int_27_requested_status,
    input int_27_paused_status,
    input int_27_highest_prio,
    output int_27_active_clr,
    output int_27_requested_clr,
    output int_27_paused_clr,
    output int_27_active_set,
    output int_27_requested_set,
    output int_27_paused_set
);

logic   trans_paus_to_act_int_27_Outp_s;
logic   trans_act_to_idle_int_27_Outp_s;
logic   trans_act_to_paus_int_27_Outp_s;
logic   trans_paus_to_act_int_24_Outp_s;
logic   trans_act_to_idle_int_24_Outp_s;
logic   trans_act_to_paus_int_24_Outp_s;
logic   trans_paus_to_act_int_18_Outp_s;
logic   trans_act_to_idle_int_18_Outp_s;
logic   trans_act_to_paus_int_18_Outp_s;
logic   trans_paus_to_act_int_14_Outp_s;
logic   trans_act_to_idle_int_14_Outp_s;
logic   trans_act_to_paus_int_14_Outp_s;
logic   trans_paus_to_act_int_10_Outp_s;
logic   trans_act_to_idle_int_10_Outp_s;
logic   trans_act_to_paus_int_10_Outp_s;
logic   trans_paus_to_act_int_6_Outp_s;
logic   trans_act_to_idle_int_6_Outp_s;
logic   trans_act_to_paus_int_6_Outp_s;
logic   trans_paus_to_act_int_3_Outp_s;
logic   trans_act_to_idle_int_3_Outp_s;
logic   trans_act_to_paus_int_3_Outp_s;
logic   trans_paus_to_act_int_0_Outp_s;
logic   trans_act_to_idle_int_0_Outp_s;
logic   trans_act_to_paus_int_0_Outp_s;
logic   trans_paus_to_act_int_31_Outp_s;
logic   trans_act_to_idle_int_31_Outp_s;
logic   trans_act_to_paus_int_31_Outp_s;
logic   trans_paus_to_act_int_26_Outp_s;
logic   trans_act_to_idle_int_26_Outp_s;
logic   trans_act_to_paus_int_26_Outp_s;
logic   trans_paus_to_act_int_23_Outp_s;
logic   trans_act_to_idle_int_23_Outp_s;
logic   trans_act_to_paus_int_23_Outp_s;
logic   trans_paus_to_act_int_20_Outp_s;
logic   trans_act_to_idle_int_20_Outp_s;
logic   trans_act_to_paus_int_20_Outp_s;
logic   trans_paus_to_act_int_17_Outp_s;
logic   trans_act_to_idle_int_17_Outp_s;
logic   trans_act_to_paus_int_17_Outp_s;
logic   trans_paus_to_act_int_13_Outp_s;
logic   trans_act_to_idle_int_13_Outp_s;
logic   trans_act_to_paus_int_13_Outp_s;
logic   trans_paus_to_act_int_9_Outp_s;
logic   trans_act_to_idle_int_9_Outp_s;
logic   trans_act_to_paus_int_9_Outp_s;
logic   trans_paus_to_act_int_2_Outp_s;
logic   trans_act_to_idle_int_2_Outp_s;
logic   trans_act_to_paus_int_2_Outp_s;
logic   trans_paus_to_act_int_30_Outp_s;
logic   trans_act_to_idle_int_30_Outp_s;
logic   trans_act_to_paus_int_30_Outp_s;
logic   trans_paus_to_act_int_29_Outp_s;
logic   trans_act_to_idle_int_29_Outp_s;
logic   trans_act_to_paus_int_29_Outp_s;
logic   trans_paus_to_act_int_25_Outp_s;
logic   trans_act_to_idle_int_25_Outp_s;
logic   trans_act_to_paus_int_25_Outp_s;
logic   trans_paus_to_act_int_22_Outp_s;
logic   trans_act_to_idle_int_22_Outp_s;
logic   trans_act_to_paus_int_22_Outp_s;
logic   trans_paus_to_act_int_16_Outp_s;
logic   trans_act_to_idle_int_16_Outp_s;
logic   trans_act_to_paus_int_16_Outp_s;
logic   trans_paus_to_act_int_12_Outp_s;
logic   trans_act_to_idle_int_12_Outp_s;
logic   trans_act_to_paus_int_12_Outp_s;
logic   trans_paus_to_act_int_8_Outp_s;
logic   trans_act_to_idle_int_8_Outp_s;
logic   trans_act_to_paus_int_8_Outp_s;
logic   trans_paus_to_act_int_5_Outp_s;
logic   trans_act_to_idle_int_5_Outp_s;
logic   trans_act_to_paus_int_5_Outp_s;
logic   trans_paus_to_act_int_28_Outp_s;
logic   trans_act_to_idle_int_28_Outp_s;
logic   trans_act_to_paus_int_28_Outp_s;
logic   trans_paus_to_act_int_21_Outp_s;
logic   trans_act_to_idle_int_21_Outp_s;
logic   trans_act_to_paus_int_21_Outp_s;
logic   trans_paus_to_act_int_19_Outp_s;
logic   trans_act_to_idle_int_19_Outp_s;
logic   trans_act_to_paus_int_19_Outp_s;
logic   trans_paus_to_act_int_15_Outp_s;
logic   trans_act_to_idle_int_15_Outp_s;
logic   trans_act_to_paus_int_15_Outp_s;
logic   trans_paus_to_act_int_11_Outp_s;
logic   trans_act_to_idle_int_11_Outp_s;
logic   trans_act_to_paus_int_11_Outp_s;
logic   trans_paus_to_act_int_7_Outp_s;
logic   trans_act_to_idle_int_7_Outp_s;
logic   trans_act_to_paus_int_7_Outp_s;
logic   trans_paus_to_act_int_4_Outp_s;
logic   trans_act_to_idle_int_4_Outp_s;
logic   trans_act_to_paus_int_4_Outp_s;
logic   trans_paus_to_act_int_1_Outp_s;
logic   trans_act_to_idle_int_1_Outp_s;
logic   trans_act_to_paus_int_1_Outp_s;
logic   trans_paus_to_act_NMI_Outp_s;
logic   int_returned_Outp_s;
logic   int_acknwoledged_Outp_s;
logic   trans_act_to_idle_NMI_Outp_s;
logic   trans_act_to_paus_NMI_Outp_s;
logic   trans_pend_to_req_NMI_Outp_s;
logic   any_in_request_Outp_s;
logic   trans_pend_to_req_int_27_Outp_s;
logic   trans_pend_to_req_int_24_Outp_s;
logic   trans_pend_to_req_int_18_Outp_s;
logic   trans_pend_to_req_int_14_Outp_s;
logic   trans_pend_to_req_int_10_Outp_s;
logic   trans_pend_to_req_int_6_Outp_s;
logic   trans_pend_to_req_int_3_Outp_s;
logic   trans_pend_to_req_int_0_Outp_s;
logic   trans_pend_to_req_int_31_Outp_s;
logic   trans_pend_to_req_int_26_Outp_s;
logic   trans_pend_to_req_int_23_Outp_s;
logic   trans_pend_to_req_int_20_Outp_s;
logic   trans_pend_to_req_int_17_Outp_s;
logic   trans_pend_to_req_int_13_Outp_s;
logic   trans_pend_to_req_int_9_Outp_s;
logic   trans_pend_to_req_int_2_Outp_s;
logic   trans_pend_to_req_int_30_Outp_s;
logic   trans_pend_to_req_int_29_Outp_s;
logic   trans_pend_to_req_int_25_Outp_s;
logic   trans_pend_to_req_int_22_Outp_s;
logic   trans_pend_to_req_int_16_Outp_s;
logic   trans_pend_to_req_int_12_Outp_s;
logic   trans_pend_to_req_int_8_Outp_s;
logic   trans_pend_to_req_int_5_Outp_s;
logic   trans_pend_to_req_int_28_Outp_s;
logic   trans_pend_to_req_int_21_Outp_s;
logic   trans_pend_to_req_int_19_Outp_s;
logic   trans_pend_to_req_int_15_Outp_s;
logic   trans_pend_to_req_int_11_Outp_s;
logic   trans_pend_to_req_int_7_Outp_s;
logic   trans_pend_to_req_int_4_Outp_s;
logic   trans_pend_to_req_int_1_Outp_s;

assign int_27_active_set = (int_27_requested_status & (~int_27_active_status) & (~int_27_paused_status) & int_acknwoledged_Outp_s) | trans_paus_to_act_int_27_Outp_s;

assign trans_paus_to_act_int_27_Outp_s = int_27_paused_status & int_27_highest_prio & int_returned_Outp_s;
assign int_27_paused_clr = trans_paus_to_act_int_27_Outp_s;

assign trans_act_to_idle_int_27_Outp_s = int_27_active_status & int_returned_Outp_s;
assign int_27_requested_clr = trans_act_to_idle_int_27_Outp_s;

assign trans_act_to_paus_int_27_Outp_s = int_27_active_status & int_acknwoledged_Outp_s;
assign int_27_paused_set = trans_act_to_paus_int_27_Outp_s;

assign int_27_active_clr = trans_act_to_paus_int_27_Outp_s | trans_act_to_idle_int_27_Outp_s;

assign int_24_active_set = (int_24_requested_status & (~int_24_active_status) & (~int_24_paused_status) & int_acknwoledged_Outp_s) | trans_paus_to_act_int_24_Outp_s;

assign trans_paus_to_act_int_24_Outp_s = int_24_paused_status & int_24_highest_prio & int_returned_Outp_s;
assign int_24_paused_clr = trans_paus_to_act_int_24_Outp_s;

assign trans_act_to_idle_int_24_Outp_s = int_24_active_status & int_returned_Outp_s;
assign int_24_requested_clr = trans_act_to_idle_int_24_Outp_s;

assign trans_act_to_paus_int_24_Outp_s = int_24_active_status & int_acknwoledged_Outp_s;
assign int_24_paused_set = trans_act_to_paus_int_24_Outp_s;

assign int_24_active_clr = trans_act_to_paus_int_24_Outp_s | trans_act_to_idle_int_24_Outp_s;

assign int_18_active_set = (int_18_requested_status & (~int_18_active_status) & (~int_18_paused_status) & int_acknwoledged_Outp_s) | trans_paus_to_act_int_18_Outp_s;

assign trans_paus_to_act_int_18_Outp_s = int_18_paused_status & int_18_highest_prio & int_returned_Outp_s;
assign int_18_paused_clr = trans_paus_to_act_int_18_Outp_s;

assign trans_act_to_idle_int_18_Outp_s = int_18_active_status & int_returned_Outp_s;
assign int_18_requested_clr = trans_act_to_idle_int_18_Outp_s;

assign trans_act_to_paus_int_18_Outp_s = int_18_active_status & int_acknwoledged_Outp_s;
assign int_18_paused_set = trans_act_to_paus_int_18_Outp_s;

assign int_18_active_clr = trans_act_to_paus_int_18_Outp_s | trans_act_to_idle_int_18_Outp_s;

assign int_14_active_set = (int_14_requested_status & (~int_14_active_status) & (~int_14_paused_status) & int_acknwoledged_Outp_s) | trans_paus_to_act_int_14_Outp_s;

assign trans_paus_to_act_int_14_Outp_s = int_14_paused_status & int_14_highest_prio & int_returned_Outp_s;
assign int_14_paused_clr = trans_paus_to_act_int_14_Outp_s;

assign trans_act_to_idle_int_14_Outp_s = int_14_active_status & int_returned_Outp_s;
assign int_14_requested_clr = trans_act_to_idle_int_14_Outp_s;

assign trans_act_to_paus_int_14_Outp_s = int_14_active_status & int_acknwoledged_Outp_s;
assign int_14_paused_set = trans_act_to_paus_int_14_Outp_s;

assign int_14_active_clr = trans_act_to_paus_int_14_Outp_s | trans_act_to_idle_int_14_Outp_s;

assign int_10_active_set = (int_10_requested_status & (~int_10_active_status) & (~int_10_paused_status) & int_acknwoledged_Outp_s) | trans_paus_to_act_int_10_Outp_s;

assign trans_paus_to_act_int_10_Outp_s = int_10_paused_status & int_10_highest_prio & int_returned_Outp_s;
assign int_10_paused_clr = trans_paus_to_act_int_10_Outp_s;

assign trans_act_to_idle_int_10_Outp_s = int_10_active_status & int_returned_Outp_s;
assign int_10_requested_clr = trans_act_to_idle_int_10_Outp_s;

assign trans_act_to_paus_int_10_Outp_s = int_10_active_status & int_acknwoledged_Outp_s;
assign int_10_paused_set = trans_act_to_paus_int_10_Outp_s;

assign int_10_active_clr = trans_act_to_paus_int_10_Outp_s | trans_act_to_idle_int_10_Outp_s;

assign int_6_active_set = (int_6_requested_status & (~int_6_active_status) & (~int_6_paused_status) & int_acknwoledged_Outp_s) | trans_paus_to_act_int_6_Outp_s;

assign trans_paus_to_act_int_6_Outp_s = int_6_paused_status & int_6_highest_prio & int_returned_Outp_s;
assign int_6_paused_clr = trans_paus_to_act_int_6_Outp_s;

assign trans_act_to_idle_int_6_Outp_s = int_6_active_status & int_returned_Outp_s;
assign int_6_requested_clr = trans_act_to_idle_int_6_Outp_s;

assign trans_act_to_paus_int_6_Outp_s = int_6_active_status & int_acknwoledged_Outp_s;
assign int_6_paused_set = trans_act_to_paus_int_6_Outp_s;

assign int_6_active_clr = trans_act_to_paus_int_6_Outp_s | trans_act_to_idle_int_6_Outp_s;

assign int_3_active_set = (int_3_requested_status & (~int_3_active_status) & (~int_3_paused_status) & int_acknwoledged_Outp_s) | trans_paus_to_act_int_3_Outp_s;

assign trans_paus_to_act_int_3_Outp_s = int_3_paused_status & int_3_highest_prio & int_returned_Outp_s;
assign int_3_paused_clr = trans_paus_to_act_int_3_Outp_s;

assign trans_act_to_idle_int_3_Outp_s = int_3_active_status & int_returned_Outp_s;
assign int_3_requested_clr = trans_act_to_idle_int_3_Outp_s;

assign trans_act_to_paus_int_3_Outp_s = int_3_active_status & int_acknwoledged_Outp_s;
assign int_3_paused_set = trans_act_to_paus_int_3_Outp_s;

assign int_3_active_clr = trans_act_to_paus_int_3_Outp_s | trans_act_to_idle_int_3_Outp_s;

assign int_0_active_set = (int_0_requested_status & (~int_0_active_status) & (~int_0_paused_status) & int_acknwoledged_Outp_s) | trans_paus_to_act_int_0_Outp_s;

assign trans_paus_to_act_int_0_Outp_s = int_0_paused_status & int_0_highest_prio & int_returned_Outp_s;
assign int_0_paused_clr = trans_paus_to_act_int_0_Outp_s;

assign trans_act_to_idle_int_0_Outp_s = int_0_active_status & int_returned_Outp_s;
assign int_0_requested_clr = trans_act_to_idle_int_0_Outp_s;

assign trans_act_to_paus_int_0_Outp_s = int_0_active_status & int_acknwoledged_Outp_s;
assign int_0_paused_set = trans_act_to_paus_int_0_Outp_s;

assign int_0_active_clr = trans_act_to_paus_int_0_Outp_s | trans_act_to_idle_int_0_Outp_s;

assign int_31_active_set = (int_31_requested_status & (~int_31_active_status) & (~int_31_paused_status) & int_acknwoledged_Outp_s) | trans_paus_to_act_int_31_Outp_s;

assign trans_paus_to_act_int_31_Outp_s = int_31_paused_status & int_31_highest_prio & int_returned_Outp_s;
assign int_31_paused_clr = trans_paus_to_act_int_31_Outp_s;

assign trans_act_to_idle_int_31_Outp_s = int_31_active_status & int_returned_Outp_s;
assign int_31_requested_clr = trans_act_to_idle_int_31_Outp_s;

assign trans_act_to_paus_int_31_Outp_s = int_31_active_status & int_acknwoledged_Outp_s;
assign int_31_paused_set = trans_act_to_paus_int_31_Outp_s;

assign int_31_active_clr = trans_act_to_paus_int_31_Outp_s | trans_act_to_idle_int_31_Outp_s;

assign int_26_active_set = (int_26_requested_status & (~int_26_active_status) & (~int_26_paused_status) & int_acknwoledged_Outp_s) | trans_paus_to_act_int_26_Outp_s;

assign trans_paus_to_act_int_26_Outp_s = int_26_paused_status & int_26_highest_prio & int_returned_Outp_s;
assign int_26_paused_clr = trans_paus_to_act_int_26_Outp_s;

assign trans_act_to_idle_int_26_Outp_s = int_26_active_status & int_returned_Outp_s;
assign int_26_requested_clr = trans_act_to_idle_int_26_Outp_s;

assign trans_act_to_paus_int_26_Outp_s = int_26_active_status & int_acknwoledged_Outp_s;
assign int_26_paused_set = trans_act_to_paus_int_26_Outp_s;

assign int_26_active_clr = trans_act_to_paus_int_26_Outp_s | trans_act_to_idle_int_26_Outp_s;

assign int_23_active_set = (int_23_requested_status & (~int_23_active_status) & (~int_23_paused_status) & int_acknwoledged_Outp_s) | trans_paus_to_act_int_23_Outp_s;

assign trans_paus_to_act_int_23_Outp_s = int_23_paused_status & int_23_highest_prio & int_returned_Outp_s;
assign int_23_paused_clr = trans_paus_to_act_int_23_Outp_s;

assign trans_act_to_idle_int_23_Outp_s = int_23_active_status & int_returned_Outp_s;
assign int_23_requested_clr = trans_act_to_idle_int_23_Outp_s;

assign trans_act_to_paus_int_23_Outp_s = int_23_active_status & int_acknwoledged_Outp_s;
assign int_23_paused_set = trans_act_to_paus_int_23_Outp_s;

assign int_23_active_clr = trans_act_to_paus_int_23_Outp_s | trans_act_to_idle_int_23_Outp_s;

assign int_20_active_set = (int_20_requested_status & (~int_20_active_status) & (~int_20_paused_status) & int_acknwoledged_Outp_s) | trans_paus_to_act_int_20_Outp_s;

assign trans_paus_to_act_int_20_Outp_s = int_20_paused_status & int_20_highest_prio & int_returned_Outp_s;
assign int_20_paused_clr = trans_paus_to_act_int_20_Outp_s;

assign trans_act_to_idle_int_20_Outp_s = int_20_active_status & int_returned_Outp_s;
assign int_20_requested_clr = trans_act_to_idle_int_20_Outp_s;

assign trans_act_to_paus_int_20_Outp_s = int_20_active_status & int_acknwoledged_Outp_s;
assign int_20_paused_set = trans_act_to_paus_int_20_Outp_s;

assign int_20_active_clr = trans_act_to_paus_int_20_Outp_s | trans_act_to_idle_int_20_Outp_s;

assign int_17_active_set = (int_17_requested_status & (~int_17_active_status) & (~int_17_paused_status) & int_acknwoledged_Outp_s) | trans_paus_to_act_int_17_Outp_s;

assign trans_paus_to_act_int_17_Outp_s = int_17_paused_status & int_17_highest_prio & int_returned_Outp_s;
assign int_17_paused_clr = trans_paus_to_act_int_17_Outp_s;

assign trans_act_to_idle_int_17_Outp_s = int_17_active_status & int_returned_Outp_s;
assign int_17_requested_clr = trans_act_to_idle_int_17_Outp_s;

assign trans_act_to_paus_int_17_Outp_s = int_17_active_status & int_acknwoledged_Outp_s;
assign int_17_paused_set = trans_act_to_paus_int_17_Outp_s;

assign int_17_active_clr = trans_act_to_paus_int_17_Outp_s | trans_act_to_idle_int_17_Outp_s;

assign int_13_active_set = (int_13_requested_status & (~int_13_active_status) & (~int_13_paused_status) & int_acknwoledged_Outp_s) | trans_paus_to_act_int_13_Outp_s;

assign trans_paus_to_act_int_13_Outp_s = int_13_paused_status & int_13_highest_prio & int_returned_Outp_s;
assign int_13_paused_clr = trans_paus_to_act_int_13_Outp_s;

assign trans_act_to_idle_int_13_Outp_s = int_13_active_status & int_returned_Outp_s;
assign int_13_requested_clr = trans_act_to_idle_int_13_Outp_s;

assign trans_act_to_paus_int_13_Outp_s = int_13_active_status & int_acknwoledged_Outp_s;
assign int_13_paused_set = trans_act_to_paus_int_13_Outp_s;

assign int_13_active_clr = trans_act_to_paus_int_13_Outp_s | trans_act_to_idle_int_13_Outp_s;

assign int_9_active_set = (int_9_requested_status & (~int_9_active_status) & (~int_9_paused_status) & int_acknwoledged_Outp_s) | trans_paus_to_act_int_9_Outp_s;

assign trans_paus_to_act_int_9_Outp_s = int_9_paused_status & int_9_highest_prio & int_returned_Outp_s;
assign int_9_paused_clr = trans_paus_to_act_int_9_Outp_s;

assign trans_act_to_idle_int_9_Outp_s = int_9_active_status & int_returned_Outp_s;
assign int_9_requested_clr = trans_act_to_idle_int_9_Outp_s;

assign trans_act_to_paus_int_9_Outp_s = int_9_active_status & int_acknwoledged_Outp_s;
assign int_9_paused_set = trans_act_to_paus_int_9_Outp_s;

assign int_9_active_clr = trans_act_to_paus_int_9_Outp_s | trans_act_to_idle_int_9_Outp_s;

assign int_2_active_set = (int_2_requested_status & (~int_2_active_status) & (~int_2_paused_status) & int_acknwoledged_Outp_s) | trans_paus_to_act_int_2_Outp_s;

assign trans_paus_to_act_int_2_Outp_s = int_2_paused_status & int_2_highest_prio & int_returned_Outp_s;
assign int_2_paused_clr = trans_paus_to_act_int_2_Outp_s;

assign trans_act_to_idle_int_2_Outp_s = int_2_active_status & int_returned_Outp_s;
assign int_2_requested_clr = trans_act_to_idle_int_2_Outp_s;

assign trans_act_to_paus_int_2_Outp_s = int_2_active_status & int_acknwoledged_Outp_s;
assign int_2_paused_set = trans_act_to_paus_int_2_Outp_s;

assign int_2_active_clr = trans_act_to_paus_int_2_Outp_s | trans_act_to_idle_int_2_Outp_s;

assign int_30_active_set = (int_30_requested_status & (~int_30_active_status) & (~int_30_paused_status) & int_acknwoledged_Outp_s) | trans_paus_to_act_int_30_Outp_s;

assign trans_paus_to_act_int_30_Outp_s = int_30_paused_status & int_30_highest_prio & int_returned_Outp_s;
assign int_30_paused_clr = trans_paus_to_act_int_30_Outp_s;

assign trans_act_to_idle_int_30_Outp_s = int_30_active_status & int_returned_Outp_s;
assign int_30_requested_clr = trans_act_to_idle_int_30_Outp_s;

assign trans_act_to_paus_int_30_Outp_s = int_30_active_status & int_acknwoledged_Outp_s;
assign int_30_paused_set = trans_act_to_paus_int_30_Outp_s;

assign int_30_active_clr = trans_act_to_paus_int_30_Outp_s | trans_act_to_idle_int_30_Outp_s;

assign int_29_active_set = (int_29_requested_status & (~int_29_active_status) & (~int_29_paused_status) & int_acknwoledged_Outp_s) | trans_paus_to_act_int_29_Outp_s;

assign trans_paus_to_act_int_29_Outp_s = int_29_paused_status & int_29_highest_prio & int_returned_Outp_s;
assign int_29_paused_clr = trans_paus_to_act_int_29_Outp_s;

assign trans_act_to_idle_int_29_Outp_s = int_29_active_status & int_returned_Outp_s;
assign int_29_requested_clr = trans_act_to_idle_int_29_Outp_s;

assign trans_act_to_paus_int_29_Outp_s = int_29_active_status & int_acknwoledged_Outp_s;
assign int_29_paused_set = trans_act_to_paus_int_29_Outp_s;

assign int_29_active_clr = trans_act_to_paus_int_29_Outp_s | trans_act_to_idle_int_29_Outp_s;

assign int_25_active_set = (int_25_requested_status & (~int_25_active_status) & (~int_25_paused_status) & int_acknwoledged_Outp_s) | trans_paus_to_act_int_25_Outp_s;

assign trans_paus_to_act_int_25_Outp_s = int_25_paused_status & int_25_highest_prio & int_returned_Outp_s;
assign int_25_paused_clr = trans_paus_to_act_int_25_Outp_s;

assign trans_act_to_idle_int_25_Outp_s = int_25_active_status & int_returned_Outp_s;
assign int_25_requested_clr = trans_act_to_idle_int_25_Outp_s;

assign trans_act_to_paus_int_25_Outp_s = int_25_active_status & int_acknwoledged_Outp_s;
assign int_25_paused_set = trans_act_to_paus_int_25_Outp_s;

assign int_25_active_clr = trans_act_to_paus_int_25_Outp_s | trans_act_to_idle_int_25_Outp_s;

assign int_22_active_set = (int_22_requested_status & (~int_22_active_status) & (~int_22_paused_status) & int_acknwoledged_Outp_s) | trans_paus_to_act_int_22_Outp_s;

assign trans_paus_to_act_int_22_Outp_s = int_22_paused_status & int_22_highest_prio & int_returned_Outp_s;
assign int_22_paused_clr = trans_paus_to_act_int_22_Outp_s;

assign trans_act_to_idle_int_22_Outp_s = int_22_active_status & int_returned_Outp_s;
assign int_22_requested_clr = trans_act_to_idle_int_22_Outp_s;

assign trans_act_to_paus_int_22_Outp_s = int_22_active_status & int_acknwoledged_Outp_s;
assign int_22_paused_set = trans_act_to_paus_int_22_Outp_s;

assign int_22_active_clr = trans_act_to_paus_int_22_Outp_s | trans_act_to_idle_int_22_Outp_s;

assign int_16_active_set = (int_16_requested_status & (~int_16_active_status) & (~int_16_paused_status) & int_acknwoledged_Outp_s) | trans_paus_to_act_int_16_Outp_s;

assign trans_paus_to_act_int_16_Outp_s = int_16_paused_status & int_16_highest_prio & int_returned_Outp_s;
assign int_16_paused_clr = trans_paus_to_act_int_16_Outp_s;

assign trans_act_to_idle_int_16_Outp_s = int_16_active_status & int_returned_Outp_s;
assign int_16_requested_clr = trans_act_to_idle_int_16_Outp_s;

assign trans_act_to_paus_int_16_Outp_s = int_16_active_status & int_acknwoledged_Outp_s;
assign int_16_paused_set = trans_act_to_paus_int_16_Outp_s;

assign int_16_active_clr = trans_act_to_paus_int_16_Outp_s | trans_act_to_idle_int_16_Outp_s;

assign int_12_active_set = (int_12_requested_status & (~int_12_active_status) & (~int_12_paused_status) & int_acknwoledged_Outp_s) | trans_paus_to_act_int_12_Outp_s;

assign trans_paus_to_act_int_12_Outp_s = int_12_paused_status & int_12_highest_prio & int_returned_Outp_s;
assign int_12_paused_clr = trans_paus_to_act_int_12_Outp_s;

assign trans_act_to_idle_int_12_Outp_s = int_12_active_status & int_returned_Outp_s;
assign int_12_requested_clr = trans_act_to_idle_int_12_Outp_s;

assign trans_act_to_paus_int_12_Outp_s = int_12_active_status & int_acknwoledged_Outp_s;
assign int_12_paused_set = trans_act_to_paus_int_12_Outp_s;

assign int_12_active_clr = trans_act_to_paus_int_12_Outp_s | trans_act_to_idle_int_12_Outp_s;

assign int_8_active_set = (int_8_requested_status & (~int_8_active_status) & (~int_8_paused_status) & int_acknwoledged_Outp_s) | trans_paus_to_act_int_8_Outp_s;

assign trans_paus_to_act_int_8_Outp_s = int_8_paused_status & int_8_highest_prio & int_returned_Outp_s;
assign int_8_paused_clr = trans_paus_to_act_int_8_Outp_s;

assign trans_act_to_idle_int_8_Outp_s = int_8_active_status & int_returned_Outp_s;
assign int_8_requested_clr = trans_act_to_idle_int_8_Outp_s;

assign trans_act_to_paus_int_8_Outp_s = int_8_active_status & int_acknwoledged_Outp_s;
assign int_8_paused_set = trans_act_to_paus_int_8_Outp_s;

assign int_8_active_clr = trans_act_to_paus_int_8_Outp_s | trans_act_to_idle_int_8_Outp_s;

assign int_5_active_set = (int_5_requested_status & (~int_5_active_status) & (~int_5_paused_status) & int_acknwoledged_Outp_s) | trans_paus_to_act_int_5_Outp_s;

assign trans_paus_to_act_int_5_Outp_s = int_5_paused_status & int_5_highest_prio & int_returned_Outp_s;
assign int_5_paused_clr = trans_paus_to_act_int_5_Outp_s;

assign trans_act_to_idle_int_5_Outp_s = int_5_active_status & int_returned_Outp_s;
assign int_5_requested_clr = trans_act_to_idle_int_5_Outp_s;

assign trans_act_to_paus_int_5_Outp_s = int_5_active_status & int_acknwoledged_Outp_s;
assign int_5_paused_set = trans_act_to_paus_int_5_Outp_s;

assign int_5_active_clr = trans_act_to_paus_int_5_Outp_s | trans_act_to_idle_int_5_Outp_s;

assign int_28_active_set = (int_28_requested_status & (~int_28_active_status) & (~int_28_paused_status) & int_acknwoledged_Outp_s) | trans_paus_to_act_int_28_Outp_s;

assign trans_paus_to_act_int_28_Outp_s = int_28_paused_status & int_28_highest_prio & int_returned_Outp_s;
assign int_28_paused_clr = trans_paus_to_act_int_28_Outp_s;

assign trans_act_to_idle_int_28_Outp_s = int_28_active_status & int_returned_Outp_s;
assign int_28_requested_clr = trans_act_to_idle_int_28_Outp_s;

assign trans_act_to_paus_int_28_Outp_s = int_28_active_status & int_acknwoledged_Outp_s;
assign int_28_paused_set = trans_act_to_paus_int_28_Outp_s;

assign int_28_active_clr = trans_act_to_paus_int_28_Outp_s | trans_act_to_idle_int_28_Outp_s;

assign int_21_active_set = (int_21_requested_status & (~int_21_active_status) & (~int_21_paused_status) & int_acknwoledged_Outp_s) | trans_paus_to_act_int_21_Outp_s;

assign trans_paus_to_act_int_21_Outp_s = int_21_paused_status & int_21_highest_prio & int_returned_Outp_s;
assign int_21_paused_clr = trans_paus_to_act_int_21_Outp_s;

assign trans_act_to_idle_int_21_Outp_s = int_21_active_status & int_returned_Outp_s;
assign int_21_requested_clr = trans_act_to_idle_int_21_Outp_s;

assign trans_act_to_paus_int_21_Outp_s = int_21_active_status & int_acknwoledged_Outp_s;
assign int_21_paused_set = trans_act_to_paus_int_21_Outp_s;

assign int_21_active_clr = trans_act_to_paus_int_21_Outp_s | trans_act_to_idle_int_21_Outp_s;

assign int_19_active_set = (int_19_requested_status & (~int_19_active_status) & (~int_19_paused_status) & int_acknwoledged_Outp_s) | trans_paus_to_act_int_19_Outp_s;

assign trans_paus_to_act_int_19_Outp_s = int_19_paused_status & int_19_highest_prio & int_returned_Outp_s;
assign int_19_paused_clr = trans_paus_to_act_int_19_Outp_s;

assign trans_act_to_idle_int_19_Outp_s = int_19_active_status & int_returned_Outp_s;
assign int_19_requested_clr = trans_act_to_idle_int_19_Outp_s;

assign trans_act_to_paus_int_19_Outp_s = int_19_active_status & int_acknwoledged_Outp_s;
assign int_19_paused_set = trans_act_to_paus_int_19_Outp_s;

assign int_19_active_clr = trans_act_to_paus_int_19_Outp_s | trans_act_to_idle_int_19_Outp_s;

assign int_15_active_set = (int_15_requested_status & (~int_15_active_status) & (~int_15_paused_status) & int_acknwoledged_Outp_s) | trans_paus_to_act_int_15_Outp_s;

assign trans_paus_to_act_int_15_Outp_s = int_15_paused_status & int_15_highest_prio & int_returned_Outp_s;
assign int_15_paused_clr = trans_paus_to_act_int_15_Outp_s;

assign trans_act_to_idle_int_15_Outp_s = int_15_active_status & int_returned_Outp_s;
assign int_15_requested_clr = trans_act_to_idle_int_15_Outp_s;

assign trans_act_to_paus_int_15_Outp_s = int_15_active_status & int_acknwoledged_Outp_s;
assign int_15_paused_set = trans_act_to_paus_int_15_Outp_s;

assign int_15_active_clr = trans_act_to_paus_int_15_Outp_s | trans_act_to_idle_int_15_Outp_s;

assign int_11_active_set = (int_11_requested_status & (~int_11_active_status) & (~int_11_paused_status) & int_acknwoledged_Outp_s) | trans_paus_to_act_int_11_Outp_s;

assign trans_paus_to_act_int_11_Outp_s = int_11_paused_status & int_11_highest_prio & int_returned_Outp_s;
assign int_11_paused_clr = trans_paus_to_act_int_11_Outp_s;

assign trans_act_to_idle_int_11_Outp_s = int_11_active_status & int_returned_Outp_s;
assign int_11_requested_clr = trans_act_to_idle_int_11_Outp_s;

assign trans_act_to_paus_int_11_Outp_s = int_11_active_status & int_acknwoledged_Outp_s;
assign int_11_paused_set = trans_act_to_paus_int_11_Outp_s;

assign int_11_active_clr = trans_act_to_paus_int_11_Outp_s | trans_act_to_idle_int_11_Outp_s;

assign int_7_active_set = (int_7_requested_status & (~int_7_active_status) & (~int_7_paused_status) & int_acknwoledged_Outp_s) | trans_paus_to_act_int_7_Outp_s;

assign trans_paus_to_act_int_7_Outp_s = int_7_paused_status & int_7_highest_prio & int_returned_Outp_s;
assign int_7_paused_clr = trans_paus_to_act_int_7_Outp_s;

assign trans_act_to_idle_int_7_Outp_s = int_7_active_status & int_returned_Outp_s;
assign int_7_requested_clr = trans_act_to_idle_int_7_Outp_s;

assign trans_act_to_paus_int_7_Outp_s = int_7_active_status & int_acknwoledged_Outp_s;
assign int_7_paused_set = trans_act_to_paus_int_7_Outp_s;

assign int_7_active_clr = trans_act_to_paus_int_7_Outp_s | trans_act_to_idle_int_7_Outp_s;

assign int_4_active_set = (int_4_requested_status & (~int_4_active_status) & (~int_4_paused_status) & int_acknwoledged_Outp_s) | trans_paus_to_act_int_4_Outp_s;

assign trans_paus_to_act_int_4_Outp_s = int_4_paused_status & int_4_highest_prio & int_returned_Outp_s;
assign int_4_paused_clr = trans_paus_to_act_int_4_Outp_s;

assign trans_act_to_idle_int_4_Outp_s = int_4_active_status & int_returned_Outp_s;
assign int_4_requested_clr = trans_act_to_idle_int_4_Outp_s;

assign trans_act_to_paus_int_4_Outp_s = int_4_active_status & int_acknwoledged_Outp_s;
assign int_4_paused_set = trans_act_to_paus_int_4_Outp_s;

assign int_4_active_clr = trans_act_to_paus_int_4_Outp_s | trans_act_to_idle_int_4_Outp_s;

assign int_1_active_set = (int_1_requested_status & (~int_1_active_status) & (~int_1_paused_status) & int_acknwoledged_Outp_s) | trans_paus_to_act_int_1_Outp_s;

assign trans_paus_to_act_int_1_Outp_s = int_1_paused_status & int_1_highest_prio & int_returned_Outp_s;
assign int_1_paused_clr = trans_paus_to_act_int_1_Outp_s;

assign trans_act_to_idle_int_1_Outp_s = int_1_active_status & int_returned_Outp_s;
assign int_1_requested_clr = trans_act_to_idle_int_1_Outp_s;

assign trans_act_to_paus_int_1_Outp_s = int_1_active_status & int_acknwoledged_Outp_s;
assign int_1_paused_set = trans_act_to_paus_int_1_Outp_s;

assign int_1_active_clr = trans_act_to_paus_int_1_Outp_s | trans_act_to_idle_int_1_Outp_s;

assign NMI_active_set = (NMI_requested_status & (~NMI_active_status) & (~NMI_paused_status) & int_acknwoledged_Outp_s) | trans_paus_to_act_NMI_Outp_s;

assign trans_paus_to_act_NMI_Outp_s = NMI_paused_status & NMI_highest_prio & int_returned_Outp_s;
assign NMI_paused_clr = trans_paus_to_act_NMI_Outp_s;

assign int_returned_Outp_s = nmi_ended | int_ended;

assign int_acknwoledged_Outp_s = nmi_intr_ACK | intr_ACK;

assign trans_act_to_idle_NMI_Outp_s = NMI_active_status & int_returned_Outp_s;
assign NMI_requested_clr = trans_act_to_idle_NMI_Outp_s;

assign trans_act_to_paus_NMI_Outp_s = NMI_active_status & int_acknwoledged_Outp_s;
assign NMI_paused_set = trans_act_to_paus_NMI_Outp_s;

assign NMI_active_clr = trans_act_to_paus_NMI_Outp_s | trans_act_to_idle_NMI_Outp_s;

assign trans_pend_to_req_NMI_Outp_s = NMI_highest_prio & (~NMI_active_status) & (~NMI_paused_status) & (~any_in_request_Outp_s);
assign NMI_requested_set = trans_pend_to_req_NMI_Outp_s;
assign nmi_intr_REQ = trans_pend_to_req_NMI_Outp_s;

assign any_in_request_Outp_s = | {(NMI_requested_status & (~NMI_active_status) & (~NMI_paused_status)),(int_1_requested_status & (~int_1_active_status) & (~int_1_paused_status)),(int_4_requested_status & (~int_4_active_status) & (~int_4_paused_status)),(int_7_requested_status & (~int_7_active_status) & (~int_7_paused_status)),(int_11_requested_status & (~int_11_active_status) & (~int_11_paused_status)),(int_15_requested_status & (~int_15_active_status) & (~int_15_paused_status)),(int_19_requested_status & (~int_19_active_status) & (~int_19_paused_status)),(int_21_requested_status & (~int_21_active_status) & (~int_21_paused_status)),(int_28_requested_status & (~int_28_active_status) & (~int_28_paused_status)),(int_5_requested_status & (~int_5_active_status) & (~int_5_paused_status)),(int_8_requested_status & (~int_8_active_status) & (~int_8_paused_status)),(int_12_requested_status & (~int_12_active_status) & (~int_12_paused_status)),(int_16_requested_status & (~int_16_active_status) & (~int_16_paused_status)),(int_22_requested_status & (~int_22_active_status) & (~int_22_paused_status)),(int_25_requested_status & (~int_25_active_status) & (~int_25_paused_status)),(int_29_requested_status & (~int_29_active_status) & (~int_29_paused_status)),(int_30_requested_status & (~int_30_active_status) & (~int_30_paused_status)),(int_2_requested_status & (~int_2_active_status) & (~int_2_paused_status)),(int_9_requested_status & (~int_9_active_status) & (~int_9_paused_status)),(int_13_requested_status & (~int_13_active_status) & (~int_13_paused_status)),(int_17_requested_status & (~int_17_active_status) & (~int_17_paused_status)),(int_20_requested_status & (~int_20_active_status) & (~int_20_paused_status)),(int_23_requested_status & (~int_23_active_status) & (~int_23_paused_status)),(int_26_requested_status & (~int_26_active_status) & (~int_26_paused_status)),(int_31_requested_status & (~int_31_active_status) & (~int_31_paused_status)),(int_0_requested_status & (~int_0_active_status) & (~int_0_paused_status)),(int_3_requested_status & (~int_3_active_status) & (~int_3_paused_status)),(int_6_requested_status & (~int_6_active_status) & (~int_6_paused_status)),(int_10_requested_status & (~int_10_active_status) & (~int_10_paused_status)),(int_14_requested_status & (~int_14_active_status) & (~int_14_paused_status)),(int_18_requested_status & (~int_18_active_status) & (~int_18_paused_status)),(int_24_requested_status & (~int_24_active_status) & (~int_24_paused_status)),(int_27_requested_status & (~int_27_active_status) & (~int_27_paused_status))};

assign trans_pend_to_req_int_27_Outp_s = int_27_highest_prio & (~int_27_active_status) & (~int_27_paused_status) & (~any_in_request_Outp_s);
assign int_27_requested_set = trans_pend_to_req_int_27_Outp_s;

assign trans_pend_to_req_int_24_Outp_s = int_24_highest_prio & (~int_24_active_status) & (~int_24_paused_status) & (~any_in_request_Outp_s);
assign int_24_requested_set = trans_pend_to_req_int_24_Outp_s;

assign trans_pend_to_req_int_18_Outp_s = int_18_highest_prio & (~int_18_active_status) & (~int_18_paused_status) & (~any_in_request_Outp_s);
assign int_18_requested_set = trans_pend_to_req_int_18_Outp_s;

assign trans_pend_to_req_int_14_Outp_s = int_14_highest_prio & (~int_14_active_status) & (~int_14_paused_status) & (~any_in_request_Outp_s);
assign int_14_requested_set = trans_pend_to_req_int_14_Outp_s;

assign trans_pend_to_req_int_10_Outp_s = int_10_highest_prio & (~int_10_active_status) & (~int_10_paused_status) & (~any_in_request_Outp_s);
assign int_10_requested_set = trans_pend_to_req_int_10_Outp_s;

assign trans_pend_to_req_int_6_Outp_s = int_6_highest_prio & (~int_6_active_status) & (~int_6_paused_status) & (~any_in_request_Outp_s);
assign int_6_requested_set = trans_pend_to_req_int_6_Outp_s;

assign trans_pend_to_req_int_3_Outp_s = int_3_highest_prio & (~int_3_active_status) & (~int_3_paused_status) & (~any_in_request_Outp_s);
assign int_3_requested_set = trans_pend_to_req_int_3_Outp_s;

assign trans_pend_to_req_int_0_Outp_s = int_0_highest_prio & (~int_0_active_status) & (~int_0_paused_status) & (~any_in_request_Outp_s);
assign int_0_requested_set = trans_pend_to_req_int_0_Outp_s;

assign trans_pend_to_req_int_31_Outp_s = int_31_highest_prio & (~int_31_active_status) & (~int_31_paused_status) & (~any_in_request_Outp_s);
assign int_31_requested_set = trans_pend_to_req_int_31_Outp_s;

assign trans_pend_to_req_int_26_Outp_s = int_26_highest_prio & (~int_26_active_status) & (~int_26_paused_status) & (~any_in_request_Outp_s);
assign int_26_requested_set = trans_pend_to_req_int_26_Outp_s;

assign trans_pend_to_req_int_23_Outp_s = int_23_highest_prio & (~int_23_active_status) & (~int_23_paused_status) & (~any_in_request_Outp_s);
assign int_23_requested_set = trans_pend_to_req_int_23_Outp_s;

assign trans_pend_to_req_int_20_Outp_s = int_20_highest_prio & (~int_20_active_status) & (~int_20_paused_status) & (~any_in_request_Outp_s);
assign int_20_requested_set = trans_pend_to_req_int_20_Outp_s;

assign trans_pend_to_req_int_17_Outp_s = int_17_highest_prio & (~int_17_active_status) & (~int_17_paused_status) & (~any_in_request_Outp_s);
assign int_17_requested_set = trans_pend_to_req_int_17_Outp_s;

assign trans_pend_to_req_int_13_Outp_s = int_13_highest_prio & (~int_13_active_status) & (~int_13_paused_status) & (~any_in_request_Outp_s);
assign int_13_requested_set = trans_pend_to_req_int_13_Outp_s;

assign trans_pend_to_req_int_9_Outp_s = int_9_highest_prio & (~int_9_active_status) & (~int_9_paused_status) & (~any_in_request_Outp_s);
assign int_9_requested_set = trans_pend_to_req_int_9_Outp_s;

assign trans_pend_to_req_int_2_Outp_s = int_2_highest_prio & (~int_2_active_status) & (~int_2_paused_status) & (~any_in_request_Outp_s);
assign int_2_requested_set = trans_pend_to_req_int_2_Outp_s;

assign trans_pend_to_req_int_30_Outp_s = int_30_highest_prio & (~int_30_active_status) & (~int_30_paused_status) & (~any_in_request_Outp_s);
assign int_30_requested_set = trans_pend_to_req_int_30_Outp_s;

assign trans_pend_to_req_int_29_Outp_s = int_29_highest_prio & (~int_29_active_status) & (~int_29_paused_status) & (~any_in_request_Outp_s);
assign int_29_requested_set = trans_pend_to_req_int_29_Outp_s;

assign trans_pend_to_req_int_25_Outp_s = int_25_highest_prio & (~int_25_active_status) & (~int_25_paused_status) & (~any_in_request_Outp_s);
assign int_25_requested_set = trans_pend_to_req_int_25_Outp_s;

assign trans_pend_to_req_int_22_Outp_s = int_22_highest_prio & (~int_22_active_status) & (~int_22_paused_status) & (~any_in_request_Outp_s);
assign int_22_requested_set = trans_pend_to_req_int_22_Outp_s;

assign trans_pend_to_req_int_16_Outp_s = int_16_highest_prio & (~int_16_active_status) & (~int_16_paused_status) & (~any_in_request_Outp_s);
assign int_16_requested_set = trans_pend_to_req_int_16_Outp_s;

assign trans_pend_to_req_int_12_Outp_s = int_12_highest_prio & (~int_12_active_status) & (~int_12_paused_status) & (~any_in_request_Outp_s);
assign int_12_requested_set = trans_pend_to_req_int_12_Outp_s;

assign trans_pend_to_req_int_8_Outp_s = int_8_highest_prio & (~int_8_active_status) & (~int_8_paused_status) & (~any_in_request_Outp_s);
assign int_8_requested_set = trans_pend_to_req_int_8_Outp_s;

assign trans_pend_to_req_int_5_Outp_s = int_5_highest_prio & (~int_5_active_status) & (~int_5_paused_status) & (~any_in_request_Outp_s);
assign int_5_requested_set = trans_pend_to_req_int_5_Outp_s;

assign trans_pend_to_req_int_28_Outp_s = int_28_highest_prio & (~int_28_active_status) & (~int_28_paused_status) & (~any_in_request_Outp_s);
assign int_28_requested_set = trans_pend_to_req_int_28_Outp_s;

assign trans_pend_to_req_int_21_Outp_s = int_21_highest_prio & (~int_21_active_status) & (~int_21_paused_status) & (~any_in_request_Outp_s);
assign int_21_requested_set = trans_pend_to_req_int_21_Outp_s;

assign trans_pend_to_req_int_19_Outp_s = int_19_highest_prio & (~int_19_active_status) & (~int_19_paused_status) & (~any_in_request_Outp_s);
assign int_19_requested_set = trans_pend_to_req_int_19_Outp_s;

assign trans_pend_to_req_int_15_Outp_s = int_15_highest_prio & (~int_15_active_status) & (~int_15_paused_status) & (~any_in_request_Outp_s);
assign int_15_requested_set = trans_pend_to_req_int_15_Outp_s;

assign trans_pend_to_req_int_11_Outp_s = int_11_highest_prio & (~int_11_active_status) & (~int_11_paused_status) & (~any_in_request_Outp_s);
assign int_11_requested_set = trans_pend_to_req_int_11_Outp_s;

assign trans_pend_to_req_int_7_Outp_s = int_7_highest_prio & (~int_7_active_status) & (~int_7_paused_status) & (~any_in_request_Outp_s);
assign int_7_requested_set = trans_pend_to_req_int_7_Outp_s;

assign trans_pend_to_req_int_4_Outp_s = int_4_highest_prio & (~int_4_active_status) & (~int_4_paused_status) & (~any_in_request_Outp_s);
assign int_4_requested_set = trans_pend_to_req_int_4_Outp_s;

assign trans_pend_to_req_int_1_Outp_s = int_1_highest_prio & (~int_1_active_status) & (~int_1_paused_status) & (~any_in_request_Outp_s);
assign int_1_requested_set = trans_pend_to_req_int_1_Outp_s;

assign intr_REQ = | {trans_pend_to_req_int_1_Outp_s,trans_pend_to_req_int_4_Outp_s,trans_pend_to_req_int_7_Outp_s,trans_pend_to_req_int_11_Outp_s,trans_pend_to_req_int_15_Outp_s,trans_pend_to_req_int_19_Outp_s,trans_pend_to_req_int_21_Outp_s,trans_pend_to_req_int_28_Outp_s,trans_pend_to_req_int_5_Outp_s,trans_pend_to_req_int_8_Outp_s,trans_pend_to_req_int_12_Outp_s,trans_pend_to_req_int_16_Outp_s,trans_pend_to_req_int_22_Outp_s,trans_pend_to_req_int_25_Outp_s,trans_pend_to_req_int_29_Outp_s,trans_pend_to_req_int_30_Outp_s,trans_pend_to_req_int_2_Outp_s,trans_pend_to_req_int_9_Outp_s,trans_pend_to_req_int_13_Outp_s,trans_pend_to_req_int_17_Outp_s,trans_pend_to_req_int_20_Outp_s,trans_pend_to_req_int_23_Outp_s,trans_pend_to_req_int_26_Outp_s,trans_pend_to_req_int_31_Outp_s,trans_pend_to_req_int_0_Outp_s,trans_pend_to_req_int_3_Outp_s,trans_pend_to_req_int_6_Outp_s,trans_pend_to_req_int_10_Outp_s,trans_pend_to_req_int_14_Outp_s,trans_pend_to_req_int_18_Outp_s,trans_pend_to_req_int_24_Outp_s,trans_pend_to_req_int_27_Outp_s};


endmodule

