/* ===============================================================
Copyright 2026, Infineon Technologies AG or an 
affiliate of Infineon Technologies AG.  All rights reserved.
 
This software, associated documentation and materials ("Software") is owned by
Infineon Technologies AG or one of its affiliates ("Infineon") and is 
protected by and subject to worldwide patent protection (United States and 
foreign), United States copyright laws and international treaty provisions. 
Therefore, you may use this Software only as provided in the license agreement
accompanying the software package from which you obtained this 
Software ("EULA"). If no EULA applies, then any reproduction, modification, 
translation, compilation, or representation of this Software is prohibited 
without the express written permission of Infineon.
 
Disclaimer: THIS SOFTWARE IS PROVIDED AS-IS, WITH NO WARRANTY OF 
ANY KIND, EXPRESS OR IMPLIED, INCLUDING, BUT NOT LIMITED TO, 
NONINFRINGEMENT, IMPLIED WARRANTIES OF  MERCHANTABILITY AND
FITNESS FOR A PARTICULAR PURPOSE.  Infineon reserves the right to make
changes to the Software without notice. Infineon does not assume any liability
arising out of the application or use of the Software or any product or 
circuit described in the Software. Infineon does not authorize its products 
for use in any products where a malfunction or failure of the Infineon product 
may reasonably be expected to result in significant property damage, injury or
death ("High Risk Product").  By including Infineon 's product in a High Risk 
Product, the manufacturer of such system or application assumes all risk of 
such use and in doing so agrees to indemnify Infineon against all liability.

 ===============================================================
*/ 
// File : InterruptController_ICcomponent_PRIO_RESOLUTION_Grouping_Priority_Circuit03_Priority_Circuit.sv 
// Author : tahiraga 
// Date : 18:20:55    21/09/2026 
// Revision :  
// =============================================================== 
// Description : 
/*
---- Auto Generated by MetaRTL , a MetaGen application
---- Contact: ParitoshKumar.Sinha@infineon.com
---- Contact: Yash.Ranjan@infineon.com
===============================================================
*/


module InterruptController_Priority_Circuit (
    input pend_LEVEL_0,
    output prio_LEVEL_0,
    input pend_LEVEL_1,
    output prio_LEVEL_1,
    input pend_LEVEL_2,
    output prio_LEVEL_2,
    input pend_LEVEL_3,
    output prio_LEVEL_3,
    input pend_LEVEL_4,
    output prio_LEVEL_4,
    input pend_LEVEL_5,
    output prio_LEVEL_5,
    input pend_LEVEL_6,
    output prio_LEVEL_6,
    input pend_LEVEL_7,
    output prio_LEVEL_7
);

assign prio_LEVEL_7 = pend_LEVEL_7 & (~pend_LEVEL_0) & (~pend_LEVEL_1) & (~pend_LEVEL_2) & (~pend_LEVEL_3) & (~pend_LEVEL_4) & (~pend_LEVEL_5) & (~pend_LEVEL_6);

assign prio_LEVEL_6 = pend_LEVEL_6 & (~pend_LEVEL_0) & (~pend_LEVEL_1) & (~pend_LEVEL_2) & (~pend_LEVEL_3) & (~pend_LEVEL_4) & (~pend_LEVEL_5);

assign prio_LEVEL_5 = pend_LEVEL_5 & (~pend_LEVEL_0) & (~pend_LEVEL_1) & (~pend_LEVEL_2) & (~pend_LEVEL_3) & (~pend_LEVEL_4);

assign prio_LEVEL_4 = pend_LEVEL_4 & (~pend_LEVEL_0) & (~pend_LEVEL_1) & (~pend_LEVEL_2) & (~pend_LEVEL_3);

assign prio_LEVEL_3 = pend_LEVEL_3 & (~pend_LEVEL_0) & (~pend_LEVEL_1) & (~pend_LEVEL_2);

assign prio_LEVEL_2 = pend_LEVEL_2 & (~pend_LEVEL_0) & (~pend_LEVEL_1);

assign prio_LEVEL_1 = pend_LEVEL_1 & (~pend_LEVEL_0);

assign prio_LEVEL_0 = pend_LEVEL_0;

endmodule

