/* ===============================================================
Copyright 2026, Infineon Technologies AG or an 
affiliate of Infineon Technologies AG.  All rights reserved.
 
This software, associated documentation and materials ("Software") is owned by
Infineon Technologies AG or one of its affiliates ("Infineon") and is 
protected by and subject to worldwide patent protection (United States and 
foreign), United States copyright laws and international treaty provisions. 
Therefore, you may use this Software only as provided in the license agreement
accompanying the software package from which you obtained this 
Software ("EULA"). If no EULA applies, then any reproduction, modification, 
translation, compilation, or representation of this Software is prohibited 
without the express written permission of Infineon.
 
Disclaimer: THIS SOFTWARE IS PROVIDED AS-IS, WITH NO WARRANTY OF 
ANY KIND, EXPRESS OR IMPLIED, INCLUDING, BUT NOT LIMITED TO, 
NONINFRINGEMENT, IMPLIED WARRANTIES OF  MERCHANTABILITY AND
FITNESS FOR A PARTICULAR PURPOSE.  Infineon reserves the right to make
changes to the Software without notice. Infineon does not assume any liability
arising out of the application or use of the Software or any product or 
circuit described in the Software. Infineon does not authorize its products 
for use in any products where a malfunction or failure of the Infineon product 
may reasonably be expected to result in significant property damage, injury or
death ("High Risk Product").  By including Infineon 's product in a High Risk 
Product, the manufacturer of such system or application assumes all risk of 
such use and in doing so agrees to indemnify Infineon against all liability.

 ===============================================================
*/ 
// File : InterruptController_ICcomponent_PRIO_RESOLUTION_Grouping_Priority_Circuit01.sv 
// Author : tahiraga 
// Date : 18:21:32    21/09/2026 
// Revision :  
// =============================================================== 
// Description : 
/*
---- Auto Generated by MetaRTL , a MetaGen application
---- Contact: ParitoshKumar.Sinha@infineon.com
---- Contact: Yash.Ranjan@infineon.com
===============================================================
*/


module InterruptController_ICcomponent_PRIO_RESOLUTION_Grouping_Priority_Circuit01 (
    input pend_int_5,
    input req_int_5,
    input active_int_5,
    output prio_0,
    input [2:0] sel_prio_int_5,
    input pend_int_8,
    input req_int_8,
    input active_int_8,
    output prio_1,
    input [2:0] sel_prio_int_8,
    input pend_int_12,
    input req_int_12,
    input active_int_12,
    output prio_2,
    input [2:0] sel_prio_int_12,
    input pend_int_16,
    input req_int_16,
    input active_int_16,
    output prio_3,
    input [2:0] sel_prio_int_16,
    input pend_int_22,
    input req_int_22,
    input active_int_22,
    output prio_4,
    input [2:0] sel_prio_int_22,
    input pend_int_25,
    input req_int_25,
    input active_int_25,
    output prio_5,
    input [2:0] sel_prio_int_25,
    input pend_int_29,
    input req_int_29,
    input active_int_29,
    output prio_6,
    input [2:0] sel_prio_int_29,
    input pend_int_30,
    input req_int_30,
    input active_int_30,
    output prio_7,
    input [2:0] sel_prio_int_30,
    input int_ended
);

logic   NOT01_Outp_s;
logic   [7:0] CONCAT07_Outp_s;
logic   [7:0] CONCAT06_Outp_s;
logic   [7:0] CONCAT05_Outp_s;
logic   [7:0] CONCAT04_Outp_s;
logic   [7:0] CONCAT03_Outp_s;
logic   [7:0] CONCAT02_Outp_s;
logic   [7:0] CONCAT01_Outp_s;
logic   mask_pend_int_30_Outp_s;
logic   mask_pend_int_29_Outp_s;
logic   mask_pend_int_25_Outp_s;
logic   mask_pend_int_22_Outp_s;
logic   mask_pend_int_16_Outp_s;
logic   mask_pend_int_12_Outp_s;
logic   mask_pend_int_8_Outp_s;
logic   mask_pend_int_5_Outp_s;
logic   [7:0] CONCAT00_Outp_s;

logic   prio_7_Outp_s;
logic   prio_6_Outp_s;
logic   prio_5_Outp_s;
logic   prio_4_Outp_s;
logic   prio_3_Outp_s;
logic   prio_2_Outp_s;
logic   prio_1_Outp_s;
logic   prio_0_Outp_s;

assign NOT01_Outp_s = ~((~(int_ended & (| {active_int_5,active_int_8,active_int_12,active_int_16,active_int_22,active_int_25,active_int_29,active_int_30}))) & (| {req_int_5,req_int_8,req_int_12,req_int_16,req_int_22,req_int_25,req_int_29,req_int_30}));

assign CONCAT07_Outp_s = {(sel_prio_int_30 == 3'b111 ? 1'b1 : 1'b0),(sel_prio_int_29 == 3'b111 ? 1'b1 : 1'b0),(sel_prio_int_25 == 3'b111 ? 1'b1 : 1'b0),(sel_prio_int_22 == 3'b111 ? 1'b1 : 1'b0),(sel_prio_int_16 == 3'b111 ? 1'b1 : 1'b0),(sel_prio_int_12 == 3'b111 ? 1'b1 : 1'b0),(sel_prio_int_8 == 3'b111 ? 1'b1 : 1'b0),(sel_prio_int_5 == 3'b111 ? 1'b1 : 1'b0)};

assign CONCAT06_Outp_s = {(sel_prio_int_30 == 3'b110 ? 1'b1 : 1'b0),(sel_prio_int_29 == 3'b110 ? 1'b1 : 1'b0),(sel_prio_int_25 == 3'b110 ? 1'b1 : 1'b0),(sel_prio_int_22 == 3'b110 ? 1'b1 : 1'b0),(sel_prio_int_16 == 3'b110 ? 1'b1 : 1'b0),(sel_prio_int_12 == 3'b110 ? 1'b1 : 1'b0),(sel_prio_int_8 == 3'b110 ? 1'b1 : 1'b0),(sel_prio_int_5 == 3'b110 ? 1'b1 : 1'b0)};

assign CONCAT05_Outp_s = {(sel_prio_int_30 == 3'b101 ? 1'b1 : 1'b0),(sel_prio_int_29 == 3'b101 ? 1'b1 : 1'b0),(sel_prio_int_25 == 3'b101 ? 1'b1 : 1'b0),(sel_prio_int_22 == 3'b101 ? 1'b1 : 1'b0),(sel_prio_int_16 == 3'b101 ? 1'b1 : 1'b0),(sel_prio_int_12 == 3'b101 ? 1'b1 : 1'b0),(sel_prio_int_8 == 3'b101 ? 1'b1 : 1'b0),(sel_prio_int_5 == 3'b101 ? 1'b1 : 1'b0)};

assign CONCAT04_Outp_s = {(sel_prio_int_30 == 3'b100 ? 1'b1 : 1'b0),(sel_prio_int_29 == 3'b100 ? 1'b1 : 1'b0),(sel_prio_int_25 == 3'b100 ? 1'b1 : 1'b0),(sel_prio_int_22 == 3'b100 ? 1'b1 : 1'b0),(sel_prio_int_16 == 3'b100 ? 1'b1 : 1'b0),(sel_prio_int_12 == 3'b100 ? 1'b1 : 1'b0),(sel_prio_int_8 == 3'b100 ? 1'b1 : 1'b0),(sel_prio_int_5 == 3'b100 ? 1'b1 : 1'b0)};

assign CONCAT03_Outp_s = {(sel_prio_int_30 == 3'b11 ? 1'b1 : 1'b0),(sel_prio_int_29 == 3'b11 ? 1'b1 : 1'b0),(sel_prio_int_25 == 3'b11 ? 1'b1 : 1'b0),(sel_prio_int_22 == 3'b11 ? 1'b1 : 1'b0),(sel_prio_int_16 == 3'b11 ? 1'b1 : 1'b0),(sel_prio_int_12 == 3'b11 ? 1'b1 : 1'b0),(sel_prio_int_8 == 3'b11 ? 1'b1 : 1'b0),(sel_prio_int_5 == 3'b11 ? 1'b1 : 1'b0)};

assign CONCAT02_Outp_s = {(sel_prio_int_30 == 3'b10 ? 1'b1 : 1'b0),(sel_prio_int_29 == 3'b10 ? 1'b1 : 1'b0),(sel_prio_int_25 == 3'b10 ? 1'b1 : 1'b0),(sel_prio_int_22 == 3'b10 ? 1'b1 : 1'b0),(sel_prio_int_16 == 3'b10 ? 1'b1 : 1'b0),(sel_prio_int_12 == 3'b10 ? 1'b1 : 1'b0),(sel_prio_int_8 == 3'b10 ? 1'b1 : 1'b0),(sel_prio_int_5 == 3'b10 ? 1'b1 : 1'b0)};

assign CONCAT01_Outp_s = {(sel_prio_int_30 == 3'b1 ? 1'b1 : 1'b0),(sel_prio_int_29 == 3'b1 ? 1'b1 : 1'b0),(sel_prio_int_25 == 3'b1 ? 1'b1 : 1'b0),(sel_prio_int_22 == 3'b1 ? 1'b1 : 1'b0),(sel_prio_int_16 == 3'b1 ? 1'b1 : 1'b0),(sel_prio_int_12 == 3'b1 ? 1'b1 : 1'b0),(sel_prio_int_8 == 3'b1 ? 1'b1 : 1'b0),(sel_prio_int_5 == 3'b1 ? 1'b1 : 1'b0)};

assign mask_pend_int_30_Outp_s = pend_int_30 & (NOT01_Outp_s | req_int_30);

assign mask_pend_int_29_Outp_s = pend_int_29 & (NOT01_Outp_s | req_int_29);

assign mask_pend_int_25_Outp_s = pend_int_25 & (NOT01_Outp_s | req_int_25);

assign mask_pend_int_22_Outp_s = pend_int_22 & (NOT01_Outp_s | req_int_22);

assign mask_pend_int_16_Outp_s = pend_int_16 & (NOT01_Outp_s | req_int_16);

assign mask_pend_int_12_Outp_s = pend_int_12 & (NOT01_Outp_s | req_int_12);

assign mask_pend_int_8_Outp_s = pend_int_8 & (NOT01_Outp_s | req_int_8);

assign mask_pend_int_5_Outp_s = pend_int_5 & (NOT01_Outp_s | req_int_5);

assign CONCAT00_Outp_s = {(sel_prio_int_30 == 3'b0 ? 1'b1 : 1'b0),(sel_prio_int_29 == 3'b0 ? 1'b1 : 1'b0),(sel_prio_int_25 == 3'b0 ? 1'b1 : 1'b0),(sel_prio_int_22 == 3'b0 ? 1'b1 : 1'b0),(sel_prio_int_16 == 3'b0 ? 1'b1 : 1'b0),(sel_prio_int_12 == 3'b0 ? 1'b1 : 1'b0),(sel_prio_int_8 == 3'b0 ? 1'b1 : 1'b0),(sel_prio_int_5 == 3'b0 ? 1'b1 : 1'b0)};

always_comb
begin
    case (CONCAT07_Outp_s)
        8'b1 : prio_7_Outp_s = mask_pend_int_5_Outp_s;
        8'b10 : prio_7_Outp_s = mask_pend_int_8_Outp_s;
        8'b100 : prio_7_Outp_s = mask_pend_int_12_Outp_s;
        8'b1000 : prio_7_Outp_s = mask_pend_int_16_Outp_s;
        8'b10000 : prio_7_Outp_s = mask_pend_int_22_Outp_s;
        8'b100000 : prio_7_Outp_s = mask_pend_int_25_Outp_s;
        8'b1000000 : prio_7_Outp_s = mask_pend_int_29_Outp_s;
        8'b10000000 : prio_7_Outp_s = mask_pend_int_30_Outp_s;
        default : prio_7_Outp_s = 1'b0;
    endcase
end

always_comb
begin
    case (CONCAT06_Outp_s)
        8'b1 : prio_6_Outp_s = mask_pend_int_5_Outp_s;
        8'b10 : prio_6_Outp_s = mask_pend_int_8_Outp_s;
        8'b100 : prio_6_Outp_s = mask_pend_int_12_Outp_s;
        8'b1000 : prio_6_Outp_s = mask_pend_int_16_Outp_s;
        8'b10000 : prio_6_Outp_s = mask_pend_int_22_Outp_s;
        8'b100000 : prio_6_Outp_s = mask_pend_int_25_Outp_s;
        8'b1000000 : prio_6_Outp_s = mask_pend_int_29_Outp_s;
        8'b10000000 : prio_6_Outp_s = mask_pend_int_30_Outp_s;
        default : prio_6_Outp_s = 1'b0;
    endcase
end

always_comb
begin
    case (CONCAT05_Outp_s)
        8'b1 : prio_5_Outp_s = mask_pend_int_5_Outp_s;
        8'b10 : prio_5_Outp_s = mask_pend_int_8_Outp_s;
        8'b100 : prio_5_Outp_s = mask_pend_int_12_Outp_s;
        8'b1000 : prio_5_Outp_s = mask_pend_int_16_Outp_s;
        8'b10000 : prio_5_Outp_s = mask_pend_int_22_Outp_s;
        8'b100000 : prio_5_Outp_s = mask_pend_int_25_Outp_s;
        8'b1000000 : prio_5_Outp_s = mask_pend_int_29_Outp_s;
        8'b10000000 : prio_5_Outp_s = mask_pend_int_30_Outp_s;
        default : prio_5_Outp_s = 1'b0;
    endcase
end

always_comb
begin
    case (CONCAT04_Outp_s)
        8'b1 : prio_4_Outp_s = mask_pend_int_5_Outp_s;
        8'b10 : prio_4_Outp_s = mask_pend_int_8_Outp_s;
        8'b100 : prio_4_Outp_s = mask_pend_int_12_Outp_s;
        8'b1000 : prio_4_Outp_s = mask_pend_int_16_Outp_s;
        8'b10000 : prio_4_Outp_s = mask_pend_int_22_Outp_s;
        8'b100000 : prio_4_Outp_s = mask_pend_int_25_Outp_s;
        8'b1000000 : prio_4_Outp_s = mask_pend_int_29_Outp_s;
        8'b10000000 : prio_4_Outp_s = mask_pend_int_30_Outp_s;
        default : prio_4_Outp_s = 1'b0;
    endcase
end

always_comb
begin
    case (CONCAT03_Outp_s)
        8'b1 : prio_3_Outp_s = mask_pend_int_5_Outp_s;
        8'b10 : prio_3_Outp_s = mask_pend_int_8_Outp_s;
        8'b100 : prio_3_Outp_s = mask_pend_int_12_Outp_s;
        8'b1000 : prio_3_Outp_s = mask_pend_int_16_Outp_s;
        8'b10000 : prio_3_Outp_s = mask_pend_int_22_Outp_s;
        8'b100000 : prio_3_Outp_s = mask_pend_int_25_Outp_s;
        8'b1000000 : prio_3_Outp_s = mask_pend_int_29_Outp_s;
        8'b10000000 : prio_3_Outp_s = mask_pend_int_30_Outp_s;
        default : prio_3_Outp_s = 1'b0;
    endcase
end

always_comb
begin
    case (CONCAT02_Outp_s)
        8'b1 : prio_2_Outp_s = mask_pend_int_5_Outp_s;
        8'b10 : prio_2_Outp_s = mask_pend_int_8_Outp_s;
        8'b100 : prio_2_Outp_s = mask_pend_int_12_Outp_s;
        8'b1000 : prio_2_Outp_s = mask_pend_int_16_Outp_s;
        8'b10000 : prio_2_Outp_s = mask_pend_int_22_Outp_s;
        8'b100000 : prio_2_Outp_s = mask_pend_int_25_Outp_s;
        8'b1000000 : prio_2_Outp_s = mask_pend_int_29_Outp_s;
        8'b10000000 : prio_2_Outp_s = mask_pend_int_30_Outp_s;
        default : prio_2_Outp_s = 1'b0;
    endcase
end

always_comb
begin
    case (CONCAT01_Outp_s)
        8'b1 : prio_1_Outp_s = mask_pend_int_5_Outp_s;
        8'b10 : prio_1_Outp_s = mask_pend_int_8_Outp_s;
        8'b100 : prio_1_Outp_s = mask_pend_int_12_Outp_s;
        8'b1000 : prio_1_Outp_s = mask_pend_int_16_Outp_s;
        8'b10000 : prio_1_Outp_s = mask_pend_int_22_Outp_s;
        8'b100000 : prio_1_Outp_s = mask_pend_int_25_Outp_s;
        8'b1000000 : prio_1_Outp_s = mask_pend_int_29_Outp_s;
        8'b10000000 : prio_1_Outp_s = mask_pend_int_30_Outp_s;
        default : prio_1_Outp_s = 1'b0;
    endcase
end

always_comb
begin
    case (CONCAT00_Outp_s)
        8'b1 : prio_0_Outp_s = mask_pend_int_5_Outp_s;
        8'b10 : prio_0_Outp_s = mask_pend_int_8_Outp_s;
        8'b100 : prio_0_Outp_s = mask_pend_int_12_Outp_s;
        8'b1000 : prio_0_Outp_s = mask_pend_int_16_Outp_s;
        8'b10000 : prio_0_Outp_s = mask_pend_int_22_Outp_s;
        8'b100000 : prio_0_Outp_s = mask_pend_int_25_Outp_s;
        8'b1000000 : prio_0_Outp_s = mask_pend_int_29_Outp_s;
        8'b10000000 : prio_0_Outp_s = mask_pend_int_30_Outp_s;
        default : prio_0_Outp_s = 1'b0;
    endcase
end

InterruptController_Priority_Circuit comp_Priority_Circuit(
    .pend_LEVEL_0 ( prio_0_Outp_s ),
    .pend_LEVEL_1 ( prio_1_Outp_s ),
    .pend_LEVEL_2 ( prio_2_Outp_s ),
    .pend_LEVEL_3 ( prio_3_Outp_s ),
    .pend_LEVEL_4 ( prio_4_Outp_s ),
    .pend_LEVEL_5 ( prio_5_Outp_s ),
    .pend_LEVEL_6 ( prio_6_Outp_s ),
    .pend_LEVEL_7 ( prio_7_Outp_s ),
    .prio_LEVEL_0 ( prio_0        ),
    .prio_LEVEL_1 ( prio_1        ),
    .prio_LEVEL_2 ( prio_2        ),
    .prio_LEVEL_3 ( prio_3        ),
    .prio_LEVEL_4 ( prio_4        ),
    .prio_LEVEL_5 ( prio_5        ),
    .prio_LEVEL_6 ( prio_6        ),
    .prio_LEVEL_7 ( prio_7        )
);


endmodule

