/* ===============================================================
Copyright 2026, Infineon Technologies AG or an 
affiliate of Infineon Technologies AG.  All rights reserved.
 
This software, associated documentation and materials ("Software") is owned by
Infineon Technologies AG or one of its affiliates ("Infineon") and is 
protected by and subject to worldwide patent protection (United States and 
foreign), United States copyright laws and international treaty provisions. 
Therefore, you may use this Software only as provided in the license agreement
accompanying the software package from which you obtained this 
Software ("EULA"). If no EULA applies, then any reproduction, modification, 
translation, compilation, or representation of this Software is prohibited 
without the express written permission of Infineon.
 
Disclaimer: THIS SOFTWARE IS PROVIDED AS-IS, WITH NO WARRANTY OF 
ANY KIND, EXPRESS OR IMPLIED, INCLUDING, BUT NOT LIMITED TO, 
NONINFRINGEMENT, IMPLIED WARRANTIES OF  MERCHANTABILITY AND
FITNESS FOR A PARTICULAR PURPOSE.  Infineon reserves the right to make
changes to the Software without notice. Infineon does not assume any liability
arising out of the application or use of the Software or any product or 
circuit described in the Software. Infineon does not authorize its products 
for use in any products where a malfunction or failure of the Infineon product 
may reasonably be expected to result in significant property damage, injury or
death ("High Risk Product").  By including Infineon 's product in a High Risk 
Product, the manufacturer of such system or application assumes all risk of 
such use and in doing so agrees to indemnify Infineon against all liability.

 ===============================================================
*/ 
// File : InterruptController_Reg_IF_AHB_RAI_Bridge_bridge_sync.sv 
// Author : tahiraga 
// Date : 18:21:28    21/09/2026 
// Revision :  
// =============================================================== 
// Description : 
/*
---- Auto Generated by MetaRTL , a MetaGen application
---- Contact: ParitoshKumar.Sinha@infineon.com
---- Contact: Yash.Ranjan@infineon.com
===============================================================
*/


module InterruptController_Reg_IF_AHB_RAI_Bridge_bridge_sync (
    input hsel_i,
    input [2:0] hsize_i,
    input hwrite_i,
    input [31:0] haddr_i,
    input [31:0] hwdata_i,
    output logic  [31:0] hrdata_o,
    output access_done_o,
    input rai_per_ack_i,
    input [31:0] rai_per_rdata_i,
    output rai_per_acc_en_o,
    output logic  rai_per_wr_en_o,
    output logic  [1:0] csc_access_size_o,
    output logic  [31:0] rai_per_wdata_o
);

logic   EQ02_Outp_s;
logic   EQ01_Outp_s;
logic   EQ00_Outp_s;


always_comb
begin
    case (hsel_i)
        1'b0 : rai_per_wdata_o = 32'b0;
        1'b1 : rai_per_wdata_o = hwdata_i;
        default : rai_per_wdata_o = 32'b0;
    endcase
end

assign EQ02_Outp_s = hsize_i == 3'b10 ? 1'b1 : 1'b0;

assign EQ01_Outp_s = hsize_i == 3'b1 ? 1'b1 : 1'b0;

assign EQ00_Outp_s = hsize_i == 3'b0 ? 1'b1 : 1'b0;


always_comb
begin
    if (EQ00_Outp_s == 1'b1) begin
        csc_access_size_o = 2'b10;
    end
    else if (EQ01_Outp_s == 1'b1) begin
        csc_access_size_o = 2'b1;
    end
    else if (EQ02_Outp_s == 1'b1) begin
        csc_access_size_o = 2'b0;
    end else begin
        csc_access_size_o = 2'b0;
    end
end

always_comb
begin
    case (hsel_i)
        1'b0 : rai_per_wr_en_o = 1'b0;
        1'b1 : rai_per_wr_en_o = hwrite_i;
        default : rai_per_wr_en_o = 1'b0;
    endcase
end

always_comb
begin
    case (hsel_i)
        1'b0 : hrdata_o = 32'b0;
        1'b1 : hrdata_o = rai_per_rdata_i;
        default : hrdata_o = 32'b0;
    endcase
end

assign access_done_o = rai_per_ack_i;
assign rai_per_acc_en_o = hsel_i;

endmodule

