/* ===============================================================
Copyright 2026, Infineon Technologies AG or an 
affiliate of Infineon Technologies AG.  All rights reserved.
 
This software, associated documentation and materials ("Software") is owned by
Infineon Technologies AG or one of its affiliates ("Infineon") and is 
protected by and subject to worldwide patent protection (United States and 
foreign), United States copyright laws and international treaty provisions. 
Therefore, you may use this Software only as provided in the license agreement
accompanying the software package from which you obtained this 
Software ("EULA"). If no EULA applies, then any reproduction, modification, 
translation, compilation, or representation of this Software is prohibited 
without the express written permission of Infineon.
 
Disclaimer: THIS SOFTWARE IS PROVIDED AS-IS, WITH NO WARRANTY OF 
ANY KIND, EXPRESS OR IMPLIED, INCLUDING, BUT NOT LIMITED TO, 
NONINFRINGEMENT, IMPLIED WARRANTIES OF  MERCHANTABILITY AND
FITNESS FOR A PARTICULAR PURPOSE.  Infineon reserves the right to make
changes to the Software without notice. Infineon does not assume any liability
arising out of the application or use of the Software or any product or 
circuit described in the Software. Infineon does not authorize its products 
for use in any products where a malfunction or failure of the Infineon product 
may reasonably be expected to result in significant property damage, injury or
death ("High Risk Product").  By including Infineon 's product in a High Risk 
Product, the manufacturer of such system or application assumes all risk of 
such use and in doing so agrees to indemnify Infineon against all liability.

 ===============================================================
*/ 
// File : InterruptController_ICcomponent_PRIO_RESOLUTION_Grouping_Priority_Circuit02.sv 
// Author : tahiraga 
// Date : 18:21:31    21/09/2026 
// Revision :  
// =============================================================== 
// Description : 
/*
---- Auto Generated by MetaRTL , a MetaGen application
---- Contact: ParitoshKumar.Sinha@infineon.com
---- Contact: Yash.Ranjan@infineon.com
===============================================================
*/


module InterruptController_ICcomponent_PRIO_RESOLUTION_Grouping_Priority_Circuit02 (
    input pend_int_2,
    input req_int_2,
    input active_int_2,
    output prio_0,
    input [2:0] sel_prio_int_2,
    input pend_int_9,
    input req_int_9,
    input active_int_9,
    output prio_1,
    input [2:0] sel_prio_int_9,
    input pend_int_13,
    input req_int_13,
    input active_int_13,
    output prio_2,
    input [2:0] sel_prio_int_13,
    input pend_int_17,
    input req_int_17,
    input active_int_17,
    output prio_3,
    input [2:0] sel_prio_int_17,
    input pend_int_20,
    input req_int_20,
    input active_int_20,
    output prio_4,
    input [2:0] sel_prio_int_20,
    input pend_int_23,
    input req_int_23,
    input active_int_23,
    output prio_5,
    input [2:0] sel_prio_int_23,
    input pend_int_26,
    input req_int_26,
    input active_int_26,
    output prio_6,
    input [2:0] sel_prio_int_26,
    input pend_int_31,
    input req_int_31,
    input active_int_31,
    output prio_7,
    input [2:0] sel_prio_int_31,
    input int_ended
);

logic   NOT01_Outp_s;
logic   [7:0] CONCAT07_Outp_s;
logic   [7:0] CONCAT06_Outp_s;
logic   [7:0] CONCAT05_Outp_s;
logic   [7:0] CONCAT04_Outp_s;
logic   [7:0] CONCAT03_Outp_s;
logic   [7:0] CONCAT02_Outp_s;
logic   [7:0] CONCAT01_Outp_s;
logic   mask_pend_int_31_Outp_s;
logic   mask_pend_int_26_Outp_s;
logic   mask_pend_int_23_Outp_s;
logic   mask_pend_int_20_Outp_s;
logic   mask_pend_int_17_Outp_s;
logic   mask_pend_int_13_Outp_s;
logic   mask_pend_int_9_Outp_s;
logic   mask_pend_int_2_Outp_s;
logic   [7:0] CONCAT00_Outp_s;

logic   prio_7_Outp_s;
logic   prio_6_Outp_s;
logic   prio_5_Outp_s;
logic   prio_4_Outp_s;
logic   prio_3_Outp_s;
logic   prio_2_Outp_s;
logic   prio_1_Outp_s;
logic   prio_0_Outp_s;

assign NOT01_Outp_s = ~((~(int_ended & (| {active_int_2,active_int_9,active_int_13,active_int_17,active_int_20,active_int_23,active_int_26,active_int_31}))) & (| {req_int_2,req_int_9,req_int_13,req_int_17,req_int_20,req_int_23,req_int_26,req_int_31}));

assign CONCAT07_Outp_s = {(sel_prio_int_31 == 3'b111 ? 1'b1 : 1'b0),(sel_prio_int_26 == 3'b111 ? 1'b1 : 1'b0),(sel_prio_int_23 == 3'b111 ? 1'b1 : 1'b0),(sel_prio_int_20 == 3'b111 ? 1'b1 : 1'b0),(sel_prio_int_17 == 3'b111 ? 1'b1 : 1'b0),(sel_prio_int_13 == 3'b111 ? 1'b1 : 1'b0),(sel_prio_int_9 == 3'b111 ? 1'b1 : 1'b0),(sel_prio_int_2 == 3'b111 ? 1'b1 : 1'b0)};

assign CONCAT06_Outp_s = {(sel_prio_int_31 == 3'b110 ? 1'b1 : 1'b0),(sel_prio_int_26 == 3'b110 ? 1'b1 : 1'b0),(sel_prio_int_23 == 3'b110 ? 1'b1 : 1'b0),(sel_prio_int_20 == 3'b110 ? 1'b1 : 1'b0),(sel_prio_int_17 == 3'b110 ? 1'b1 : 1'b0),(sel_prio_int_13 == 3'b110 ? 1'b1 : 1'b0),(sel_prio_int_9 == 3'b110 ? 1'b1 : 1'b0),(sel_prio_int_2 == 3'b110 ? 1'b1 : 1'b0)};

assign CONCAT05_Outp_s = {(sel_prio_int_31 == 3'b101 ? 1'b1 : 1'b0),(sel_prio_int_26 == 3'b101 ? 1'b1 : 1'b0),(sel_prio_int_23 == 3'b101 ? 1'b1 : 1'b0),(sel_prio_int_20 == 3'b101 ? 1'b1 : 1'b0),(sel_prio_int_17 == 3'b101 ? 1'b1 : 1'b0),(sel_prio_int_13 == 3'b101 ? 1'b1 : 1'b0),(sel_prio_int_9 == 3'b101 ? 1'b1 : 1'b0),(sel_prio_int_2 == 3'b101 ? 1'b1 : 1'b0)};

assign CONCAT04_Outp_s = {(sel_prio_int_31 == 3'b100 ? 1'b1 : 1'b0),(sel_prio_int_26 == 3'b100 ? 1'b1 : 1'b0),(sel_prio_int_23 == 3'b100 ? 1'b1 : 1'b0),(sel_prio_int_20 == 3'b100 ? 1'b1 : 1'b0),(sel_prio_int_17 == 3'b100 ? 1'b1 : 1'b0),(sel_prio_int_13 == 3'b100 ? 1'b1 : 1'b0),(sel_prio_int_9 == 3'b100 ? 1'b1 : 1'b0),(sel_prio_int_2 == 3'b100 ? 1'b1 : 1'b0)};

assign CONCAT03_Outp_s = {(sel_prio_int_31 == 3'b11 ? 1'b1 : 1'b0),(sel_prio_int_26 == 3'b11 ? 1'b1 : 1'b0),(sel_prio_int_23 == 3'b11 ? 1'b1 : 1'b0),(sel_prio_int_20 == 3'b11 ? 1'b1 : 1'b0),(sel_prio_int_17 == 3'b11 ? 1'b1 : 1'b0),(sel_prio_int_13 == 3'b11 ? 1'b1 : 1'b0),(sel_prio_int_9 == 3'b11 ? 1'b1 : 1'b0),(sel_prio_int_2 == 3'b11 ? 1'b1 : 1'b0)};

assign CONCAT02_Outp_s = {(sel_prio_int_31 == 3'b10 ? 1'b1 : 1'b0),(sel_prio_int_26 == 3'b10 ? 1'b1 : 1'b0),(sel_prio_int_23 == 3'b10 ? 1'b1 : 1'b0),(sel_prio_int_20 == 3'b10 ? 1'b1 : 1'b0),(sel_prio_int_17 == 3'b10 ? 1'b1 : 1'b0),(sel_prio_int_13 == 3'b10 ? 1'b1 : 1'b0),(sel_prio_int_9 == 3'b10 ? 1'b1 : 1'b0),(sel_prio_int_2 == 3'b10 ? 1'b1 : 1'b0)};

assign CONCAT01_Outp_s = {(sel_prio_int_31 == 3'b1 ? 1'b1 : 1'b0),(sel_prio_int_26 == 3'b1 ? 1'b1 : 1'b0),(sel_prio_int_23 == 3'b1 ? 1'b1 : 1'b0),(sel_prio_int_20 == 3'b1 ? 1'b1 : 1'b0),(sel_prio_int_17 == 3'b1 ? 1'b1 : 1'b0),(sel_prio_int_13 == 3'b1 ? 1'b1 : 1'b0),(sel_prio_int_9 == 3'b1 ? 1'b1 : 1'b0),(sel_prio_int_2 == 3'b1 ? 1'b1 : 1'b0)};

assign mask_pend_int_31_Outp_s = pend_int_31 & (NOT01_Outp_s | req_int_31);

assign mask_pend_int_26_Outp_s = pend_int_26 & (NOT01_Outp_s | req_int_26);

assign mask_pend_int_23_Outp_s = pend_int_23 & (NOT01_Outp_s | req_int_23);

assign mask_pend_int_20_Outp_s = pend_int_20 & (NOT01_Outp_s | req_int_20);

assign mask_pend_int_17_Outp_s = pend_int_17 & (NOT01_Outp_s | req_int_17);

assign mask_pend_int_13_Outp_s = pend_int_13 & (NOT01_Outp_s | req_int_13);

assign mask_pend_int_9_Outp_s = pend_int_9 & (NOT01_Outp_s | req_int_9);

assign mask_pend_int_2_Outp_s = pend_int_2 & (NOT01_Outp_s | req_int_2);

assign CONCAT00_Outp_s = {(sel_prio_int_31 == 3'b0 ? 1'b1 : 1'b0),(sel_prio_int_26 == 3'b0 ? 1'b1 : 1'b0),(sel_prio_int_23 == 3'b0 ? 1'b1 : 1'b0),(sel_prio_int_20 == 3'b0 ? 1'b1 : 1'b0),(sel_prio_int_17 == 3'b0 ? 1'b1 : 1'b0),(sel_prio_int_13 == 3'b0 ? 1'b1 : 1'b0),(sel_prio_int_9 == 3'b0 ? 1'b1 : 1'b0),(sel_prio_int_2 == 3'b0 ? 1'b1 : 1'b0)};

always_comb
begin
    case (CONCAT07_Outp_s)
        8'b1 : prio_7_Outp_s = mask_pend_int_2_Outp_s;
        8'b10 : prio_7_Outp_s = mask_pend_int_9_Outp_s;
        8'b100 : prio_7_Outp_s = mask_pend_int_13_Outp_s;
        8'b1000 : prio_7_Outp_s = mask_pend_int_17_Outp_s;
        8'b10000 : prio_7_Outp_s = mask_pend_int_20_Outp_s;
        8'b100000 : prio_7_Outp_s = mask_pend_int_23_Outp_s;
        8'b1000000 : prio_7_Outp_s = mask_pend_int_26_Outp_s;
        8'b10000000 : prio_7_Outp_s = mask_pend_int_31_Outp_s;
        default : prio_7_Outp_s = 1'b0;
    endcase
end

always_comb
begin
    case (CONCAT06_Outp_s)
        8'b1 : prio_6_Outp_s = mask_pend_int_2_Outp_s;
        8'b10 : prio_6_Outp_s = mask_pend_int_9_Outp_s;
        8'b100 : prio_6_Outp_s = mask_pend_int_13_Outp_s;
        8'b1000 : prio_6_Outp_s = mask_pend_int_17_Outp_s;
        8'b10000 : prio_6_Outp_s = mask_pend_int_20_Outp_s;
        8'b100000 : prio_6_Outp_s = mask_pend_int_23_Outp_s;
        8'b1000000 : prio_6_Outp_s = mask_pend_int_26_Outp_s;
        8'b10000000 : prio_6_Outp_s = mask_pend_int_31_Outp_s;
        default : prio_6_Outp_s = 1'b0;
    endcase
end

always_comb
begin
    case (CONCAT05_Outp_s)
        8'b1 : prio_5_Outp_s = mask_pend_int_2_Outp_s;
        8'b10 : prio_5_Outp_s = mask_pend_int_9_Outp_s;
        8'b100 : prio_5_Outp_s = mask_pend_int_13_Outp_s;
        8'b1000 : prio_5_Outp_s = mask_pend_int_17_Outp_s;
        8'b10000 : prio_5_Outp_s = mask_pend_int_20_Outp_s;
        8'b100000 : prio_5_Outp_s = mask_pend_int_23_Outp_s;
        8'b1000000 : prio_5_Outp_s = mask_pend_int_26_Outp_s;
        8'b10000000 : prio_5_Outp_s = mask_pend_int_31_Outp_s;
        default : prio_5_Outp_s = 1'b0;
    endcase
end

always_comb
begin
    case (CONCAT04_Outp_s)
        8'b1 : prio_4_Outp_s = mask_pend_int_2_Outp_s;
        8'b10 : prio_4_Outp_s = mask_pend_int_9_Outp_s;
        8'b100 : prio_4_Outp_s = mask_pend_int_13_Outp_s;
        8'b1000 : prio_4_Outp_s = mask_pend_int_17_Outp_s;
        8'b10000 : prio_4_Outp_s = mask_pend_int_20_Outp_s;
        8'b100000 : prio_4_Outp_s = mask_pend_int_23_Outp_s;
        8'b1000000 : prio_4_Outp_s = mask_pend_int_26_Outp_s;
        8'b10000000 : prio_4_Outp_s = mask_pend_int_31_Outp_s;
        default : prio_4_Outp_s = 1'b0;
    endcase
end

always_comb
begin
    case (CONCAT03_Outp_s)
        8'b1 : prio_3_Outp_s = mask_pend_int_2_Outp_s;
        8'b10 : prio_3_Outp_s = mask_pend_int_9_Outp_s;
        8'b100 : prio_3_Outp_s = mask_pend_int_13_Outp_s;
        8'b1000 : prio_3_Outp_s = mask_pend_int_17_Outp_s;
        8'b10000 : prio_3_Outp_s = mask_pend_int_20_Outp_s;
        8'b100000 : prio_3_Outp_s = mask_pend_int_23_Outp_s;
        8'b1000000 : prio_3_Outp_s = mask_pend_int_26_Outp_s;
        8'b10000000 : prio_3_Outp_s = mask_pend_int_31_Outp_s;
        default : prio_3_Outp_s = 1'b0;
    endcase
end

always_comb
begin
    case (CONCAT02_Outp_s)
        8'b1 : prio_2_Outp_s = mask_pend_int_2_Outp_s;
        8'b10 : prio_2_Outp_s = mask_pend_int_9_Outp_s;
        8'b100 : prio_2_Outp_s = mask_pend_int_13_Outp_s;
        8'b1000 : prio_2_Outp_s = mask_pend_int_17_Outp_s;
        8'b10000 : prio_2_Outp_s = mask_pend_int_20_Outp_s;
        8'b100000 : prio_2_Outp_s = mask_pend_int_23_Outp_s;
        8'b1000000 : prio_2_Outp_s = mask_pend_int_26_Outp_s;
        8'b10000000 : prio_2_Outp_s = mask_pend_int_31_Outp_s;
        default : prio_2_Outp_s = 1'b0;
    endcase
end

always_comb
begin
    case (CONCAT01_Outp_s)
        8'b1 : prio_1_Outp_s = mask_pend_int_2_Outp_s;
        8'b10 : prio_1_Outp_s = mask_pend_int_9_Outp_s;
        8'b100 : prio_1_Outp_s = mask_pend_int_13_Outp_s;
        8'b1000 : prio_1_Outp_s = mask_pend_int_17_Outp_s;
        8'b10000 : prio_1_Outp_s = mask_pend_int_20_Outp_s;
        8'b100000 : prio_1_Outp_s = mask_pend_int_23_Outp_s;
        8'b1000000 : prio_1_Outp_s = mask_pend_int_26_Outp_s;
        8'b10000000 : prio_1_Outp_s = mask_pend_int_31_Outp_s;
        default : prio_1_Outp_s = 1'b0;
    endcase
end

always_comb
begin
    case (CONCAT00_Outp_s)
        8'b1 : prio_0_Outp_s = mask_pend_int_2_Outp_s;
        8'b10 : prio_0_Outp_s = mask_pend_int_9_Outp_s;
        8'b100 : prio_0_Outp_s = mask_pend_int_13_Outp_s;
        8'b1000 : prio_0_Outp_s = mask_pend_int_17_Outp_s;
        8'b10000 : prio_0_Outp_s = mask_pend_int_20_Outp_s;
        8'b100000 : prio_0_Outp_s = mask_pend_int_23_Outp_s;
        8'b1000000 : prio_0_Outp_s = mask_pend_int_26_Outp_s;
        8'b10000000 : prio_0_Outp_s = mask_pend_int_31_Outp_s;
        default : prio_0_Outp_s = 1'b0;
    endcase
end

InterruptController_Priority_Circuit comp_Priority_Circuit(
    .pend_LEVEL_0 ( prio_0_Outp_s ),
    .pend_LEVEL_1 ( prio_1_Outp_s ),
    .pend_LEVEL_2 ( prio_2_Outp_s ),
    .pend_LEVEL_3 ( prio_3_Outp_s ),
    .pend_LEVEL_4 ( prio_4_Outp_s ),
    .pend_LEVEL_5 ( prio_5_Outp_s ),
    .pend_LEVEL_6 ( prio_6_Outp_s ),
    .pend_LEVEL_7 ( prio_7_Outp_s ),
    .prio_LEVEL_0 ( prio_0        ),
    .prio_LEVEL_1 ( prio_1        ),
    .prio_LEVEL_2 ( prio_2        ),
    .prio_LEVEL_3 ( prio_3        ),
    .prio_LEVEL_4 ( prio_4        ),
    .prio_LEVEL_5 ( prio_5        ),
    .prio_LEVEL_6 ( prio_6        ),
    .prio_LEVEL_7 ( prio_7        )
);


endmodule

