/* ===============================================================
Copyright 2026, Infineon Technologies AG or an 
affiliate of Infineon Technologies AG.  All rights reserved.
 
This software, associated documentation and materials ("Software") is owned by
Infineon Technologies AG or one of its affiliates ("Infineon") and is 
protected by and subject to worldwide patent protection (United States and 
foreign), United States copyright laws and international treaty provisions. 
Therefore, you may use this Software only as provided in the license agreement
accompanying the software package from which you obtained this 
Software ("EULA"). If no EULA applies, then any reproduction, modification, 
translation, compilation, or representation of this Software is prohibited 
without the express written permission of Infineon.
 
Disclaimer: THIS SOFTWARE IS PROVIDED AS-IS, WITH NO WARRANTY OF 
ANY KIND, EXPRESS OR IMPLIED, INCLUDING, BUT NOT LIMITED TO, 
NONINFRINGEMENT, IMPLIED WARRANTIES OF  MERCHANTABILITY AND
FITNESS FOR A PARTICULAR PURPOSE.  Infineon reserves the right to make
changes to the Software without notice. Infineon does not assume any liability
arising out of the application or use of the Software or any product or 
circuit described in the Software. Infineon does not authorize its products 
for use in any products where a malfunction or failure of the Infineon product 
may reasonably be expected to result in significant property damage, injury or
death ("High Risk Product").  By including Infineon 's product in a High Risk 
Product, the manufacturer of such system or application assumes all risk of 
such use and in doing so agrees to indemnify Infineon against all liability.

 ===============================================================
*/ 
// File : InterruptController_ICcomponent_PRIO_RESOLUTION.sv 
// Author : tahiraga 
// Date : 18:22:21    21/09/2026 
// Revision :  
// =============================================================== 
// Description : 
/*
---- Auto Generated by MetaRTL , a MetaGen application
---- Contact: ParitoshKumar.Sinha@infineon.com
---- Contact: Yash.Ranjan@infineon.com
===============================================================
*/


module InterruptController_ICcomponent_PRIO_RESOLUTION (
    input pend_int_0,
    output chosen_int_0,
    input [2:0] int_0_prio,
    input req_int_0,
    input active_int_0,
    input pend_int_1,
    output chosen_int_1,
    input [2:0] int_1_prio,
    input req_int_1,
    input active_int_1,
    input pend_int_2,
    output chosen_int_2,
    input [2:0] int_2_prio,
    input req_int_2,
    input active_int_2,
    input pend_int_3,
    output chosen_int_3,
    input [2:0] int_3_prio,
    input req_int_3,
    input active_int_3,
    input pend_int_4,
    output chosen_int_4,
    input [2:0] int_4_prio,
    input req_int_4,
    input active_int_4,
    input pend_int_5,
    output chosen_int_5,
    input [2:0] int_5_prio,
    input req_int_5,
    input active_int_5,
    input pend_int_6,
    output chosen_int_6,
    input [2:0] int_6_prio,
    input req_int_6,
    input active_int_6,
    input pend_int_7,
    output chosen_int_7,
    input [2:0] int_7_prio,
    input req_int_7,
    input active_int_7,
    input pend_int_8,
    output chosen_int_8,
    input [2:0] int_8_prio,
    input req_int_8,
    input active_int_8,
    input pend_int_9,
    output chosen_int_9,
    input [2:0] int_9_prio,
    input req_int_9,
    input active_int_9,
    input pend_int_10,
    output chosen_int_10,
    input [2:0] int_10_prio,
    input req_int_10,
    input active_int_10,
    input pend_int_11,
    output chosen_int_11,
    input [2:0] int_11_prio,
    input req_int_11,
    input active_int_11,
    input pend_int_12,
    output chosen_int_12,
    input [2:0] int_12_prio,
    input req_int_12,
    input active_int_12,
    input pend_int_13,
    output chosen_int_13,
    input [2:0] int_13_prio,
    input req_int_13,
    input active_int_13,
    input pend_int_14,
    output chosen_int_14,
    input [2:0] int_14_prio,
    input req_int_14,
    input active_int_14,
    input pend_int_15,
    output chosen_int_15,
    input [2:0] int_15_prio,
    input req_int_15,
    input active_int_15,
    input pend_int_16,
    output chosen_int_16,
    input [2:0] int_16_prio,
    input req_int_16,
    input active_int_16,
    input pend_int_17,
    output chosen_int_17,
    input [2:0] int_17_prio,
    input req_int_17,
    input active_int_17,
    input pend_int_18,
    output chosen_int_18,
    input [2:0] int_18_prio,
    input req_int_18,
    input active_int_18,
    input pend_int_19,
    output chosen_int_19,
    input [2:0] int_19_prio,
    input req_int_19,
    input active_int_19,
    input pend_int_20,
    output chosen_int_20,
    input [2:0] int_20_prio,
    input req_int_20,
    input active_int_20,
    input pend_int_21,
    output chosen_int_21,
    input [2:0] int_21_prio,
    input req_int_21,
    input active_int_21,
    input pend_int_22,
    output chosen_int_22,
    input [2:0] int_22_prio,
    input req_int_22,
    input active_int_22,
    input pend_int_23,
    output chosen_int_23,
    input [2:0] int_23_prio,
    input req_int_23,
    input active_int_23,
    input pend_int_24,
    output chosen_int_24,
    input [2:0] int_24_prio,
    input req_int_24,
    input active_int_24,
    input pend_int_25,
    output chosen_int_25,
    input [2:0] int_25_prio,
    input req_int_25,
    input active_int_25,
    input pend_int_26,
    output chosen_int_26,
    input [2:0] int_26_prio,
    input req_int_26,
    input active_int_26,
    input pend_int_27,
    output chosen_int_27,
    input [2:0] int_27_prio,
    input req_int_27,
    input active_int_27,
    input pend_int_28,
    output chosen_int_28,
    input [2:0] int_28_prio,
    input req_int_28,
    input active_int_28,
    input pend_int_29,
    output chosen_int_29,
    input [2:0] int_29_prio,
    input req_int_29,
    input active_int_29,
    input pend_int_30,
    output chosen_int_30,
    input [2:0] int_30_prio,
    input req_int_30,
    input active_int_30,
    input pend_int_31,
    output chosen_int_31,
    input [2:0] int_31_prio,
    input req_int_31,
    input active_int_31,
    input pend_NMI,
    output chosen_NMI,
    input req_NMI,
    input active_NMI,
    input [1:0] Group1_prio,
    input [1:0] Group2_prio,
    input [1:0] Group3_prio,
    input [1:0] Group4_prio,
    input int_ended,
    input nmi_ended
);

logic   Grouping_Priority_Circuit02_prio_0_s;
logic   Grouping_Priority_Circuit02_prio_1_s;
logic   Grouping_Priority_Circuit02_prio_2_s;
logic   Grouping_Priority_Circuit02_prio_3_s;
logic   Grouping_Priority_Circuit02_prio_4_s;
logic   Grouping_Priority_Circuit02_prio_5_s;
logic   Grouping_Priority_Circuit02_prio_6_s;
logic   Grouping_Priority_Circuit02_prio_7_s;
logic   Grouping_Priority_Circuit01_prio_0_s;
logic   Grouping_Priority_Circuit01_prio_1_s;
logic   Grouping_Priority_Circuit01_prio_2_s;
logic   Grouping_Priority_Circuit01_prio_3_s;
logic   Grouping_Priority_Circuit01_prio_4_s;
logic   Grouping_Priority_Circuit01_prio_5_s;
logic   Grouping_Priority_Circuit01_prio_6_s;
logic   Grouping_Priority_Circuit01_prio_7_s;
logic   Grouping_Priority_Circuit00_prio_0_s;
logic   Grouping_Priority_Circuit00_prio_1_s;
logic   Grouping_Priority_Circuit00_prio_2_s;
logic   Grouping_Priority_Circuit00_prio_3_s;
logic   Grouping_Priority_Circuit00_prio_4_s;
logic   Grouping_Priority_Circuit00_prio_5_s;
logic   Grouping_Priority_Circuit00_prio_6_s;
logic   Grouping_Priority_Circuit00_prio_7_s;
logic   [3:0] CONCAT03_Outp_s;
logic   [3:0] CONCAT02_Outp_s;
logic   [3:0] CONCAT01_Outp_s;
logic   Group4_has_pend_int_Outp_s;
logic   Group3_has_pend_int_Outp_s;
logic   Group2_has_pend_int_Outp_s;
logic   Group1_has_pend_int_Outp_s;
logic   [3:0] CONCAT00_Outp_s;
logic   has_pending_nmi_Outp_s;
logic   Priority_Circuit_prio_LEVEL_0_s;
logic   Priority_Circuit_prio_LEVEL_1_s;
logic   Priority_Circuit_prio_LEVEL_2_s;
logic   Priority_Circuit_prio_LEVEL_3_s;
logic   Grouping_Priority_Circuit03_prio_0_s;
logic   Grouping_Priority_Circuit03_prio_1_s;
logic   Grouping_Priority_Circuit03_prio_2_s;
logic   Grouping_Priority_Circuit03_prio_3_s;
logic   Grouping_Priority_Circuit03_prio_4_s;
logic   Grouping_Priority_Circuit03_prio_5_s;
logic   Grouping_Priority_Circuit03_prio_6_s;
logic   Grouping_Priority_Circuit03_prio_7_s;

logic   LEVEL_reverse_mux_1_Outp_s;
logic   LEVEL_reverse_mux_2_Outp_s;
logic   LEVEL_reverse_mux_0_Outp_s;
logic   prio_3_Outp_s;
logic   prio_2_Outp_s;
logic   prio_1_Outp_s;
logic   prio_0_Outp_s;
logic   LEVEL_reverse_mux_3_Outp_s;

always_comb
begin
    case (Group2_prio)
        2'b0 : LEVEL_reverse_mux_1_Outp_s = Priority_Circuit_prio_LEVEL_0_s;
        2'b1 : LEVEL_reverse_mux_1_Outp_s = Priority_Circuit_prio_LEVEL_1_s;
        2'b10 : LEVEL_reverse_mux_1_Outp_s = Priority_Circuit_prio_LEVEL_2_s;
        2'b11 : LEVEL_reverse_mux_1_Outp_s = Priority_Circuit_prio_LEVEL_3_s;
        default : LEVEL_reverse_mux_1_Outp_s = 1'b0;
    endcase
end

InterruptController_ICcomponent_PRIO_RESOLUTION_Regrouping_Priority_Circuit01 comp_Regrouping_Priority_Circuit01(
    .pend_bit                              ( LEVEL_reverse_mux_1_Outp_s           ),
    .Grouping_Priority_Circuit01_prio_0_in ( Grouping_Priority_Circuit01_prio_0_s ),
    .Grouping_Priority_Circuit01_prio_1_in ( Grouping_Priority_Circuit01_prio_1_s ),
    .Grouping_Priority_Circuit01_prio_2_in ( Grouping_Priority_Circuit01_prio_2_s ),
    .Grouping_Priority_Circuit01_prio_3_in ( Grouping_Priority_Circuit01_prio_3_s ),
    .Grouping_Priority_Circuit01_prio_4_in ( Grouping_Priority_Circuit01_prio_4_s ),
    .Grouping_Priority_Circuit01_prio_5_in ( Grouping_Priority_Circuit01_prio_5_s ),
    .Grouping_Priority_Circuit01_prio_6_in ( Grouping_Priority_Circuit01_prio_6_s ),
    .Grouping_Priority_Circuit01_prio_7_in ( Grouping_Priority_Circuit01_prio_7_s ),
    .int_5_prio                            ( int_5_prio                           ),
    .int_8_prio                            ( int_8_prio                           ),
    .int_12_prio                           ( int_12_prio                          ),
    .int_16_prio                           ( int_16_prio                          ),
    .int_22_prio                           ( int_22_prio                          ),
    .int_25_prio                           ( int_25_prio                          ),
    .int_29_prio                           ( int_29_prio                          ),
    .int_30_prio                           ( int_30_prio                          ),
    .int_5_out                             ( chosen_int_5                         ),
    .int_8_out                             ( chosen_int_8                         ),
    .int_12_out                            ( chosen_int_12                        ),
    .int_16_out                            ( chosen_int_16                        ),
    .int_22_out                            ( chosen_int_22                        ),
    .int_25_out                            ( chosen_int_25                        ),
    .int_29_out                            ( chosen_int_29                        ),
    .int_30_out                            ( chosen_int_30                        )
);

always_comb
begin
    case (Group3_prio)
        2'b0 : LEVEL_reverse_mux_2_Outp_s = Priority_Circuit_prio_LEVEL_0_s;
        2'b1 : LEVEL_reverse_mux_2_Outp_s = Priority_Circuit_prio_LEVEL_1_s;
        2'b10 : LEVEL_reverse_mux_2_Outp_s = Priority_Circuit_prio_LEVEL_2_s;
        2'b11 : LEVEL_reverse_mux_2_Outp_s = Priority_Circuit_prio_LEVEL_3_s;
        default : LEVEL_reverse_mux_2_Outp_s = 1'b0;
    endcase
end

InterruptController_ICcomponent_PRIO_RESOLUTION_Regrouping_Priority_Circuit02 comp_Regrouping_Priority_Circuit02(
    .pend_bit                              ( LEVEL_reverse_mux_2_Outp_s           ),
    .Grouping_Priority_Circuit02_prio_0_in ( Grouping_Priority_Circuit02_prio_0_s ),
    .Grouping_Priority_Circuit02_prio_1_in ( Grouping_Priority_Circuit02_prio_1_s ),
    .Grouping_Priority_Circuit02_prio_2_in ( Grouping_Priority_Circuit02_prio_2_s ),
    .Grouping_Priority_Circuit02_prio_3_in ( Grouping_Priority_Circuit02_prio_3_s ),
    .Grouping_Priority_Circuit02_prio_4_in ( Grouping_Priority_Circuit02_prio_4_s ),
    .Grouping_Priority_Circuit02_prio_5_in ( Grouping_Priority_Circuit02_prio_5_s ),
    .Grouping_Priority_Circuit02_prio_6_in ( Grouping_Priority_Circuit02_prio_6_s ),
    .Grouping_Priority_Circuit02_prio_7_in ( Grouping_Priority_Circuit02_prio_7_s ),
    .int_2_prio                            ( int_2_prio                           ),
    .int_9_prio                            ( int_9_prio                           ),
    .int_13_prio                           ( int_13_prio                          ),
    .int_17_prio                           ( int_17_prio                          ),
    .int_20_prio                           ( int_20_prio                          ),
    .int_23_prio                           ( int_23_prio                          ),
    .int_26_prio                           ( int_26_prio                          ),
    .int_31_prio                           ( int_31_prio                          ),
    .int_2_out                             ( chosen_int_2                         ),
    .int_9_out                             ( chosen_int_9                         ),
    .int_13_out                            ( chosen_int_13                        ),
    .int_17_out                            ( chosen_int_17                        ),
    .int_20_out                            ( chosen_int_20                        ),
    .int_23_out                            ( chosen_int_23                        ),
    .int_26_out                            ( chosen_int_26                        ),
    .int_31_out                            ( chosen_int_31                        )
);

always_comb
begin
    case (Group1_prio)
        2'b0 : LEVEL_reverse_mux_0_Outp_s = Priority_Circuit_prio_LEVEL_0_s;
        2'b1 : LEVEL_reverse_mux_0_Outp_s = Priority_Circuit_prio_LEVEL_1_s;
        2'b10 : LEVEL_reverse_mux_0_Outp_s = Priority_Circuit_prio_LEVEL_2_s;
        2'b11 : LEVEL_reverse_mux_0_Outp_s = Priority_Circuit_prio_LEVEL_3_s;
        default : LEVEL_reverse_mux_0_Outp_s = 1'b0;
    endcase
end

InterruptController_ICcomponent_PRIO_RESOLUTION_Regrouping_Priority_Circuit00 comp_Regrouping_Priority_Circuit00(
    .pend_bit                              ( LEVEL_reverse_mux_0_Outp_s           ),
    .Grouping_Priority_Circuit00_prio_0_in ( Grouping_Priority_Circuit00_prio_0_s ),
    .Grouping_Priority_Circuit00_prio_1_in ( Grouping_Priority_Circuit00_prio_1_s ),
    .Grouping_Priority_Circuit00_prio_2_in ( Grouping_Priority_Circuit00_prio_2_s ),
    .Grouping_Priority_Circuit00_prio_3_in ( Grouping_Priority_Circuit00_prio_3_s ),
    .Grouping_Priority_Circuit00_prio_4_in ( Grouping_Priority_Circuit00_prio_4_s ),
    .Grouping_Priority_Circuit00_prio_5_in ( Grouping_Priority_Circuit00_prio_5_s ),
    .Grouping_Priority_Circuit00_prio_6_in ( Grouping_Priority_Circuit00_prio_6_s ),
    .Grouping_Priority_Circuit00_prio_7_in ( Grouping_Priority_Circuit00_prio_7_s ),
    .int_1_prio                            ( int_1_prio                           ),
    .int_4_prio                            ( int_4_prio                           ),
    .int_7_prio                            ( int_7_prio                           ),
    .int_11_prio                           ( int_11_prio                          ),
    .int_15_prio                           ( int_15_prio                          ),
    .int_19_prio                           ( int_19_prio                          ),
    .int_21_prio                           ( int_21_prio                          ),
    .int_28_prio                           ( int_28_prio                          ),
    .int_1_out                             ( chosen_int_1                         ),
    .int_4_out                             ( chosen_int_4                         ),
    .int_7_out                             ( chosen_int_7                         ),
    .int_11_out                            ( chosen_int_11                        ),
    .int_15_out                            ( chosen_int_15                        ),
    .int_19_out                            ( chosen_int_19                        ),
    .int_21_out                            ( chosen_int_21                        ),
    .int_28_out                            ( chosen_int_28                        )
);

InterruptController_ICcomponent_PRIO_RESOLUTION_Grouping_Priority_Circuit02 comp_Grouping_Priority_Circuit02(
    .pend_int_2      ( pend_int_2                           ),
    .req_int_2       ( req_int_2                            ),
    .active_int_2    ( active_int_2                         ),
    .sel_prio_int_2  ( int_2_prio                           ),
    .pend_int_9      ( pend_int_9                           ),
    .req_int_9       ( req_int_9                            ),
    .active_int_9    ( active_int_9                         ),
    .sel_prio_int_9  ( int_9_prio                           ),
    .pend_int_13     ( pend_int_13                          ),
    .req_int_13      ( req_int_13                           ),
    .active_int_13   ( active_int_13                        ),
    .sel_prio_int_13 ( int_13_prio                          ),
    .pend_int_17     ( pend_int_17                          ),
    .req_int_17      ( req_int_17                           ),
    .active_int_17   ( active_int_17                        ),
    .sel_prio_int_17 ( int_17_prio                          ),
    .pend_int_20     ( pend_int_20                          ),
    .req_int_20      ( req_int_20                           ),
    .active_int_20   ( active_int_20                        ),
    .sel_prio_int_20 ( int_20_prio                          ),
    .pend_int_23     ( pend_int_23                          ),
    .req_int_23      ( req_int_23                           ),
    .active_int_23   ( active_int_23                        ),
    .sel_prio_int_23 ( int_23_prio                          ),
    .pend_int_26     ( pend_int_26                          ),
    .req_int_26      ( req_int_26                           ),
    .active_int_26   ( active_int_26                        ),
    .sel_prio_int_26 ( int_26_prio                          ),
    .pend_int_31     ( pend_int_31                          ),
    .req_int_31      ( req_int_31                           ),
    .active_int_31   ( active_int_31                        ),
    .sel_prio_int_31 ( int_31_prio                          ),
    .int_ended       ( int_ended                            ),
    .prio_0          ( Grouping_Priority_Circuit02_prio_0_s ),
    .prio_1          ( Grouping_Priority_Circuit02_prio_1_s ),
    .prio_2          ( Grouping_Priority_Circuit02_prio_2_s ),
    .prio_3          ( Grouping_Priority_Circuit02_prio_3_s ),
    .prio_4          ( Grouping_Priority_Circuit02_prio_4_s ),
    .prio_5          ( Grouping_Priority_Circuit02_prio_5_s ),
    .prio_6          ( Grouping_Priority_Circuit02_prio_6_s ),
    .prio_7          ( Grouping_Priority_Circuit02_prio_7_s )
);

InterruptController_ICcomponent_PRIO_RESOLUTION_Grouping_Priority_Circuit01 comp_Grouping_Priority_Circuit01(
    .pend_int_5      ( pend_int_5                           ),
    .req_int_5       ( req_int_5                            ),
    .active_int_5    ( active_int_5                         ),
    .sel_prio_int_5  ( int_5_prio                           ),
    .pend_int_8      ( pend_int_8                           ),
    .req_int_8       ( req_int_8                            ),
    .active_int_8    ( active_int_8                         ),
    .sel_prio_int_8  ( int_8_prio                           ),
    .pend_int_12     ( pend_int_12                          ),
    .req_int_12      ( req_int_12                           ),
    .active_int_12   ( active_int_12                        ),
    .sel_prio_int_12 ( int_12_prio                          ),
    .pend_int_16     ( pend_int_16                          ),
    .req_int_16      ( req_int_16                           ),
    .active_int_16   ( active_int_16                        ),
    .sel_prio_int_16 ( int_16_prio                          ),
    .pend_int_22     ( pend_int_22                          ),
    .req_int_22      ( req_int_22                           ),
    .active_int_22   ( active_int_22                        ),
    .sel_prio_int_22 ( int_22_prio                          ),
    .pend_int_25     ( pend_int_25                          ),
    .req_int_25      ( req_int_25                           ),
    .active_int_25   ( active_int_25                        ),
    .sel_prio_int_25 ( int_25_prio                          ),
    .pend_int_29     ( pend_int_29                          ),
    .req_int_29      ( req_int_29                           ),
    .active_int_29   ( active_int_29                        ),
    .sel_prio_int_29 ( int_29_prio                          ),
    .pend_int_30     ( pend_int_30                          ),
    .req_int_30      ( req_int_30                           ),
    .active_int_30   ( active_int_30                        ),
    .sel_prio_int_30 ( int_30_prio                          ),
    .int_ended       ( int_ended                            ),
    .prio_0          ( Grouping_Priority_Circuit01_prio_0_s ),
    .prio_1          ( Grouping_Priority_Circuit01_prio_1_s ),
    .prio_2          ( Grouping_Priority_Circuit01_prio_2_s ),
    .prio_3          ( Grouping_Priority_Circuit01_prio_3_s ),
    .prio_4          ( Grouping_Priority_Circuit01_prio_4_s ),
    .prio_5          ( Grouping_Priority_Circuit01_prio_5_s ),
    .prio_6          ( Grouping_Priority_Circuit01_prio_6_s ),
    .prio_7          ( Grouping_Priority_Circuit01_prio_7_s )
);

InterruptController_ICcomponent_PRIO_RESOLUTION_Grouping_Priority_Circuit00 comp_Grouping_Priority_Circuit00(
    .pend_int_1      ( pend_int_1                           ),
    .req_int_1       ( req_int_1                            ),
    .active_int_1    ( active_int_1                         ),
    .sel_prio_int_1  ( int_1_prio                           ),
    .pend_int_4      ( pend_int_4                           ),
    .req_int_4       ( req_int_4                            ),
    .active_int_4    ( active_int_4                         ),
    .sel_prio_int_4  ( int_4_prio                           ),
    .pend_int_7      ( pend_int_7                           ),
    .req_int_7       ( req_int_7                            ),
    .active_int_7    ( active_int_7                         ),
    .sel_prio_int_7  ( int_7_prio                           ),
    .pend_int_11     ( pend_int_11                          ),
    .req_int_11      ( req_int_11                           ),
    .active_int_11   ( active_int_11                        ),
    .sel_prio_int_11 ( int_11_prio                          ),
    .pend_int_15     ( pend_int_15                          ),
    .req_int_15      ( req_int_15                           ),
    .active_int_15   ( active_int_15                        ),
    .sel_prio_int_15 ( int_15_prio                          ),
    .pend_int_19     ( pend_int_19                          ),
    .req_int_19      ( req_int_19                           ),
    .active_int_19   ( active_int_19                        ),
    .sel_prio_int_19 ( int_19_prio                          ),
    .pend_int_21     ( pend_int_21                          ),
    .req_int_21      ( req_int_21                           ),
    .active_int_21   ( active_int_21                        ),
    .sel_prio_int_21 ( int_21_prio                          ),
    .pend_int_28     ( pend_int_28                          ),
    .req_int_28      ( req_int_28                           ),
    .active_int_28   ( active_int_28                        ),
    .sel_prio_int_28 ( int_28_prio                          ),
    .int_ended       ( int_ended                            ),
    .prio_0          ( Grouping_Priority_Circuit00_prio_0_s ),
    .prio_1          ( Grouping_Priority_Circuit00_prio_1_s ),
    .prio_2          ( Grouping_Priority_Circuit00_prio_2_s ),
    .prio_3          ( Grouping_Priority_Circuit00_prio_3_s ),
    .prio_4          ( Grouping_Priority_Circuit00_prio_4_s ),
    .prio_5          ( Grouping_Priority_Circuit00_prio_5_s ),
    .prio_6          ( Grouping_Priority_Circuit00_prio_6_s ),
    .prio_7          ( Grouping_Priority_Circuit00_prio_7_s )
);

assign CONCAT03_Outp_s = {(Group4_prio == 2'b11 ? 1'b1 : 1'b0),(Group3_prio == 2'b11 ? 1'b1 : 1'b0),(Group2_prio == 2'b11 ? 1'b1 : 1'b0),(Group1_prio == 2'b11 ? 1'b1 : 1'b0)};

assign CONCAT02_Outp_s = {(Group4_prio == 2'b10 ? 1'b1 : 1'b0),(Group3_prio == 2'b10 ? 1'b1 : 1'b0),(Group2_prio == 2'b10 ? 1'b1 : 1'b0),(Group1_prio == 2'b10 ? 1'b1 : 1'b0)};

assign CONCAT01_Outp_s = {(Group4_prio == 2'b1 ? 1'b1 : 1'b0),(Group3_prio == 2'b1 ? 1'b1 : 1'b0),(Group2_prio == 2'b1 ? 1'b1 : 1'b0),(Group1_prio == 2'b1 ? 1'b1 : 1'b0)};

assign Group4_has_pend_int_Outp_s = Grouping_Priority_Circuit03_prio_0_s | Grouping_Priority_Circuit03_prio_1_s | Grouping_Priority_Circuit03_prio_2_s | Grouping_Priority_Circuit03_prio_3_s | Grouping_Priority_Circuit03_prio_4_s | Grouping_Priority_Circuit03_prio_5_s | Grouping_Priority_Circuit03_prio_6_s | Grouping_Priority_Circuit03_prio_7_s;

assign Group3_has_pend_int_Outp_s = Grouping_Priority_Circuit02_prio_0_s | Grouping_Priority_Circuit02_prio_1_s | Grouping_Priority_Circuit02_prio_2_s | Grouping_Priority_Circuit02_prio_3_s | Grouping_Priority_Circuit02_prio_4_s | Grouping_Priority_Circuit02_prio_5_s | Grouping_Priority_Circuit02_prio_6_s | Grouping_Priority_Circuit02_prio_7_s;

assign Group2_has_pend_int_Outp_s = Grouping_Priority_Circuit01_prio_0_s | Grouping_Priority_Circuit01_prio_1_s | Grouping_Priority_Circuit01_prio_2_s | Grouping_Priority_Circuit01_prio_3_s | Grouping_Priority_Circuit01_prio_4_s | Grouping_Priority_Circuit01_prio_5_s | Grouping_Priority_Circuit01_prio_6_s | Grouping_Priority_Circuit01_prio_7_s;

assign Group1_has_pend_int_Outp_s = Grouping_Priority_Circuit00_prio_0_s | Grouping_Priority_Circuit00_prio_1_s | Grouping_Priority_Circuit00_prio_2_s | Grouping_Priority_Circuit00_prio_3_s | Grouping_Priority_Circuit00_prio_4_s | Grouping_Priority_Circuit00_prio_5_s | Grouping_Priority_Circuit00_prio_6_s | Grouping_Priority_Circuit00_prio_7_s;

assign CONCAT00_Outp_s = {(Group4_prio == 2'b0 ? 1'b1 : 1'b0),(Group3_prio == 2'b0 ? 1'b1 : 1'b0),(Group2_prio == 2'b0 ? 1'b1 : 1'b0),(Group1_prio == 2'b0 ? 1'b1 : 1'b0)};

always_comb
begin
    case (CONCAT03_Outp_s)
        4'b1 : prio_3_Outp_s = Group1_has_pend_int_Outp_s;
        4'b10 : prio_3_Outp_s = Group2_has_pend_int_Outp_s;
        4'b100 : prio_3_Outp_s = Group3_has_pend_int_Outp_s;
        4'b1000 : prio_3_Outp_s = Group4_has_pend_int_Outp_s;
        default : prio_3_Outp_s = 1'b0;
    endcase
end

always_comb
begin
    case (CONCAT02_Outp_s)
        4'b1 : prio_2_Outp_s = Group1_has_pend_int_Outp_s;
        4'b10 : prio_2_Outp_s = Group2_has_pend_int_Outp_s;
        4'b100 : prio_2_Outp_s = Group3_has_pend_int_Outp_s;
        4'b1000 : prio_2_Outp_s = Group4_has_pend_int_Outp_s;
        default : prio_2_Outp_s = 1'b0;
    endcase
end

always_comb
begin
    case (CONCAT01_Outp_s)
        4'b1 : prio_1_Outp_s = Group1_has_pend_int_Outp_s;
        4'b10 : prio_1_Outp_s = Group2_has_pend_int_Outp_s;
        4'b100 : prio_1_Outp_s = Group3_has_pend_int_Outp_s;
        4'b1000 : prio_1_Outp_s = Group4_has_pend_int_Outp_s;
        default : prio_1_Outp_s = 1'b0;
    endcase
end

always_comb
begin
    case (CONCAT00_Outp_s)
        4'b1 : prio_0_Outp_s = Group1_has_pend_int_Outp_s;
        4'b10 : prio_0_Outp_s = Group2_has_pend_int_Outp_s;
        4'b100 : prio_0_Outp_s = Group3_has_pend_int_Outp_s;
        4'b1000 : prio_0_Outp_s = Group4_has_pend_int_Outp_s;
        default : prio_0_Outp_s = 1'b0;
    endcase
end

assign has_pending_nmi_Outp_s = pend_NMI | 1'b0;

InterruptController_ICcomponent_PRIO_RESOLUTION_Priority_Circuit comp_Priority_Circuit(
    .nmi_pending  ( has_pending_nmi_Outp_s          ),
    .pend_LEVEL_0 ( prio_0_Outp_s                   ),
    .pend_LEVEL_1 ( prio_1_Outp_s                   ),
    .pend_LEVEL_2 ( prio_2_Outp_s                   ),
    .pend_LEVEL_3 ( prio_3_Outp_s                   ),
    .prio_LEVEL_0 ( Priority_Circuit_prio_LEVEL_0_s ),
    .prio_LEVEL_1 ( Priority_Circuit_prio_LEVEL_1_s ),
    .prio_LEVEL_2 ( Priority_Circuit_prio_LEVEL_2_s ),
    .prio_LEVEL_3 ( Priority_Circuit_prio_LEVEL_3_s )
);

InterruptController_ICcomponent_PRIO_RESOLUTION_Grouping_Priority_Circuit03 comp_Grouping_Priority_Circuit03(
    .pend_int_0      ( pend_int_0                           ),
    .req_int_0       ( req_int_0                            ),
    .active_int_0    ( active_int_0                         ),
    .sel_prio_int_0  ( int_0_prio                           ),
    .pend_int_3      ( pend_int_3                           ),
    .req_int_3       ( req_int_3                            ),
    .active_int_3    ( active_int_3                         ),
    .sel_prio_int_3  ( int_3_prio                           ),
    .pend_int_6      ( pend_int_6                           ),
    .req_int_6       ( req_int_6                            ),
    .active_int_6    ( active_int_6                         ),
    .sel_prio_int_6  ( int_6_prio                           ),
    .pend_int_10     ( pend_int_10                          ),
    .req_int_10      ( req_int_10                           ),
    .active_int_10   ( active_int_10                        ),
    .sel_prio_int_10 ( int_10_prio                          ),
    .pend_int_14     ( pend_int_14                          ),
    .req_int_14      ( req_int_14                           ),
    .active_int_14   ( active_int_14                        ),
    .sel_prio_int_14 ( int_14_prio                          ),
    .pend_int_18     ( pend_int_18                          ),
    .req_int_18      ( req_int_18                           ),
    .active_int_18   ( active_int_18                        ),
    .sel_prio_int_18 ( int_18_prio                          ),
    .pend_int_24     ( pend_int_24                          ),
    .req_int_24      ( req_int_24                           ),
    .active_int_24   ( active_int_24                        ),
    .sel_prio_int_24 ( int_24_prio                          ),
    .pend_int_27     ( pend_int_27                          ),
    .req_int_27      ( req_int_27                           ),
    .active_int_27   ( active_int_27                        ),
    .sel_prio_int_27 ( int_27_prio                          ),
    .int_ended       ( int_ended                            ),
    .prio_0          ( Grouping_Priority_Circuit03_prio_0_s ),
    .prio_1          ( Grouping_Priority_Circuit03_prio_1_s ),
    .prio_2          ( Grouping_Priority_Circuit03_prio_2_s ),
    .prio_3          ( Grouping_Priority_Circuit03_prio_3_s ),
    .prio_4          ( Grouping_Priority_Circuit03_prio_4_s ),
    .prio_5          ( Grouping_Priority_Circuit03_prio_5_s ),
    .prio_6          ( Grouping_Priority_Circuit03_prio_6_s ),
    .prio_7          ( Grouping_Priority_Circuit03_prio_7_s )
);

always_comb
begin
    case (Group4_prio)
        2'b0 : LEVEL_reverse_mux_3_Outp_s = Priority_Circuit_prio_LEVEL_0_s;
        2'b1 : LEVEL_reverse_mux_3_Outp_s = Priority_Circuit_prio_LEVEL_1_s;
        2'b10 : LEVEL_reverse_mux_3_Outp_s = Priority_Circuit_prio_LEVEL_2_s;
        2'b11 : LEVEL_reverse_mux_3_Outp_s = Priority_Circuit_prio_LEVEL_3_s;
        default : LEVEL_reverse_mux_3_Outp_s = 1'b0;
    endcase
end

InterruptController_ICcomponent_PRIO_RESOLUTION_Regrouping_Priority_Circuit03 comp_Regrouping_Priority_Circuit03(
    .pend_bit                              ( LEVEL_reverse_mux_3_Outp_s           ),
    .Grouping_Priority_Circuit03_prio_0_in ( Grouping_Priority_Circuit03_prio_0_s ),
    .Grouping_Priority_Circuit03_prio_1_in ( Grouping_Priority_Circuit03_prio_1_s ),
    .Grouping_Priority_Circuit03_prio_2_in ( Grouping_Priority_Circuit03_prio_2_s ),
    .Grouping_Priority_Circuit03_prio_3_in ( Grouping_Priority_Circuit03_prio_3_s ),
    .Grouping_Priority_Circuit03_prio_4_in ( Grouping_Priority_Circuit03_prio_4_s ),
    .Grouping_Priority_Circuit03_prio_5_in ( Grouping_Priority_Circuit03_prio_5_s ),
    .Grouping_Priority_Circuit03_prio_6_in ( Grouping_Priority_Circuit03_prio_6_s ),
    .Grouping_Priority_Circuit03_prio_7_in ( Grouping_Priority_Circuit03_prio_7_s ),
    .int_0_prio                            ( int_0_prio                           ),
    .int_3_prio                            ( int_3_prio                           ),
    .int_6_prio                            ( int_6_prio                           ),
    .int_10_prio                           ( int_10_prio                          ),
    .int_14_prio                           ( int_14_prio                          ),
    .int_18_prio                           ( int_18_prio                          ),
    .int_24_prio                           ( int_24_prio                          ),
    .int_27_prio                           ( int_27_prio                          ),
    .int_0_out                             ( chosen_int_0                         ),
    .int_3_out                             ( chosen_int_3                         ),
    .int_6_out                             ( chosen_int_6                         ),
    .int_10_out                            ( chosen_int_10                        ),
    .int_14_out                            ( chosen_int_14                        ),
    .int_18_out                            ( chosen_int_18                        ),
    .int_24_out                            ( chosen_int_24                        ),
    .int_27_out                            ( chosen_int_27                        )
);

assign chosen_NMI = pend_NMI;

endmodule

